= "Hibernate OGM 5 is out!"
Davide D'Alto
:awestruct-tags: [ "Hibernate OGM", "Releases" ]
:awestruct-layout: blog-post
---

http://hibernate.org/ogm/[Hibernate OGM] 5.0.0.Final is finally here!

== What's new?

Compared to the http://in.relation.to/2015/06/02/hibernate-ogm-42-final-is-out/[4.2.Final], this version includes:

* upgrade to http://hibernate.org/search[Hibernate ORM 5] and http://hibernate.org/search[Hibernate Search 5], so you can easily use it with http://wildfly.org[WildFly 10];
* integration with Redis as tech preview, including http://in.relation.to/2016/03/30/hibernate-ogm-5-CR1-released[Redis cluster support and hash mapping];
* upgrade to MongoDB Driver 3;
* http://in.relation.to/2015/12/21/hibernate-ogm-5-beta1-released/[Mapping support for Cassandra 2.2 new data types];
* http://in.relation.to/2015/12/21/hibernate-ogm-5-beta1-released/[PostLoad event support];
* http://in.relation.to/2015/12/21/hibernate-ogm-5-beta1-released/[Infinispan 8];
* http://in.relation.to/2016/03/30/hibernate-ogm-5-CR1-released[Additional MongoDB native CLI queries support];

There are also several bug fixes and you can find all the details in the
https://github.com/hibernate/hibernate-ogm/blob/7a28f25276d7344f91af8c93a7ec8b366fb1898a/changelog.txt[changelog].

A nice http://hibernate.org/ogm/documentation/getting-started[Getting started guide] 
is available on our website for people who want to start playing with it. A more in depth explanation
of all the details around Hibernate OGM is in the
http://docs.jboss.org/hibernate/ogm/5.0/reference/en-US/html[reference documentation].

If you need to upgrade from a previous version,
you can find help on the https://developer.jboss.org/wiki/HibernateOGMMigrationNotes[migration notes].

== What's coming next?

Now that Hibernate OGM 5 is out, we can focus on working on some new integrations like http://neo4j.com[Neo4j] remote
and http://infinispan.org/hotrod-clients[Hot Rod].

You can also have a look at the http://hibernate.org/ogm/roadmap[roadmap] for up-to-date news
about what's coming next.

If you think that something is missing or if you have some opinion about what we should include,
please, let us hear your voice.

== Where can I get it?

You can get Hibernate OGM 5.0.0.Final core via Maven using the following coordinates:

* _org.hibernate.ogm:hibernate-ogm-core:5.0.0.Final_ 

and these are the back-ends currently available:

* http://cassandra.apache.org[Cassandra]: _org.hibernate.ogm:hibernate-ogm-cassandra:5.0.0.Final_
* http://couchdb.apache.org[CouchDB]: _org.hibernate.ogm:hibernate-ogm-couchdb:5.0.0.Final_
* http://infinispan.org[Infinispan]: _org.hibernate.ogm:hibernate-ogm-infinispan:5.0.0.Final_
* http://www.ehcache.org[Ehcache]: _org.hibernate.ogm:hibernate-ogm-ehcache:5.0.0.Final_
* https://www.mongodb.com[MongoDB]: _org.hibernate.ogm:hibernate-ogm-mongodb:5.0.0.Final_
* http://neo4j.com[Neo4j]: _org.hibernate.ogm:hibernate-ogm-neo4j:5.0.0.Final_
* http://redis.io[Redis]: _org.hibernate.ogm:hibernate-ogm-redis:5.0.0.Final_

Alternatively, you can download archives containing all the binaries, source code and documentation
https://sourceforge.net/projects/hibernate/files/hibernate-ogm/5.0.0.Final[from SourceForge].

== How can I get in touch?

You can find us through the following channels:

* https://forum.hibernate.org/viewforum.php?f=31[User forum]
* https://hibernate.atlassian.net/browse/OGM[Issue tracker]
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list]
* http://stackoverflow.com[Stack Overflow]: we monitor the tag _hibernate-ogm_

We are looking forward to hear your feedback!

