= "Hibernate OGM 5.1 CR 1 is out"
Davide D'Alto
:awestruct-tags: [ "Hibernate OGM", "Releases" ]
:awestruct-layout: blog-post
---

Good news!

The first candidate release for https://hibernate.org/ogm/[Hibernate OGM] 5.1 is out.

Compared to http://in.relation.to/2017/01/05/hibernate-ogm-5-beta3-and-5[5.1 Beta3],
this release upgrades Hibernate Search to version 5.5.6.Final and supports 
MongoDB aggregate operation in native queries.

You can find all the details in the
https://hibernate.atlassian.net/issues/?jql=project=10160%20AND%20fixVersion=27501[5.1.0.CR1 changelog].

If you need to upgrade from a version before 5.0, you can find help on the
https://developer.jboss.org/wiki/HibernateOGMMigrationNotes[migration notes].

== Hibernate Search 5.5.6.Final

https://hibernate.org/search[Hibernate Search] transparently indexes your data and offers fast
full-text and geolocation search.

This version supports https://www.elastic.co/products/elasticsearch[Elasticsearch].

This means that now you can use Hibernate OGM to do CRUD operations on your favourite NoSQL
database while having it also transparently synchronize to an Elasticsearch cluster.

If you are not familiar with Hibernate Search you can find all the details about the latest
stable version in the
http://in.relation.to/2017/01/30/hibernate-search-5-6-0-Final-and-5-7-0-CR1[official blog].

== Aggregation in MongoDB

MongoDB native queries now support the
https://docs.mongodb.com/manual/aggregation[aggregation operation] syntax.

For example, this is now a valid native query:

====
[source,java]
----
String nativeQuery = "db.Poem.aggregate(["
                  + "{ '$match': "
                        + "{'$or': ["
                                 + "{'author': { '$regex': 'Oscar.*', '$options': 'i'}}, "
                                 + "{ 'name': { '$regex': 'Po.*'} }"
                        + "]}}, "
                  + "{ '$sort' : { 'name' : -1 } }"
                  + "])";

List<Poem> poems = (List<Poem>) em.createNativeQuery( nativeQuery, Poem.class ).getResultList();
----
====

== Where can I get it?

You can get the required core library using the following Maven coordinates:

* _org.hibernate.ogm:hibernate-ogm-core:5.1.0.CR1_ 

and these are the backends currently available for 5.1.0.CR1:

* http://cassandra.apache.org[Cassandra]: _org.hibernate.ogm:hibernate-ogm-cassandra:5.1.0.CR1_
* http://couchdb.apache.org[CouchDB]: _org.hibernate.ogm:hibernate-ogm-couchdb:5.1.0.CR1_
* http://infinispan.org[Infinispan] 
** Embedded: _org.hibernate.ogm:hibernate-ogm-infinispan:5.1.0.CR1_
** Remote: _org.hibernate.ogm:hibernate-ogm-infinispan-remote:5.1.0.CR1_
* http://www.ehcache.org[Ehcache]: _org.hibernate.ogm:hibernate-ogm-ehcache:5.1.0.CR1_
* https://www.mongodb.com[MongoDB]: _org.hibernate.ogm:hibernate-ogm-mongodb:5.1.0.CR1_
* http://neo4j.com[Neo4j]: _org.hibernate.ogm:hibernate-ogm-neo4j:5.1.0.CR1_
* http://redis.io[Redis]: _org.hibernate.ogm:hibernate-ogm-redis:5.1.0.CR1_

Alternatively, you can download archives containing all the binaries, source code and documentation
https://sourceforge.net/projects/hibernate/files/hibernate-ogm/5.1.0.CR1[from Sourceforge].

== What's next?

We are going to clean up the documentation and release 5.1 Final.

After that, we will focus on Hibernate OGM 5.2 which will support Hibernate ORM 5.2

== How can I get in touch?

You can find us through the following channels:

* https://forum.hibernate.org/viewforum.php?f=31[User forum]
* https://hibernate.atlassian.net/browse/OGM[Issue tracker]
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list]
* http://stackoverflow.com[Stack Overflow]: we monitor the tag _hibernate-ogm_
* https://hibernate.zulipchat.com/#narrow/stream/132091-hibernate-ogm-dev[Zulip]: Hibernate OGM Zulip stream

We are looking forward to hear your feedback!

