= "Hibernate OGM 5.1 Beta3 and 5.0.4 are out"
Davide D'Alto
:awestruct-tags: [ "Hibernate OGM", "Releases" ]
:awestruct-layout: blog-post
---

Hello everybody, holidays are over and we decided to start back with a small release.

http://hibernate.org/ogm/[Hibernate OGM] 5.1 Beta3 and a new 5.0 maintainance releases
are now available.

In these releases we fixed some issues around sequence generation and queries on
entities using the single table per class inheritance strategy.
An update is highly recommended.

Hibernate OGM 5.0.4.Final is backward compatible with 5.0.3.Final.
If you need to upgrade from a version before 5.0, you can find help on the
https://developer.jboss.org/wiki/HibernateOGMMigrationNotes[migration notes].

All the details about these releases are on the
https://github.com/hibernate/hibernate-ogm/blob/5.0.4.Final/changelog.tx[5.0.4.Final changelog],
the
https://github.com/hibernate/hibernate-ogm/blob/5.1.0.Beta2/changelog.txt[5.1.0.Beta2 changelog]
and the
https://github.com/hibernate/hibernate-ogm/blob/5.1.0.Beta3/changelog.txt[5.1.0.Beta3 changelog].

== What happened to 5.1 Beta2?

Think of it as the crazy uncle nobody wants to talk about, you should check 5.1 Beta3 instead.

== Where can I get them?

=== 5.0.4.Final

You can get the required core library using the following Maven coordinates:

* _org.hibernate.ogm:hibernate-ogm-core:5.0.4.Final_ 

and these are the backends currently available:

* http://cassandra.apache.org[Cassandra]: _org.hibernate.ogm:hibernate-ogm-cassandra:5.0.4.Final_
* http://couchdb.apache.org[CouchDB]: _org.hibernate.ogm:hibernate-ogm-couchdb:5.0.4.Final_
* http://infinispan.org[Infinispan]: _org.hibernate.ogm:hibernate-ogm-infinispan:5.0.4.Final_
* http://www.ehcache.org[Ehcache]: _org.hibernate.ogm:hibernate-ogm-ehcache:5.0.4.Final_
* https://www.mongodb.com[MongoDB]: _org.hibernate.ogm:hibernate-ogm-mongodb:5.0.4.Final_
* http://neo4j.com[Neo4j]: _org.hibernate.ogm:hibernate-ogm-neo4j:5.0.4.Final_
* http://redis.io[Redis]: _org.hibernate.ogm:hibernate-ogm-redis:5.0.4.Final_

Alternatively, you can download archives containing all the binaries, source code and documentation
https://sourceforge.net/projects/hibernate/files/hibernate-ogm/5.0.4.Final[from Sourceforge].

=== 5.1.0.Beta3

You can get the required core library using the following Maven coordinates:

* _org.hibernate.ogm:hibernate-ogm-core:5.1.0.Beta3_ 

and these are the backends currently available for 5.1.0.Beta3:

* http://cassandra.apache.org[Cassandra]: _org.hibernate.ogm:hibernate-ogm-cassandra:5.1.0.Beta3_
* http://couchdb.apache.org[CouchDB]: _org.hibernate.ogm:hibernate-ogm-couchdb:5.1.0.Beta3_
* http://infinispan.org[Infinispan] 
** Embedded: _org.hibernate.ogm:hibernate-ogm-infinispan:5.1.0.Beta3_
** Remote: _org.hibernate.ogm:hibernate-ogm-infinispan-remote:5.1.0.Beta3_
* http://www.ehcache.org[Ehcache]: _org.hibernate.ogm:hibernate-ogm-ehcache:5.1.0.Beta3_
* https://www.mongodb.com[MongoDB]: _org.hibernate.ogm:hibernate-ogm-mongodb:5.1.0.Beta3_
* http://neo4j.com[Neo4j]: _org.hibernate.ogm:hibernate-ogm-neo4j:5.1.0.Beta3_
* http://redis.io[Redis]: _org.hibernate.ogm:hibernate-ogm-redis:5.1.0.Beta3_

Alternatively, you can download archives containing all the binaries, source code and documentation
https://sourceforge.net/projects/hibernate/files/hibernate-ogm/5.1.0.Beta3[from Sourceforge].

== What's next?

We are getting ready for the first 5.1 candidate release.

== How can I get in touch?

You can find us through the following channels:

* https://forum.hibernate.org/viewforum.php?f=31[User forum]
* https://hibernate.atlassian.net/browse/OGM[Issue tracker]
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list]
* http://stackoverflow.com[Stack Overflow]: we monitor the tag _hibernate-ogm_
* https://hibernate.zulipchat.com/#narrow/stream/132091-hibernate-ogm-dev[Zulip]: Hibernate OGM Zulip stream

We are looking forward to hear your feedback!

