= "Hibernate OGM 5.4.0.Final release"
Davide D'Alto
:awestruct-tags: [ "Hibernate OGM", "Releases" ]
:awestruct-layout: blog-post
---

https://hibernate.org/ogm/releases/5.4/#get-it[Hibernate OGM 5.4.0.Final] has been released!

Here's a list of the main changes compared to version http://in.relation.to/2018/03/29/hibernate-ogm-5-3-1-Final-released/[5.3.1.Final]:

* Infinispan remote https://docs.jboss.org/hibernate/ogm/5.4/reference/en-US/html_single/#infinispan-remote-transaction[transactions over HotRod] client
* https://docs.jboss.org/hibernate/ogm/5.4/reference/en-US/html_single/#_remote_query_capabilities[JPQL and native queries] support for Infinispan remote
* https://docs.jboss.org/hibernate/ogm/5.4/reference/en-US/html_single/#_infinispan_remote_stored_procedures[server side procedures calls] for Infinispan Remote
* Cache creation and configuration for https://docs.jboss.org/hibernate/ogm/5.4/reference/en-US/html_single/#infinispan-remote-cache-configuration[Infinispan remote]
* Java types `java.time.LocalDate`, `java.time.LocalDateTime` and `java.time.LocalTime` are natively supported as field types
* https://docs.jboss.org/hibernate/ogm/5.4/reference/en-US/html_single/#mongodb-gridfs-support[GridFS support for MongoDB]
* Neo4j remote procedures support via JPA

More details available in the
https://hibernate.atlassian.net/issues/?jql=project=10160%20AND%20fixVersion=31724[release notes].

== Components upgrade

* Hibernate ORM 5.3.4.Final
* Hibernate Search 5.10.4.Final
* Infinispan 9.4.0.Final
* Neo4j 3.4.9

== Where can I get Hibernate OGM?

You can include the dialect of your choice in your project using the following Maven coordinates:

* http://infinispan.org[Infinispan]
** Remote: _org.hibernate.ogm:hibernate-ogm-infinispan-remote:5.4.0.Final_
** Embedded: _org.hibernate.ogm:hibernate-ogm-infinispan-embedded:5.4.0.Final_
* https://www.mongodb.com[MongoDB]: _org.hibernate.ogm:hibernate-ogm-mongodb:5.4.0.Final_
* http://neo4j.com[Neo4j]: _org.hibernate.ogm:hibernate-ogm-neo4j:5.4.0.Final_
** Infinispan Remote: _org.hibernate.ogm:hibernate-ogm-featurepack-infinispan-remote:5.4.0.Final_
** Infinispan Embedded: _org.hibernate.ogm:hibernate-ogm-featurepack-infinispan-embedded:5.4.0.Final_
** MongoDB: _org.hibernate.ogm:hibernate-ogm-featurepack-mongodb:5.4.0.Final_
** Neo4j: _org.hibernate.ogm:hibernate-ogm-featurepack-neo4j:5.4.0.Final_

Alternatively, you can download archives containing all the binaries, source code and documentation
https://sourceforge.net/projects/hibernate/files/hibernate-ogm/5.4.0.Final[from Sourceforge].

If you are interested about available versions, you can check the official
https://hibernate.org/ogm/releases[Hibernate OGM download page].

== How can I get in touch?

You can find us through the following channels:

* https://discourse.hibernate.org/c/hibernate-ogm[User forum]
* https://hibernate.atlassian.net/browse/OGM[Issue tracker]
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list]
* http://stackoverflow.com[Stack Overflow]: we monitor the tag _hibernate-ogm_
* https://hibernate.zulipchat.com/#narrow/stream/132091-hibernate-ogm-dev[Zulip]: Hibernate OGM Zulip stream

== Contributions

Thanks a lot to our contributors (in order of appearance in the commit log):
Anastasiia Gavrilash, Aleksandr Mylnikov, Volodymyr Trytsetskyi,
The Viet Nguyen and Sergey Chernolyas.

Without them, Hibernate OGM 5.4 Final wouldn't have some of the new features we were
able to include. You rock!

Looking forward to hearing your feedback!

