= "Hibernate OGM 5.4.1.Final release"
Davide D'Alto
:awestruct-tags: [ "Hibernate OGM", "Releases" ]
:awestruct-layout: blog-post
---

https://hibernate.org/ogm/releases/5.4/#get-it[Hibernate OGM 5.4.1.Final] has been released!

The feature packs included in this release are now compatible with WildFly 14 and we added
support for the `@OrderBy` annotation.

A special thanks to our contributors!

https://github.com/gitdude1458[gtdude1458] found and fixed a
https://hibernate.atlassian.net/browse/OGM-1544[concurrency bug] in the MongoDB dialect.

Aleksandr Mylnikov worked on the the MongoDB dialect and it now supports 
https://hibernate.atlassian.net/browse/OGM-1542[HQL select count distinct] queries.

More details available in the
https://hibernate.atlassian.net/issues/?jql=project=10160+AND+fixVersion=31741[release notes].

== Components upgrade

* Neo4j 3.4.10
* Neo4j java driver 1.7.2
* MongoDB java driver 3.9.1

== Where can I get Hibernate OGM?

You can include the dialect of your choice in your project using the following Maven coordinates:

* http://infinispan.org[Infinispan]
** Remote: _org.hibernate.ogm:hibernate-ogm-infinispan-remote:5.4.1.Final_
** Embedded: _org.hibernate.ogm:hibernate-ogm-infinispan-embedded:5.4.1.Final_
* https://www.mongodb.com[MongoDB]: _org.hibernate.ogm:hibernate-ogm-mongodb:5.4.1.Final_
* http://neo4j.com[Neo4j]: _org.hibernate.ogm:hibernate-ogm-neo4j:5.4.1.Final_
** Infinispan Remote: _org.hibernate.ogm:hibernate-ogm-featurepack-infinispan-remote:5.4.1.Final_
** Infinispan Embedded: _org.hibernate.ogm:hibernate-ogm-featurepack-infinispan-embedded:5.4.1.Final_
** MongoDB: _org.hibernate.ogm:hibernate-ogm-featurepack-mongodb:5.4.1.Final_
** Neo4j: _org.hibernate.ogm:hibernate-ogm-featurepack-neo4j:5.4.1.Final_

Alternatively, you can download archives containing all the binaries, source code and documentation
https://sourceforge.net/projects/hibernate/files/hibernate-ogm/5.4.1.Final[from Sourceforge].

If you are interested about available versions, you can check the official
https://hibernate.org/ogm/releases[Hibernate OGM download page].

== How can I get in touch?

You can find us through the following channels:

* https://discourse.hibernate.org/c/hibernate-ogm[User forum]
* https://hibernate.atlassian.net/browse/OGM[Issue tracker]
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list]
* http://stackoverflow.com[Stack Overflow]: we monitor the tag _hibernate-ogm_
* https://hibernate.zulipchat.com/#narrow/stream/132091-hibernate-ogm-dev[Zulip]: Hibernate OGM Zulip stream

Looking forward to hearing your feedback!

