= "Hibernate OGM 5.4.0.Beta1 release"
Davide D'Alto
:awestruct-tags: [ "Hibernate OGM", "Releases" ]
:awestruct-layout: blog-post
---

https://hibernate.org/ogm/releases/5.4/#get-it[Hibernate OGM 5.4.0.Beta1] has been released!

The main differences from the previous release is the upgrade to Hibernate ORM 5.3.0.Final, 
the support for Infinispan Remote native and JPQL queries (without requiring Hibernate Search),
and the use of cluster counters for local caches when generating sequences with Infinispan Embedded.

More detail available in the 
https://hibernate.atlassian.net/issues/?jql=project=10160+AND+fixVersion=31660[release notes].

== Hibernate ORM 5.3

Hibernate ORM 5.3 has a huge list of improvements, most notably it implements JPA 2.2.

You can find all the details about it in the 
http://in.relation.to/2018/05/14/hibernate-orm-530-final-release/[Hibernate ORM 5.3.0.Final release post].

== Infinispan Remote queries

You can execute queries in Infinispan using the query language called
https://blog.infinispan.org/2016/12/meet-ickle.html[Ickle]. This latest version of Hibernate OGM
will convert the JPQL queries into an equivalent in Ickle. You can also run native query directly.

Here is an example of a native query execution:

====
[source, JAVA]
----
String ickleQuery = "from HibernateOGMGenerated.Registry where level > 3 order by start"
List result = session.createNativeQuery( ickleQuery )
				.addEntity( Employee.class )
				.list();
----
====

With Ickle you can also write queries which use Infinispan's full-text capabilities backed by Apache Lucene, as long as the field is indexed. It's a nice language combining some notions from JPQL and the Lucene query languages.

Note that this will only work if the cache already exists on the server and the
fields are indexed. Currently Hibernate OGM is able to automatically generate protobuf schemas but the generated metadata will not include index definitions, so you might need to add these as needed.

== Where can I get Hibernate OGM?

You can include in your project the dialect of your choice using these Maven coordinates:

* http://infinispan.org[Infinispan]
** Remote: _org.hibernate.ogm:hibernate-ogm-infinispan-remote:5.4.0.Beta1_
** Embedded: _org.hibernate.ogm:hibernate-ogm-infinispan-embedded:5.4.0.Beta1_
* https://www.mongodb.com[MongoDB]: _org.hibernate.ogm:hibernate-ogm-mongodb:5.4.0.Beta1_
* http://neo4j.com[Neo4j]: _org.hibernate.ogm:hibernate-ogm-neo4j:5.4.0.Beta1_
** Infinispan Remote: _org.hibernate.ogm:hibernate-ogm-featurepack-infinispan-remote:5.4.0.Beta1_
** Infinispan Embedded: _org.hibernate.ogm:hibernate-ogm-featurepack-infinispan-embedded:5.4.0.Beta1_
** MongoDB: _org.hibernate.ogm:hibernate-ogm-featurepack-mongodb:5.4.0.Beta1_
** Neo4j: _org.hibernate.ogm:hibernate-ogm-featurepack-neo4j:5.4.0.Beta1_

Alternatively, you can download archives containing all the binaries, source code and documentation
https://sourceforge.net/projects/hibernate/files/hibernate-ogm/5.4.0.Beta1[from Sourceforge].

If you are interested about available versions, you can check the official
https://hibernate.org/ogm/releases[Hibernate OGM download page].

== How can I get in touch?

You can find us through the following channels:

* https://discourse.hibernate.org/c/hibernate-ogm[User forum]
* https://hibernate.atlassian.net/browse/OGM[Issue tracker]
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list]
* http://stackoverflow.com[Stack Overflow]: we monitor the tag _hibernate-ogm_
* https://hibernate.zulipchat.com/#narrow/stream/132091-hibernate-ogm-dev[Zulip]: Hibernate OGM Zulip stream

== Contributions

Some of the new features have been contributed by 
Bato-Bair, Sergey Chernolyas and The Viet Nguyen.
Thanks a lot!

We are looking forward to hearing your feedback!

