= Hibernate Reactive 1.0.0.CR7 released
Davide D'Alto
:awestruct-tags: [ "Hibernate Reactive" ]
:awestruct-layout: blog-post
---

:getting-started: http://hibernate.org/reactive/documentation/1.0/reference/html_single/#getting-started

Hibernate Reactive 1.0.0.CR7 is out and is now licensed under the https://opensource.org/licenses/Apache-2.0[Apache License, Version 2.0].

This version also contains some https://github.com/hibernate/hibernate-reactive/issues/836[performance improvements],
adds a https://github.com/hibernate/hibernate-reactive/issues/807[new method `SessionFactory#withStatelessTransaction`],
upgrades to https://in.relation.to/2021/06/15/hibernate-orm-552-release/[Hibernate ORM 5.5.2.Final] and
supports the use of https://github.com/hibernate/hibernate-reactive/issues/856[`hibernate.jdbc.time_zone` for time types].

You can find a complete list of changes on https://github.com/hibernate/hibernate-reactive/milestone/9?closed=1[the Hibernate Reactive issue tracker].

Thank you!

== How can I get it?

All details are available on the 
link:https://hibernate.org/reactive/releases/1.0/#get-it[Hibernate Reactive website releases page].

If you are new to Hibernate Reactive, {getting-started}[the official documentation] is a good place to start.

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-reactive[**hibernate-reactive** tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-reactive[User forum] or the https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user[**hibernate-user** stream on Zulip] (usage questions, general feedback)
* https://github.com/hibernate/hibernate-reactive/issues[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] or the https://hibernate.zulipchat.com/#narrow/stream/205413-hibernate-reactive-dev[**hibernate-reactive-dev** stream on Zulip] (development-related discussions)
