= "Hibernate Reactive: Beta 3"
Davide D'Alto
:awestruct-tags: [ "Hibernate Reactive", "Releases" ]
:awestruct-layout: blog-post
:released-version: 1.0.0.Beta3
---

This exciting new project was announced by Gavin King a couple of months ago; if you've missed it please check
https://in.relation.to/2020/12/03/hibernate-reactive/[Introducing Hibernate Reactive].

= Hibernate Reactive 1.0.0.Beta3

Hibernate 1.0.0.Beta3 contains several performance improvements and the intial support for the annotation `@ElementCollection`.

This release is compatible with https://in.relation.to/2021/02/09/hibernate-orm-5428-final-release/[Hibernate ORM 5.4.28.Final].
It's also included in Quarkus via the Hibernate Reactive extension,  this means that you can compile your reactive
application to native code thanks to https://www.graalvm.org[GraalVM!].

== Where can I get it?

It's available on https://bintray.com/hibernate/artifacts/hibernate-reactive/1.0.0.Beta3[Bintray]
and https://search.maven.org/artifact/org.hibernate.reactive/hibernate-reactive-core/1.0.0.Beta3/jar[Maven Central]
and you can include it in your project using the following GAV coordinates:

* _org.hibernate.reactive:hibernate-reactive-core:1.0.0.Beta3_

Or, if you are using Quarkus, via the Hiberante Reactive extension:

* _io.quarkus:quarkus-hibernate-reactive:<quarkus-version>_

More details and the documentation are available on the http://hibernate.org/reactive[Hibernate Reactive website].

== Quarkus Quickstarts

You can find a couple of Quarkus quickstarts on GitHub:
* https://github.com/quarkusio/quarkus-quickstarts/tree/master/hibernate-reactive-quickstart[Hibernate Reactive with RESTEasy Reactive] quickstart
* https://github.com/quarkusio/quarkus-quickstarts/tree/master/hibernate-reactive-routes-quickstart[Hibernate Reactive with Vert.x Web Routes] quickstart

Or you can https://code.quarkus.io/?g=org.acme&a=code-with-quarkus&v=1.0.0-SNAPSHOT&b=MAVEN&s=r1s&cn=code.quarkus.io[generate a new Quarks project]
that uses the Hibernate Reactive extension and start coding right away.

== Feedback, issues, ideas?

Please try it out and let us know what you think of it and what you'd like to see improved.
Patches are very welcome as well.

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate-reactive[**hibernate-reactive** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-reactive[User forum] (usage questions, general feedback)
* https://github.com/hibernate/hibernate-reactive/issues[Issue tracker] (bug reports, feature requests, propose patches)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
* https://hibernate.zulipchat.com/#narrow/stream/205413-hibernate-reactive-dev[Chat] (usage and development-related discussions)
