= How to build in.relation.to
:awestruct-layout: title-nocol
:toc:
:toc-placement: preamble

A bit of Git, a bit of Ruby and you will get your local in.relation.to served.

== Prerequisites

* Get http://git-scm.com[Git]
* Get https://www.ruby-lang.org/en/[Ruby] > 1.9

== Installation

=== Ensure Rake is installed

Make sure https://github.com/jimweirich/rake[Rake] is available. It is often installed per default.

[source]
----
> rake --version
----

If you get "_command not found_":

[source]
----
> gem install rake
----

=== Ensure Bundler is installed

Make sure http://bundler.io/[Bundler] is available. It manages your Ruby gems locally to the project
and prevents version conflicts between different Ruby projects. To quote from the website:

____
Bundler provides a consistent environment for Ruby projects by tracking and installing the exact
gems and versions that are needed.
____

[source]
----
> bundle -v
----

If you get "_command not found_":

[source]
----
> gem install bundler
----

=== Get the source

[source]
----
> git clone git@github.com:hibernate/in.relation.to.git
> cd in.relation.to
----

=== Setup awestruct

[source]
----
> rake setup
> rake check
----

=== Serve the site locally

[source]
----
rake preview
----

Point your browser to http://localhost:4242. Per default the site is generated with
the _editor_ profile enabled. In this profile posts per tag and author are not
generated. The main purpose of this mode is to generate a new blog entry.
If you want the full site generated you should use:

[source]
----
rake preview[development]
----

or

[source]
----
rake preview[production]
----

== Preview changes on staging.in.relation.to

Use git to push on the _staging_ branch on GitHub.
You might need to use "git push --force" to overwrite previous experiments;
possibly check when doing so to not interfere with someone else also looking to publish a preview.

Pushing on this branch will trigger a build at http://ci.hibernate.org/view/Website/job/staging.in.relation.to/[the CI Server],
if the build is successfull your changes should be visibile on http://staging.in.relation.to.org/[the staging website].

== Publish changes to "live" production

Use git to push on the _production_ branch on GitHub.

In this case, never use "--force" !
If you have a push error, please rebase first, and possibly repeat the staging phase.

Also in this case a build is triggered on http://ci.hibernate.org/view/Website/job/in.relation.to/[the CI Server],
and if successfull the content is then visible on http://in.relation.to.org/[the public blog].


== Tips & Tricks

=== Which other tasks exist in the Rake build file?

[source]
----
> rake --tasks
----

This will list the available tasks with a short description

=== I am getting errors when trying to execute *awestruct* directly

You need to use `bundle exec <command>` to make sure you get all required Gems. Check the *Rakefile*
to see how the different awestruct calls are wrapped.

=== If your changes are not visible...

Panic! Then completely regenerate the site via:

[source]
----
> rake clean preview
----

== License

The content of this repository is released under the link:http://www.apache.org/licenses/LICENSE-2.0.txt[ASL 2.0].

By submitting a "pull request" or otherwise contributing to this repository, you
agree to license your contribution under the respective licenses mentioned above.

== Acknowledgements

This website uses https://github.com/jbossorg/bootstrap-community[JBoss Community Bootstrap].

