= Meet Martin Braun, the youngest Hibernate contributor
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate Search" ]
:awestruct-layout: blog-post
---

In this post, I'd like you to meet Martin, who, in spite of his young age, has been very active in the Hibernate Search project development,
implementing some interesting extensions or helping with pull request reviewing.

Because I'd love to see more university students getting involved with open source software, I took this opportunity and interviewed Martin about this experience.

. *Hi, Martin. You are one of the youngest contributors we've ever had. Can you please introduce yourself?*
+
Hi, Vlad. I am a 22-year-old Master's Degree student at University of Bayreuth, Germany and have been
interested in Hibernate Search and Fulltext Search (Lucene, Solr) for quite some time now. I am also a firm believer of
Open Source and have actually always wanted to become a contributor of a tool (or software) many other
developers use in their projects. Knowing that a piece of code you wrote is running in other systems is quite the
rewarding feeling.
+
. *I understand that you took part in the Google Summer of Code event. Can you tell us a little bit about this program?*
+
Yes, I took part in last years Google Summer of Code program and was mentored by Sanne Grinovero
while working on adapting Hibernate Search to work with any JPA provider. It gave me the opportunity
to dive more deeply into the codebase as it allowed me to concentrate on nothing but my project work-wise.
In general Google Summer of Code is one of the best learning experiences any student that wants to get into
Open Source can have.

. *Contributing to an open-source project is a great learning experience. Has this activity helped you improve your skills?*
+
Definitely. While building new features or tracking down bugs, you encounter loads of different pieces of
code you have to work through. With that comes learning new technologies and APIs. Also, the general
process of submitting JIRA issues, discussing them and implementing the solutions is something you
can learn while working on an open source project. Trying out the process yourself is invaluable and cannot be compared
to just learning them on paper. This is also something I always tell to new coders: Try it out or you will not get it 100%.

. *Do you think the entry barrier is high for starting contributing to an open source project? How should we encourage students to getting involved with open source?*
+
In the case of the Hibernate team, I can only say that it was quite easy to get into contact with the other developers.
I just got onto IRC and asked questions about problems I had. They helped me with every question I had, so I stuck around.
Then, I started reporting issues or making feature requests and was immediately incorporated into discussions. So no, the barrier
is not high (at least for me in the case of the Hibernate team).
+
I think open source needs to be encouraged more at a university level. I think many students don't realize what they are missing.
Yes, open standards are encouraged and teaching uses open APIs all over the place, but universities tend to keep much of the
work that is suitable for open source behind closed doors (btw: I don't think that closed source is always a bad thing, but it sometimes
is in the way of innovation).
+
. *What are your plans for the future?*
+
Firstly, I want to finish my Masters degree at University. I haven't fully decided yet,
whether I want to stay at University or not. Time will tell, I guess.
Secondly, I want to keep contributing to Hibernate Search and finish merging
the features of last years Google Summer of Code into the core code base.

*Thank you, Martin, and keep up the good work.*