= Hibernate Community Newsletter 17/2016
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM", "Newsletter" ]
:awestruct-layout: blog-post
---

Welcome to the Hibernate community newsletter in which we share blog posts, forum, and StackOverflow questions that are especially relevant to our users.

== Articles

Fitbit is using Hibernate for data persistence. On their engineering blog, they published an article about https://eng.fitbit.com/instrumenting-hibernate-connection-providers/[connection provider instrumentation].
Although this is a very clever solution, in case you need a solution for monitoring connection pool usage, I'd suggest using https://github.com/vladmihalcea/flexy-pool[FlexyPool] instead.

I've run a survey on my Twitter account to find out the JPA provider market share in 2016.
Just like in https://zeroturnaround.com/rebellabs/java-tools-and-technologies-landscape-for-2014/10/[2014] and https://blogs.oracle.com/theaquarium/entry/dzone_survey_shows_jpa_dominates[2015], https://vladmihalcea.com/jpa-providers-market-share-in-2016/[Hibernate is leading by a very large margin].
Thanks for choosing Hibernate, and stay tuned for even more great features.

You can use the Fluent Interface pattern with Hibernate and JPA. Check out https://vladmihalcea.com/how-to-increment-the-parent-entity-version-whenever-a-child-entity-gets-modified-with-jpa-and-hibernate/[this post for more details].

Anghel Leonard has added comprehensive list of test cases for both Hibernate ORM and OGM on http://java-ee-articles.blogspot.ro[his blog] and https://github.com/AnghelLeonard[GitHub repository].

Thorben Janssen wrote a series of articles related to:

* http://www.thoughts-on-java.org/get-query-results-stream-hibernate-5/[Using Java 1.8 Streams with Hibernate 5.2]
* http://www.thoughts-on-java.org/benefits-repeatable-annotations-hibernate-5-2/[The benefits of Repeatable annotations in Hibernate 5.2]
* http://www.thoughts-on-java.org/hibernate-tips-define-query-timeout/[How to define a Query Timeout with JPA and Hibernate]

Hibernate has great support for concurrency control.
In https://vladmihalcea.com/how-to-increment-the-parent-entity-version-whenever-a-child-entity-gets-modified-with-jpa-and-hibernate/[this article],
you can find out how you can increment a root entity version whenever any child entity is being added/removed or even modified.

== Time to upgrade

http://in.relation.to/2016/08/12/hibernate-orm-511-final-release/[Hibernate 5.1 has got a new release]. Check out https://hibernate.atlassian.net/issues/?jql=project=10031+AND+fixVersion=22550[the impressive amount of bug fixes].

== Questions and answers

* https://forum.hibernate.org/viewtopic.php?f=1&t=1043518[How to map a table name dynamically?]
* http://stackoverflow.com/questions/17780927/how-to-find-a-reasonable-size-for-connection-pooling-and-how-to-verify-it/38866022#38866022[How to find a reasonable size for a database connection pool and how to verify it?]
* http://stackoverflow.com/questions/38928741/does-hibernate-5-supports-xml-based-entity-mapping/38939467#38939467[Does Hibernate 5 supports XML based entity mapping?]
* https://www.quora.com/How-do-you-serialize-Hibernate-classes-in-Java/answer/Vlad-Mihalcea-1?srid=agud[How do you serialize Hibernate classes in Java?]
* https://www.quora.com/How-much-time-will-it-take-to-learn-Spring-framework-and-Hibernate-properly/answer/Vlad-Mihalcea-1[How much time will it take to learn Spring framework and Hibernate properly?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043545[Mapping entities across two databases via a key, not an id]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043547[Performance issues while coding Multitenancy in Hibernate]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043554[How can I configure StatementInspector in Hibernate?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043555[Why does JOIN FETCH return duplicates?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043558[Select (for version column) not being generated after an update]
* https://www.quora.com/What-do-you-use-as-property-of-hbm2dll-auto-in-hibernate-cfg-file-in-production/answer/Vlad-Mihalcea-1[What do you use as property of hbm2dll.auto in hibernate.cfg file in production?]


