= Hibernate Community Newsletter 2/2016
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM" ]
:awestruct-layout: blog-post
---

Starting this year, we are hosting http://in.relation.to/2016/01/04/hibernate-community-newsletter-2016-1/[a series of articles] focused on the Hibernate community.
We share blog posts, forum and StackOverflow questions that are especially relevant to our users.

== Articles

A very interesting project is http://trafodion.apache.org/[Apache Trafodion], which aims to build a transactional SQL engine on top of Hadoop.
We'd like to thanks the Trafodion team for writing a https://esgyn.com/trafodion-dialect-hibernate/[Hibernate Dialect], therefore making it possible to access Hadoop from a Hibernate data access layer.
Give it a try and let us know what you think.

Thorben Janssen wrote an article about http://www.thoughts-on-java.org/jpa-native-queries/[calling native SQL queries from JPA].

Romain Manni-Bucau demonstrates how you can integrate https://rmannibucau.wordpress.com/2016/01/14/jpa-java8-stream-paginated-findall/[JPA pagination with Java 8 Streams].

http://michael-simons.eu/[Michael J. Simons], who gave us the idea of writing the http://in.relation.to/2016/01/14/hibernate-jpa-test-case-template/[JPA test case templates],
describes the http://info.michael-simons.eu/2016/01/14/spring-boot-based-site-and-api-for-euregjug/[EuregJUG site] architecture which, along other open-source frameworks, makes use of Hibernate for accessing data.

== Questions and answers

* http://stackoverflow.com/questions/34588354/difference-between-size-length-and-columnlength-value/34589474#34589474[What's the difference between `@Size`, `@Length` and `@Column(length=value)`?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1042886&p=2488533#p2488533[What's the difference between a bidirectional `@ManyToMany` relationship and two `@OneToMany` associations on the junction table?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1042929&p=2488605#p2488605[How to do HQL join with a collection of primitive elements?]
* http://stackoverflow.com/questions/34738708/how-to-insert-data-as-fast-as-possible-with-hibernate/34744739#34744739[How to insert data as fast as possible with Hibernate?]
* http://stackoverflow.com/questions/34739475/get-max-value-from-table-using-hibernate/34745183#34745183[How to get the entity with the maximum id value with Hibernate?]
* https://stackoverflow.com/questions/34731783/how-to-register-custom-identifiergenerator-in-hibernate-jpa-entitymanager/34747951#34747951[How to register custom `IdentifierGenerator` in Hibernate JPA `EntityManager`?]
* http://stackoverflow.com/questions/34800788/does-statelesssession-support-lazy-loading[Does StatelessSession support lazy loading?]
