= Hibernate Community Newsletter 20/2016
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM", "Newsletter" ]
:awestruct-layout: blog-post
---

Welcome to the Hibernate community newsletter in which we share blog posts, forum, and StackOverflow questions that are especially relevant to our users.

== Articles

Steven Feuerstein, a well-known Oracle PL/SQL author, wrote an article in which he's http://stevenfeuersteinonplsql.blogspot.ro/2016/09/looking-for-stories-about-using.html[Looking for stories about using Hibernate with Oracle Database].
Hibernate ORM is very suitable for OLTP, especially for writing to the database. Check out http://stevenfeuersteinonplsql.blogspot.ro/2016/09/looking-for-stories-about-using.html#comments[the comment section] for more details.

Since Hibernate 5.2, you can now configure the JDBC batch size on a per Session basic. Check out https://vladmihalcea.com/how-to-customize-the-jdbc-batch-size-for-each-persistence-context-with-hibernate/[this article for more details] about this new feature.

Thorben Janssen wrote an article about http://www.thoughts-on-java.org/query-complex-jpa-hibernate/[JPQL query capabilities and limitations].

If you want to use Java 1.8 `Optional` with JPA entities, check out https://vladmihalcea.com/the-best-way-to-map-a-java-1-8-optional-entity-attribute-with-jpa-and-hibernate/[this post] for how you can do it without affecting other Java EE guarantees.

SitePoint has published a new article about https://www.sitepoint.com/schema-migration-hibernate-flywaydb/[Hibernate schema migrations with FlywayDB].
Although Hibernate comes with a schema generation tool, for a production environment, an automatic schema management tool that uses database-specific scripts is a much better choice.

== Time to upgrade

We have released http://in.relation.to/2016/10/03/hibernate-orm-523-final-release/[Hibernate ORM 5.2.3] and http://in.relation.to/2016/10/06/TripleHibernateSearchRelease/[three versions of Hibernate Search]:

5.6.0.Beta3:: The latest version of our main development branch, with experimental Elasticsearch integration.

5.7.0.Alpha1:: Essentially the same as 5.6.0.Beta3, but compatible with Hibernate ORM version 5.2.x.

5.5.5.Final:: A maintenance release of our stable branch.

== Questions and answers

* http://stackoverflow.com/questions/30976896/merging-a-managed-entity-on-the-manytoone-side/30977677#30977677[Merging a managed entity on the ``@ManyToOne` side]
* http://stackoverflow.com/questions/39794782/in-hibernate-jpa-how-to-transparently-solve-failed-to-lazily-initialize-a-coll/39794892#39794782[In Hibernate JPA, how to transparently solve “failed to lazily initialize a collection of role” exception?]
* http://stackoverflow.com/questions/34738708/how-to-insert-data-as-fast-as-possible-with-hibernate/34744739#34744739[How to insert data as fast as possible with Hibernate?]
* https://forum.hibernate.org/viewtopic.php?p=2490558[MappedSuperClass using id to calculate equals/hashCode]
* https://forum.hibernate.org/viewtopic.php?p=2490495[Hibernate XAResource for JTA transaction management]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043652[Integrate JBoss Narayana transaction manager with Hibernate]
* https://forum.hibernate.org/viewtopic.php?p=2490504[pg-uuid with `String` getter and setter]
* https://forum.hibernate.org/viewtopic.php?p=2490505[Creating Configuration object inside doGet method of servlet]
* https://forum.hibernate.org/viewtopic.php?p=2490520[MySQL schema issue when migrating Hibernate 4 to 5]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043651[EJB and JTA sync problems between process]
