= Hibernate Community Newsletter 10/2016
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM", "Newsletter" ]
:awestruct-layout: blog-post
---

Welcome to the Hibernate community newsletter in which we share blog posts, forum, and StackOverflow questions that are especially relevant to our users.

== Events

C2B2 and Red Hat are hosting a http://www.meetup.com/JBoss-User-Group/events/230987571/[Hibernate Q&A event], so
if you are in London on May 24th, you now have the opportunity of meeting some of the developers that are behind Hibernate ORM, OGM, Search, and Validator.

== Articles

* Thorben Janssen wrote a very good article about http://www.thoughts-on-java.org/how-to-join-unrelated-entities/[joining unrelated entities] using JPA
and the new Hibernate 5.1 new joining feature.
* For out Portuguese readers, Emmanuel Neri wrote a short article about https://emmanuelnerisouza.wordpress.com/2016/05/08/usando-localdatejava-8-no-hibernate4-jpa-2-1/[mapping `LocalDate` with Hibernate 4 and Spring].
While Hibernate 5 already comes with the `hibernate-java8` module, for Hibernate 4 you need to use a JPA converter or a Hibernate custom type.
* I wrote a guide about https://vladmihalcea.com/how-to-call-sql-server-stored-procedures-and-functions-from-hibernate/[calling SQL Server stored procedure from Hibernate], and another article about https://vladmihalcea.com/the-best-way-of-logging-jdbc-statements/[logging JDBC statements] along with their bind parameter values.

== Videos

The Devoxx France 2016 videos are available on YouTube, so, if you know French, you should definitely watch Emmanuel Bernard' talks on https://www.youtube.com/watch?v=SJaLBX2Yv5o[Hibernate projects latest features], as well as the one about the https://www.youtube.com/watch?v=pQJY-Mu-yGA[Elasticsearch support that is being integrated into Hibernate Search].

If you want to learn how to boost your data access layer performance, you should check my https://www.youtube.com/watch?v=BTdTEe9QL5k&t=1s[High-Performance Hibernate] talk as well.

== Questions and answers

* https://forum.hibernate.org/viewtopic.php?f=1&t=1043217&p=2489444#p2489444[Replacement example for EJ3BNamingStrategy]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043221&p=2489447#p2489447[Hibernate 4.2.17 and MySQL 5.7]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043223&start=0[Hibernate 5.1.0 with MySQL "Text" field java.lang.ArrayIndexOutOfBoundsException]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043227&p=2489479#p2489479[Migration from Hibernate 3.3 to 5.1, SchemaUpdate issue]
* http://stackoverflow.com/questions/36920695/hibernate-and-transaction-using-method-annotation/36930696#36930696[Is it possible to multiplex multiple read-only transactions on a single JDBC Connection?]
