= Hibernate Community Newsletter 21/2016
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM", "Newsletter" ]
:awestruct-layout: blog-post
---

Welcome to the Hibernate community newsletter in which we share blog posts, forum, and StackOverflow questions that are especially relevant to our users.

== Articles

Don't miss our Hibernate developer interviews with http://in.relation.to/2016/10/11/meet-petar-tahchiev/[Petar Tahchiev] and http://in.relation.to/2016/10/21/meet-michael-simons/[Michael Simons].

If you're curious how you can control the SQL `UPDATE` statement generated by Hibernate, check out https://vladmihalcea.com/2016/10/11/how-to-update-only-a-subset-of-entity-attributes-using-jpa-and-hibernate/[this article].

Thorben Janssen wrote an article about http://www.thoughts-on-java.org/persist-creation-update-timestamps-hibernate/[persisting the creation timestamp for a particular entity].

https://www.optaplanner.org/[OptaPlanner] is an open source project aiming to optimize business resource planning.
Because persistence is a very common requirement for business applications, OptaPlanner offers support for JPA and Hibernate.
Check out https://www.optaplanner.org/blog/2015/09/23/IntegratingJpaHibernateWithOptaPlanner.html[this post] to find out more about integrating Hibernate into OptaPlanner.

Implementing `equals` and `hashCode` for JPA entities requires you to take into account all https://vladmihalcea.com/2014/07/30/a-beginners-guide-to-jpahibernate-entity-state-transitions/[entity state transitions].
For this reason, I wrote a summary of https://vladmihalcea.com/2016/10/20/the-best-way-to-implement-equals-hashcode-and-tostring-with-jpa-and-hibernate/[how you should implement `equals` and `hashCode` for both natural identifiers and synthetic keys].

== Time to upgrade

Hibernate OGM 5.1.Alpha1 and 5.0.2.Final have been released. Check out http://in.relation.to/2016/10/10/hibernate-ogm-5-1-alpha-and-5-0-2-released/[this post] for more details.

Hibernate Validator 5.3.0.Final has been released as well. Check out http://in.relation.to/2016/10/11/hibernate-validator-530-final-out/[the release notes] for more details.

== Questions and answers

* http://stackoverflow.com/questions/14699087/is-it-possible-to-update-only-a-subset-of-attributes-on-an-entity-using-spring-m/39972124#39972124[Is it possible to update only a subset of attributes on an entity using Spring MVC with JPA?]
* http://stackoverflow.com/questions/12011343/how-do-you-enable-batch-inserts-in-hibernate/29145834#29145834[How do you enable batch inserts in Hibernate?]
* http://stackoverflow.com/questions/40115158/how-to-make-hibernate-lock-annotation-work-for-oracle-db/40121788#40121788[How to make Hibernate `@Lock` annotation work for Oracle DB?]
* http://stackoverflow.com/questions/26564360/hibernate-connection-pool-provider-for-cloud-sql/26640960#26640960[Hibernate connection pool provider for Cloud SQL?]
* http://stackoverflow.com/questions/12928402/what-is-use-of-lazycollection/40132098#40132098[What is the use of the Hibernate `@LazyCollection` annotation?]
* http://stackoverflow.com/questions/30053647/specifying-a-primary-key-on-elementcollection/30069012#30069012[Specifying a primary key on ``@ElementCollection`]
* http://stackoverflow.com/questions/29947671/kill-ehcache-warn-messages/30086568#30086568[How to remove the Ehcache WARN messages when using Hibernate?]
* http://stackoverflow.com/questions/30088649/multiple-join-fetch-in-one-jpql-query/30093606#30093606[Multiple join fetch in one JPQL query]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043693&p=2490590[Hibernate query returns a list with null elements]
* https://forum.hibernate.org/viewtopic.php?f=9&t=1043698&p=2490601[How to eager fetch a Hibernate proxy?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043726&p=2490649[`PropertyValueException` in Hibernate 4 to 5 migration]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043727&p=2490661[Why was a `DELETE` statement generated after `saveAndFlush()`?]
