= Meet Sergey Chernolyas
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate OGM" ]
:awestruct-layout: blog-post
---

In this post, I'd like you to meet https://github.com/schernolyas[Sergey Chernolyas] who is one of our Hibernate OGM project contributors.

. *Hi, Sergey. You are one of the people who contributed to the Hibernate OGM project. Can you please introduce yourself?*
+
Hi, Vlad! My name is Sergey Chernolyas.
I am from Russia, and I am 38 years old.
I have been working with Java technologies since 2000.
During my career, I got four certificates on Java technologies from Oracle and got involved in many development and integration projects.
+
. *Can you tell us what project are you currently working on and if it uses Hibernate OGM?*
+
Now, I am working on a new module for Hibernate OGM, which aims to integrate the OrientDB NoSQL database.
With this module, OGM will support a total of 7 NoSQL databases.
Although at my current job, my work is not related to NoSQL solutions or Hibernate OGM,
I am interested in this topic, and that’s why I pushed myself to learn Hibernate OGM and exploring NoSQL databases.

. *Can you tell us a little about OrientDB?*
+
OrientDB is a graph-oriented and document-oriented database, and it is built using Java technologies.
Briefly, the main advantages of using OrientDB are:

.. It can operate in several modes: as an in-memory database, or through a network connection, or it can be store data in a local file.
.. It offers join-less entity associations.
.. It supports stored procedures that may be written in Java, JavaScript and any other language implementing the https://www.jcp.org/en/jsr/detail?id=223[JSR-223] specification (e.g. Groovy, JRuby, etc.).
.. It has good performance and is Big Data-oriented.
+
For more details about OrientDB, you can visit the http://orientdb.com/docs/last/[official documentation].
Recently, the OrientDB team released the 2.2 GA version, so it’s worth giving it a try.

. *What is the main benefit of using Hibernate OGM for accessing OrientDB over using their native API?*
+
The main benefit of using Hibernate OGM over the native API is the standard way for application development.
Also, Hibernate OGM hides many low-level operations for creating and managing database connections, or for executing queries.
+
While implementing the first version of the OrientDB Hibernate OGM module,
I was faced with some OrientDB issues that prevented me integrate all features that ought to be supported by any Hibernate OGM module.
Luckily, the OrientDB team was helpful and supportive, and I hope that by the time I finish this integration,
the OrientDB team had already fixed my previously reported issues.

*Thank you, Sergey for taking your time, and keep up the good work.*