= Hibernate Community Newsletter 24/2016
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM", "Newsletter" ]
:awestruct-layout: blog-post
---

Welcome to the Hibernate community newsletter in which we share blog posts, forum, and StackOverflow questions that are especially relevant to our users.

== Interviews

Don't miss our Hibernate developer interviews with
http://in.relation.to/2016/11/24/meet-christian-beykov/[Christian Beikov] and
http://in.relation.to/2016/11/30/meet-simon-martinelli/[Simon Martinelli].

If you like our interviews, then we have good news since we are going to interview
many developers that are a constant inspiration for our Java community.

== Articles

If you plan on using Apache Ignite, check out http://frommyworkshop.blogspot.ro/2016/11/apache-ignite-with-jpa-missing-element.html[this article]
about using Hibernate OGM when operating with a JPA-based Domain Model.

Database streaming is usually associated with large data set processing.
However, there is a price to pay for using streaming.
https://vladmihalcea.com/how-does-mysql-result-set-streaming-perform-vs-fetching-the-whole-jdbc-resultset-at-once/[This article]
explains why pagination might be a better option in many batch processing use cases.

Blaze Persistence offers many complementary features to standard JPA Criteria API.
In https://blazebit.com/blog/2016/getting-started-with-blaze-persistence-entity-views.html[this post],
Christian Beykov explains why you should use Entity Views when fetching data.

Flemming Harms wrote http://fharms.github.io/apache%20camel/2016/11/26/Take-JPA-to-another-level-in-Apache-Camel/[a very good article]
about integrating JPA with Apache Camel.

Thorben Janssen shows you http://www.thoughts-on-java.org/create-generate-table-model/[how you can generate the database schema from JPA entities].
While this is fine for generating an initial migration script, in reality, you need
incremental migration scripts that are managed by a tool like Flyway.
Check out https://www.sitepoint.com/schema-migration-hibernate-flywaydb/[this article] for more info.

Multitenancy is a very powerful concept, and JavaEE 8 might standardize this technique.
Meanwhile, you can use Hibernate ORM as explained in https://www.ricston.com/blog/multitenancy-jpa-spring-hibernate-part-1/[this article].

IntelijIDEA 2016.3 offers a very nice console for running JPQL queries and visualizing query results.
Check out https://www.jetbrains.com/help/idea/2016.3/working-with-the-hibernate-console.html[this article] for more info.

I wrote https://vladmihalcea.com/how-to-map-calculated-properties-with-hibernate-generated-annotation/[an article about mapping database-side calculated properties using the `@Generated` annotation].

== Time to upgrade

* http://in.relation.to/2016/11/24/hibernate-orm-525-final-release/[Hibernate ORM 5.2.5] and http://in.relation.to/2016/11/23/hibernate-orm-513-final-release/[Hibernate ORM 5.1.3]
* http://in.relation.to/2016/11/22/hibernate-validator-533-final-out/[Hibernate Validator 5.3.3]
* http://in.relation.to/2016/11/29/hibernate-search-5-6-0-Beta4-and-5-7-0-Beta1/[Hibernate Search 5.6.0.Beta4 and 5.7.0.Beta1]

== Questions and answers

* https://www.quora.com/Which-of-JPA-tool-do-you-use-and-why/answer/Vlad-Mihalcea-1[Which of JPA tool do you use and why?]
* https://www.quora.com/What-is-the-best-practice-for-Session-Management-with-Java-Hibernate/answer/Vlad-Mihalcea-1[What is the best practice for Session Management when using Hibernate?]
* http://stackoverflow.com/questions/40918597/join-table-on-case-insensitive-pk-and-fk-with-jpa/40919112#40919112[Join table on case insensitive PK and FK with JPA]
* http://stackoverflow.com/questions/29774200/group-concat-max-length-set-not-support-in-sql-query/29789072#29789072[How to set `group_concat_max_len` with MySQL and Hibernate?]
* http://stackoverflow.com/questions/40257688/hibernate-querytranslatorimpl-hql-ast-parsing-performance/40260896#40260896[Hibernate `QueryTranslatorImpl` HQL AST parsing performance]
* http://stackoverflow.com/questions/30981392/sequencegenerator-allocationsize-duplicate-key-error-issue/30981627#30981627[`@SequenceGenerator` allocationSize 'duplicate key error' issue]
* http://stackoverflow.com/questions/15974474/mapping-postgresql-json-column-to-hibernate-value-type/37946530#37946530[Mapping PostgreSQL JSON column to Hibernate value type]
* http://stackoverflow.com/questions/28363625/exclude-entity-field-at-update-with-jpa/28363801#28363801[Exclude entity field at update with JPA]
* http://stackoverflow.com/questions/10041938/how-to-choose-the-id-generation-strategy-when-using-hibernate/38391106#38391106[How to choose the id generation strategy when using Hibernate?]
* http://stackoverflow.com/questions/23983455/unsupportedexception-when-ever-i-call-saveobject-method-in-hibernate-while-sav/23983872#23983872[`UnsupportedException` whenever I call save(entity) method in Hibernate and SQL Server]
* http://stackoverflow.com/questions/25204019/how-to-use-the-pooled-lo-optimizer-with-hibernate-in-jboss/30183918#30183918[How to use the pooled-lo optimizer with Hibernate in JBoss?]
* http://stackoverflow.com/questions/40885133/can-i-use-jpa-to-filter-parent-by-number-of-children/40885436#40885436[Can I use JPA to filter parent by the number of children?]
* http://stackoverflow.com/questions/24359088/high-memory-usage-when-using-hibernate/24359242#24359242[High memory usage when using Hibernate]
* http://stackoverflow.com/questions/22729740/mapping-json-object-to-hibernate-entity/37946471#37946471[Mapping JSON object to Hibernate entity]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043816[How to write a reporting SQL query using JPA or Hibernate Criteria?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043814[WARN: SQL Error: 942, SQLState: 42000 when using Oracle with Hibernate]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043804[`NoSuchMethodError` - `org.hibernate.cfg.Environment`]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043810[Hibernate 5.2.2 with Oracle 12.1 throws ORA-17004 Struct null Value]
