= Hibernate Community Newsletter 5/2016
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM", "Newsletter" ]
:awestruct-layout: blog-post
---

Welcome to the Hibernate community newsletter in which we share blog posts, forum and StackOverflow questions that are especially relevant to our users.

== News

The http://in.relation.to/2016/02/16/hibernate-orm-new-user-guide[new User Guide] is online, and it's now the default Hibernate reference documentation.
We keep on improving it, and the next release will contain a chapter about Hibernate Spatial, a section about calling stored procedures, and an update to the Multi-tenancy chapter.

Sanne talked about Hibernate Search and Lucene at the http://www.flax.co.uk/blog/2016/02/24/london-lucenesolr-meetup-learning-rank-hibernate-search/[London Lucene/Solr Meetup].
I hope the recordings will be available soon.

== Articles

Bozhidar Bozhanov wrote a http://techblog.bozho.net/setting-up-distributed-infinispan-cache-with-hibernate-and-spring/[step-by-step] guide for integrating Hibernate, Spring, and Infinispan.

Dane Dennis, from JArchitect, http://crunchify.com/lessons-to-learn-fundamental-of-hibernate-core-implementation/[analyzed the Hibernate Core API] and concluded that
Hibernate is a "good example of open source projects to learn from".

While running some tests on all major relational database systems, I bumped into a very interesting issue relating to https://vladmihalcea.com/mysql-metadata-locking-and-database-transaction-ending/[MySQL metadata locking].
The bottom line is that you a transaction should always end as otherwise locks might be held, therefore impacting other concurrent transactions.

== Questions and answers

* https://forum.hibernate.org/viewtopic.php?f=1&t=1042956&p=2488749#p2488749[Is to practical to catch RollbackException?]
* http://stackoverflow.com/questions/35540901/member-of-in-jpql-not-translated-into-sql-exists-clause/35547779#35547779[Member of in JPQL not translated into SQL exists clause]
* http://stackoverflow.com/questions/35547513/sqlquery-list-returns-the-same-entries/35547652#35547652[SQLQuery.list() returns the same entries]
* http://stackoverflow.com/questions/35547129/hibernate-jpa-2-1-dependency/35547527#35547527[Hibernate JPA 2.1 dependency]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1042957&p=2488751#p2488751[Second-level cache doesn't store not found results]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1042963&p=2488753[Dynamic PersistenceUnitInfo.getJarFileUrls]
* https://stackoverflow.com/questions/35559854/how-do-i-force-a-hit-in-my-second-level-cache-in-my-junit-test/35581121#35581121[How do I force a hit in my second-level cache in my JUnit test?]
* http://stackoverflow.com/questions/35552109/how-to-setup-hibernate-gradle-plugin-for-bytecode-enhancement/35581674?stw=2#35581674[How to setup Hibernate Gradle plugin for bytecode enhancement?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1042977&p=2488803#p2488803[How to programmatically add an AttributeConverter in Hibernate 5.1]