= Hibernate Community Newsletter 23/2016
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM", "Newsletter" ]
:awestruct-layout: blog-post
---

Welcome to the Hibernate community newsletter in which we share blog posts, forum, and StackOverflow questions that are especially relevant to our users.

== Articles

Don't miss our Hibernate developer interviews with
http://in.relation.to/2016/11/18/meet-rafael-winterhalter-and-bytebuddy/[Rafael Winterhalter] and
http://in.relation.to/2016/11/15/meet-julien-dubois-and-jhipster/[Julien Dubois].
If you like our interviews, then we have good news since we are going to interview
many developers that are a constant inspiration for our Java community.

When streaming data from a Relational Database, it's very important to understand the underlying JDBC Driver capabilities.
Krešimir Nesek wrote https://knes1.github.io/blog/2015/2015-10-19-streaming-mysql-results-using-java8-streams-and-spring-data.html[a very good article]
about how you can take advantage of MySQL streaming when using Spring Data and Hibernate.

You should never concatenate strings when building dynamic queries, and this rule applies to JPQL queries as well.
Check out https://vladmihalcea.com/2016/11/08/a-beginners-guide-to-sql-injection-and-how-you-should-prevent-it/[this article] for what dangers awaits you if you don't follow this advice.

Nicky Bass Mølholm wrote https://moelholm.com/2016/11/09/spring-boot-controlling-timezones-with-hibernate/[a wonderful article] explaining the benefit of using the newly introduced
`hibernate.jdbc.time_zone` configuration property when using Spring Boot.

Benjamin Schmeling wrote a very detailed article about http://javatar81.blogspot.ro/2016/11/implementing-sortable-filterable.html[Implementing sortable, filterable, paginated and lazy Primefaces DataTable with Spring Data].

I wrote an article about https://vladmihalcea.com/2016/11/17/how-to-map-calculated-properties-with-jpa-and-hibernate-formula-annotation/[How to map calculated properties with JPA and Hibernate `@Formula` annotation].

Matti Tahvonen has created https://github.com/mstahv/spring-boot-spatial-example[Spring Boot example with Hibernate Spatial].
You can check it out on https://github.com/mstahv/spring-boot-spatial-example[GitHub].

== Time to upgrade

http://in.relation.to/2016/11/10/hibernate-validator-532-final-out/[Hibernate Validator 5.3.2] is out, as well as
http://in.relation.to/2016/11/08/hibernate-ogm-with-hotrod-support/[Hibernate OGM 5.1.0.Beta1 and 5.0.3.Final].

== Questions and answers

* https://www.quora.com/What-are-the-differences-between-Oracle-and-MySQL-for-Java-programming-Does-Hibernate-use-Oracle/answer/Vlad-Mihalcea-1[What are the differences between Oracle and MySQL for Java programming? Does Hibernate use Oracle?]
* https://www.quora.com/What-is-the-plan-you-suggest-to-master-Spring-and-Hibernate-frameworks-in-one-month/answer/Vlad-Mihalcea-1[What is the plan you suggest to master Spring and Hibernate frameworks in one month?]
* http://stackoverflow.com/questions/1115739/sql-injection-in-java-mysql-multiple-queries/40490013#40490013[SQL Injection in Java and MySQL when using multiple queries]
* http://stackoverflow.com/questions/23807143/hibernate-cannot-open-connection-exception/23807851#23807851[Hibernate throws `org.hibernate.exception.GenericJDBCException: Cannot open connection`]
* http://stackoverflow.com/questions/40592625/unable-to-access-transactionmanager-or-usertransaction-after-updating-to-hiberna/40635221#40635221[Unable to access `TransactionManager` or `UserTransaction` after updating to Hibernate 5]
* http://stackoverflow.com/questions/23925322/delete-child-from-parent-and-parent-from-child-automatically-with-jpa-annotation/23926548#23926548[Delete child from parent and parent from child automatically with JPA annotations]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043769&p=2490783[Cascade operation performance tuning for Hibernate 5]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043772&p=2490799[How to create a conditional database unique constraint?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043774&p=2490803[Migration to Hibernate 5.2.4: Problem with inheritance mapping]
* https://forum.hibernate.org/viewtopic.php?t=1043780[Running a MySQL native query which employs a user-defined function]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043783&p=2490843[How to use MySQL variables in Hibernate?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043785[How to handle `org.hibernate.StaleStateException`?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1043789&p=2490865[LIMIT keyword is not supported in HQL or JPQL]
* https://forum.hibernate.org/viewtopic.php?p=2490870[Best approach for multiple entities mapped on the same table]
