= Hibernate Community Newsletter 1/2016
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM", "Newsletter" ]
:awestruct-layout: blog-post
---

Happy New Year, everyone!

Starting this year, we are going to host a series of articles focused on the Hibernate community.
We are going to share blog posts, forum and StackOverflow questions, that are especially relevant to our users.

== Articles

Thorben Janssen, who regularly writes about JPA and Hibernate topics, has summarized the most typical logging configurations in a http://www.thoughts-on-java.org/hibernate-logging-guide/[Hibernate Logging Guide].

For our Portuguese readers, Rafael Ponte has written a very interesting http://blog.triadworks.com.br/jpa-por-que-voce-deveria-evitar-relacionamento-bidirecional[article about bidirectional relationships] and the caveats of not properly synchronizing both ends of a bidirectional association.

One topic, I always wanted to investigate in great details, is about the http://vladmihalcea.com/2015/12/22/hibernate-aggressive-connection-release/[aggressive connection release] behavior employed for JTA transactions.
For high-performance data access platforms, it's worth checking if the Java EE application server can operate successfully even without aggressive connection release.

== Questions and answers

* https://stackoverflow.com/questions/34480029/how-to-get-bound-parameters-out-of-a-hibernate-criteria-object/34481374#34481374[How to get bound parameters out of a Hibernate Criteria object?]
* http://stackoverflow.com/questions/34467121/hibernate-jpa-storing-constants-in-entity-class/34489177#34489177[Storing constants in entity class?]
* http://stackoverflow.com/questions/34383258/hibernate-many-to-many-remove-relation/34472122#34472122[What's the purpose of a remove operation in a many-to-many relationship?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1042849[How does the Persistence Context size affects flushing?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1042848[Why does Hibernate re-enable auto-commit after releasing the database connection?]
* http://stackoverflow.com/questions/34528450/multiple-hibernate-sequence-generators-for-one-entity-with-postgresql/34530385#34530385[Can there be multiple identifier generators in the same entity mapping?]