= MariaDB Dialects
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM" ]
:awestruct-layout: blog-post
---

Starting with Hibernate ORM 5.2.8, MariaDB gets its own Hibernate dialects.

== About MariaDB

https://en.wikipedia.org/wiki/MariaDB[MariaDB] is a MySQL fork that emerged in 2009 as a drop-in replacement for MySQL.
While for a while, MariaDB and MySQL offered similar functionalities, with time, both MariaDB and MySQL have diverged.

For this reason, we created the https://hibernate.atlassian.net/browse/HHH-11457[HHH-11457] issue, which is fixed in the Hibernate ORM 5.2.8.

== Dialect variants

For the moment, you cna use one of the following two options:

`MariaDBDialect`:: which is the base class for all MariaDB dialects and it works with any MariaDB version
`MariaDB53Dialect`:: which is intended to be used with MariaDB 5.3 or newer versions

In time, we will add new Dialects based on newer capabilities introduced by MariaDB.

== Connection properties

While to connect to a MySQL application, the connection properties look as follows:

- 'db.dialect' : 'org.hibernate.dialect.MySQL57InnoDBDialect',
- 'jdbc.driver': 'com.mysql.jdbc.Driver',
- 'jdbc.user'  : 'hibernate_orm_test',
- 'jdbc.pass'  : 'hibernate_orm_test',
- 'jdbc.url'   : 'jdbc:mysql://127.0.0.1/hibernate_orm_test'

For MariaDB, the connection properties look like this:


- 'db.dialect' : 'org.hibernate.dialect.MariaDB53Dialect',
- 'jdbc.driver': 'org.mariadb.jdbc.Driver',
- 'jdbc.user'  : 'hibernate_orm_test',
- 'jdbc.pass'  : 'hibernate_orm_test',
- 'jdbc.url'   : 'jdbc:mariadb://127.0.0.1/hibernate_orm_test'

While the URL includes the `mariadb` database identifier, the `MariaDB53Dialect` supports `Time` and `Timestamp` with microsecond precision, just like `MySQL57InnoDBDialect`.

== Conclusion

If you are using MariaDB, it's best to use the MariaDB-specific Dialects from now on since it's much easier to match the MariaDB version with its appropriate Hibernate Dialect.
