= Hibernate Community Newsletter 6/2017
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM" ]
:awestruct-layout: blog-post
---

Welcome to the Hibernate community newsletter in which we share blog posts, forum, and StackOverflow questions that are especially relevant to our users.

== Articles

Javin Paul wrote a very good article about http://javarevisited.blogspot.ro/2017/03/difference-between-first-and-second-level-cache-in-Hibernate.html[the difference between the first and the second-level cache in Hibernate].

Implementing the soft delete pattern with Hibernate is trivial. Check out https://vladmihalcea.com/2017/03/08/the-best-way-to-soft-delete-with-hibernate/[this article for more details].

Sri Vikram Sundar wrote a very detailed tutorial about http://javainfinite.com/spring/spring-mvc-hibernate-mysql-crud-operation/[integrating Spring MVC, MySQL, and Hibernate].

Stefan Pröll wrote two articles about using Hibernate Search and Spring Boot:

* https://blog.stefanproell.at/2017/03/12/using-hibernate-search-with-spring-boot/[Using Hibernate Search with Spring Boot]
* https://blog.stefanproell.at/2017/03/10/hibernate-search-and-spring-boot/[Building Bridges with Hibernate Search and Spring Boot]

Sunil Singh Bora wrote a https://www.boraji.com/hibernate-5-save-and-load-image-file-example[tutorial about saving and loading an Image using Hibernate 5].

Baeldung features http://www.baeldung.com/hibernate-immutable[an article about using the Hibernate-specific `@Immutable` annotation]
to mark entities that should never be modified, which allow Hibernate to enable some flush-time performance optimizations.

Arnold Gálovics wrote http://blog.arnoldgalovics.com/2017/03/14/using-projections-in-your-data-access-layer/[a very good article about using DTO projections for reading data when using JPA and Hibernate].

I wrote an article which explains https://vladmihalcea.com/2017/03/14/how-to-store-date-time-and-timestamps-in-utc-time-zone-with-jdbc-and-hibernate/[how to handle timezones when using Date/Time and Timestamps with JDBC and Hibernate].

For our Portuguese readers, Rafael Ponte wrote http://blog.triadworks.com.br/controle-transacional-programatico-em-sistemas-legados[a guide to controlling transactions programmatically in Legacy Systems using Java 8 Lambdas and the Template Pattern].
For non-Portuguese readers, you can use Google Translate since most Romance languages are easily translated into English.

Thorben Janssen wrote an article about http://www.thoughts-on-java.org/hibernate-tips-map-bidirectional-many-many-association/[mapping a bidirectional many-to-many association with JPA and Hibernate].

== Time to upgrade

Hibernate ORM http://in.relation.to/2017/03/14/hibernate-orm-515-final-release/[5.1.5] and http://in.relation.to/2017/03/16/hibernate-orm-529-final-release/[5.2.9] have been released.

== Questions and answers

* https://www.quora.com/What-is-the-difference-between-AnnotationConfiguration-and-Configuration-in-hibernate/answer/Vlad-Mihalcea-1[What is the difference between AnnotationConfiguration and Configuration in Hibernate?]
* http://stackoverflow.com/questions/42899647/batch-insert-with-hibernate-oracle-does-not-log-which-entity-cause-the-constrain/42900094#42900094[Batch insert with Hibernate and Oracle does not log which entity causes the ConstraintViolationException]
* http://stackoverflow.com/questions/27671776/how-to-make-a-one-to-many-bidirectional-relation-with-jpa-annotations-where-the/27677298#27677298[How to make a one-to-many bidirectional relation with JPA annotations, where the collection side owns it]
* http://stackoverflow.com/questions/41523914/bidirectional-onetomany-relation-with-jpa-annotations-doesnt-seem-to-work/41524034#41524034[Bidirectional @OneToMany relation with JPA annotations doesn't seem to work]
* http://stackoverflow.com/questions/27170089/transaction-management-in-hibernate-with-dao-design-pattern/27248135#27248135[Transaction Management in Hibernate with DAO Design Pattern]
* https://stackoverflow.com/questions/42897310/how-to-disable-optimistic-locking-in-spring-data-jpa/42898080#42898080[How to disable optimistic locking in Spring Data JPA]
* http://stackoverflow.com/questions/8753442/thinking-behind-decision-of-connection-pool-size/23537240#23537240[Thinking behind decision of database connection pool size]
* http://stackoverflow.com/questions/42703010/my-hibernate-testprogram-freezes-during-execution-why/42751890#42751890[My Hibernate test program freezes during execution]
* http://stackoverflow.com/questions/42781811/hibernate-refresh-in-many-to-one-relation/42785618#42785618[Hibernate refresh in many-to-one relation]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044119[HQL with NOT EXISTS and @ManyToMany association]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044123[How to escape keywords with JPA]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044078[How to delete an entity by the auto-generated ID in MySQL]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044103[How to set the begin and end index in Entity Graph Fetching]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044107[Hibernate Sequence is not generating id numbers in order]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044112[Passing parent entities field values to @Filter annotation]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044130[Migration from 4.3.9 to 5.1.5 (Foreign key problem)]





