= Hibernate Community Newsletter 14/2017
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM", "Newsletter" ]
:awestruct-layout: blog-post
---

Welcome to the Hibernate community newsletter in which we share blog posts, forum, and StackOverflow questions that are especially relevant to our users.

== Articles

In https://medium.com/calvin-codes/hibernate-entitymanager-merge-v-s-persist-1-d9e7b2f3f5a6[this article],
Arpit Jain writes about the differences between `persist` and `merge` in relation to JPA transaction boundaries.
For more details about the `persist` and `merge`
https://vladmihalcea.com/2014/07/30/a-beginners-guide-to-jpa-hibernate-entity-state-transitions/[entity state transitions],
check out https://vladmihalcea.com/2016/07/19/jpa-persist-and-merge/[this article] as well.

For functional programming aficionados, TehDev wrote a very interesting article about https://techdev.de/refactoring-towards-a-transaction-monad/[refactoring towards a transaction monad].

If you're using Payara Server, check out this article about http://blog.payara.fish/using-hibernate-5-on-payara-server[how you can integrate it with Hibernate 5].

Baeldung published an article about the differences between http://www.baeldung.com/hibernate-save-persist-update-merge-saveorupdate[`persist`, `merge`, `update`, as well as `saveOrUpdate`].

If you're using Grails, Michael Scharhag shows you http://www.mscharhag.com/grails/using-hibernate-filters-in-grails[how you can make use of Hibernate filters].

JPA 2.2 has been released, but Hibernate has been supporting https://vladmihalcea.com/2017/06/26/whats-new-in-jpa-2-2-java-8-date-and-time-types/[Java 1.8 Date and Time],
Hibernate-specific `@Repeatable` annotations and, since 5.1, Java 1.8 streams are supported as well.

While at it, check out this article about
https://vladmihalcea.com/2017/07/04/whats-new-in-jpa-2-2-stream-the-result-of-a-query-execution/[the caveats of using Streams when trying to limit the records fetched by a JDBC `ResultSet`].

If you're using MySQL, Thorben Janssen has written
https://www.thoughts-on-java.org/5-things-you-need-to-know-when-using-hibernate-with-mysql/[a list of tips to take into consideration when using Hibernate].
If you are interested in more details, then check out the following articles as well:

* https://vladmihalcea.com/2017/01/04/why-you-should-never-use-the-table-identifier-generator-with-jpa-and-hibernate/[Why you should never use the TABLE identifier generator with JPA and Hibernate]
* https://vladmihalcea.com/2017/01/24/why-should-not-use-the-auto-jpa-generationtype-with-mysql-and-hibernate/[Why should not use the AUTO JPA GenerationType with MySQL and Hibernate]
* https://vladmihalcea.com/2017/01/17/how-to-replace-the-table-identifier-generator-with-either-sequence-or-identity-in-a-portable-way/[How to replace the TABLE identifier generator with either SEQUENCE or IDENTITY in a portable way]

http://debezium.io/[Debezium] is an open-source project developed by Red Hat which allows you to capture transaction events from RDBMS like MySQL, PostgreSQL or NoSQL solutions such as MongoDB
and push them to https://kafka.apache.org/[Apache Kafka]. For more details, check out
https://vladmihalcea.com/2017/07/19/how-to-extract-change-data-events-from-mysql-to-kafka-using-debezium/[this tutorial] about using Debezium, MySQL and Kafka.

== Time to upgrade

http://in.relation.to/2017/07/18/hibernate-search-5-8-0-Beta4/[Hibernate Search 5.8.0.Beta4 is out with AWS integration].

http://in.relation.to/2017/07/11/hibernate-validator-600-cr3-out/[Hibernate Validator 6.0.0.CR3 is out with Bean Validation 2.0.0.CR3 support].

== Questions and answers

* https://www.quora.com/What-is-the-best-way-to-learn-JPA-Java-Persistence-API/answer/Vlad-Mihalcea-1[What is the best way to learn JPA (Java Persistence API)?]
* https://stackoverflow.com/questions/34383258/hibernate-many-to-many-remove-relation/34472122#34472122[Hibernate many-to-many remove relation]
* https://stackoverflow.com/questions/30288464/when-should-i-use-joincolumn-or-jointable/30292348#30292348[When should I use `@JoinColumn` or `@JoinTable`?]
* https://stackoverflow.com/questions/25097957/org-hibernate-exception-lockacquisitionexception-threads/25099277#25099277[Hibernate throws org.hibernate.exception.LockAcquisitionException]
* https://stackoverflow.com/questions/27697810/hibernate-disabled-insert-batching-when-using-an-identity-identifier-generator/27732138#27732138[Hibernate disabled insert batching when using an identity identifier generator]
* https://stackoverflow.com/questions/26416881/hibernate-mapping-exception-could-not-determine-type-for/26417545#26417545[Hibernate mapping exception - Could not determine type for]
* https://stackoverflow.com/questions/37747218/how-to-implement-a-custom-string-sequence-identifier-generator-with-hibernate/37749564#37749564[How to implement a custom String sequence identifier generator with Hibernate]
* https://stackoverflow.com/questions/11822302/how-to-join-two-unrelated-entities-using-hibernate/36479380#36479380[How to join two unrelated entities using Hibernate]
* https://stackoverflow.com/questions/2895460/hibernate-versioning-parent-entity/39224864#39224864[Hibernate versioning parent entity]
* https://stackoverflow.com/questions/31293822/how-to-get-the-hibernate-sessionfactory-from-org-springframework-orm-hibernate4/31294417#31294417[How to get the Hibernate SessionFactory from org.springframework.orm.hibernate4.LocalSessionFactoryBean?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044591[SQL to HQL conversion for Complex Query]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044595[How to install a global Interceptor with Hibernate 5]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044597[Best way to handle time zones with Hibernate]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044516[Query nested objects using HQL or Criteria Builder]
