= Hibernate Community Newsletter 5/2017
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM" ]
:awestruct-layout: blog-post
---

Welcome to the Hibernate community newsletter in which we share blog posts, forum, and StackOverflow questions that are especially relevant to our users.

== Interviews

Don't miss our Hibernate developer interviews with http://in.relation.to/2017/02/27/meet-marco-pivetta/[Marco Pivetta] and http://in.relation.to/2017/03/01/meet-kevin-peters/[Kevin Peters].

If you want to share your story about Hibernate, let us know, and we can share it with our huge community of passionate developers.

== Books

Javin Paul, a long-time Java blogger, gives http://www.java67.com/2017/02/2-best-books-to-learn-hibernate-for-Java-Developers.html[a review of the two best Hibernate books for Java developers].

Thorben Janssen is now writing a http://www.thoughts-on-java.org/book-report-week6/[Hibernate Tips book], and you can get a free copy if you want to review it.

== Articles

Nowadays, many RDBMS support JSON column types and Hibernate makes it very easy to use JSON object as entity attributes as
http://milesgreatwood.com/2017/02/07/hibernate-getting-json-to-java-java-to-hibernate/[this article] demonstrates it.

Encrypting and decrypting column values is easy-peasy when using Hibernate.
Check out https://vladmihalcea.com/2017/02/24/how-do-encrypt-and-decrypt-data-with-hibernate/[this article] for a detailed tutorial on this topic.

Arnold Galavics wrote http://blog.arnoldgalovics.com/2017/02/27/lazyinitializationexception-demystified/[a very good article] how the `LazyInitializationException` works in Hibernate.

Craig Andrews is building a https://github.com/candrews/hibernate-springcache[Hibernate SpringCache] prototype which acts like a Hibernate second-level cache implementation on top of Spring Cache.
The idea is very interesting, and we are looking for your feedback on this topic.

Our colleague, Chris Cranford have a talk about https://www.devnexus.com/s/speakers/17242[Hibernate Performance at DevNexus], and https://docs.google.com/presentation/d/1-RsIFGuegF5k7neKwvidApp2N8mgb-h31iBXeQJTrMk/pub?start=false&loop=false&delayms=3000&slide=id.g1b24cd57fa_0_606[here are the slides].

If you're using MySQL, then you should know that http://in.relation.to/2017/02/20/mysql-dialect-refactoring/[we refactored the MySQL Dialects] so that it's much easier for you to match a Hibernate Dialect with a given MySQL server version.

Concurrency Control is a very interesting topic, and if you every wondered how MVCC (Multi-Version Concurrency Control) works, then https://vladmihalcea.com/2017/03/01/how-does-mvcc-multi-version-concurrency-control-work/[this article] is going to unravel how INERT, UPDATE, and DELETE statements work in MVCC-based database engines.

Thorben Janssen wrote two articles about Hibernate Search, one about http://www.thoughts-on-java.org/implement-complex-full-text-search-hibernate-search/[custom Analyzers]
and another one about http://www.thoughts-on-java.org/use-facets-categorize-fulltextquery-results/[Facets].

== Time to upgrade

* http://in.relation.to/2017/02/22/hibernate-search-5-7-0-Final/[Hibernate Search 5.7.0] has been released!
* http://in.relation.to/2017/03/02/hibernate-ogm-5-1-Final-released/[Hibernate OGM 5.1.0] is out!
* For our Eclipse Users, you can now use http://in.relation.to/2017/03/03/EclipseToolsForHibernateSearchRelease20/[the second version of the Hibernate Search plugin]

== Questions and answers

* https://www.quora.com/How-do-you-track-modified-changes-in-the-database/answer/Vlad-Mihalcea-1[How do you track modified changes in the database?]
* http://stackoverflow.com/questions/22592366/hibernate-date-encryption-to-prevent-direct-access/42442012#42442012[Hibernate - date encryption to prevent direct access]
* http://stackoverflow.com/questions/28000223/hibernate-error-on-update-could-not-execute-statement-the-right-syntax-to-use/28005009#28005009[Hibernate error on update : could not execute statement, the right syntax to use near 'index=1']
* http://stackoverflow.com/questions/5268466/how-does-hibernate-detect-dirty-state-of-an-entity-object/25425009#25425009[How does Hibernate detect the dirty state of an entity object?]
* http://stackoverflow.com/questions/25125210/hibernate-persistentset-remove-operation-not-working/25131860#25131860[Hibernate PersistentSet remove() operation not working]
* http://stackoverflow.com/questions/42416715/taking-long-time-to-flush-intermediately-using-hibernate/42435674#42435674[Taking a long time to flush intermediately using Hibernate]
* http://stackoverflow.com/questions/42437840/hibernate-columntransformer-and-postgres-encrypt-a-column/42437963#42437963[How to encrypt a column in Postgres using Hibernate @ColumnTransformer]
* http://stackoverflow.com/questions/5179676/how-do-i-implement-mvcc/42531381#42531381[How do I implement MVCC?]
* http://stackoverflow.com/questions/28043558/what-is-discriminator-value-in-hibernate-mapping-file/28044425#28044425[What is the meaning of discriminator-value in Hibernate mapping file?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044044[How to delete multiple entries with JPA and Hibernate?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044047[Does it make sense to have a Query Cache per Session?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044059[What is the best way for a project to work with multiple different DBs?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044064[How to select directly from a @ManyToMany JPA link table?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044066[Hibernate 5 & Spring Boot multitenancy (schema per user)]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044073[Hibernate with Oracle - getInt not implemented for class oracle.jdbc.driver.T4CRowid]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044040[How to persist an entity with _manually_ assigned id?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044048[Hibernate allocationSize incrementBy causes constraint violation exceptions]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044042[Spring REST, MQ, and Hibernate multitenancy]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044043[Hibernate + JPA: usability issue with counts in Criteria API]
