= Hibernate Community Newsletter 7/2017
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM" ]
:awestruct-layout: blog-post
---

Welcome to the Hibernate community newsletter in which we share blog posts, forum, and StackOverflow questions that are especially relevant to our users.

== Upcoming events

Java Gruppen Danemark is hosting a https://www.javagruppen.dk/55-arrangementer/arrangementer-2017/366-javagruppe-high-performance-hibernate-ga-hjem-mode-hos-miracle-i-aarhus[High-Performance Hibernate webinar].
If you want to participate, then you should https://www.eventbrite.com/e/javagruppe-high-performance-hibernate-ga-hjem-mde-hos-miracle-i-aarhus-tickets-33082229840[register on Eventbrite].

http://in.relation.to/2017/04/03/HibernateOGMatDevoxxUK2017/[Hibernate OGM will be at Devoxx UK 2017]. If you want to learn more about Hibernate OGM and Infinispan, then you should definitely come to see Sanne's presentation.

== Articles

A very handy feature when working with JDBC batch updates is to find out which statement triggered a batch failure.
Read https://vladmihalcea.com/2017/03/21/how-to-find-which-statement-failed-in-a-jdbc-batch-update/[this article] for more info on this topic.

You can use Hibernate with CockroachDB. Check out https://www.cockroachlabs.com/docs/build-a-java-app-with-cockroachdb-hibernate.html[this tutorial] to see how easily you can integrate them.

Mapping the `@OneToMany` association is not as easy as you might think.
Check out this article which shows you https://vladmihalcea.com/2017/03/29/the-best-way-to-map-a-onetomany-association-with-jpa-and-hibernate/[the best way to map a `@OneToMany` relationship].

Alon Segal shows you how to implement https://dzone.com/articles/spring-boot-hibernate-multitenancy-implementation[Multitenancy with Spring and Hibernate].
Multitenancy is very handy when you need to support multiple customers on a single platform so that each customer is limited to its own tenant.

I read http://www.codesod.com/2017/03/dealing-with-javas-localdatetime-in-jpa.html[this article] which describes a way to provide
a JPA `AttributeConverter` to support Java 1.8 Data/Time types. However, this is not needed since Hibernate has been supported them for quite a while now.

For our Czech readers, Roman Pichlík wrote http://www.dagblog.cz/2017/03/papirova-skalovatelnost-bcrypt-ladeni.html[a very good article] about all sorts of application performance issues,
and the Open-Session in View is mentioned as well.

For our French readers, eXo platform has written https://www.exoplatform.com/blog/fr/2017/03/28/developper-avec-jpa-et-exo-platform[an article] that shows you how to integrate eXO with JPA and Hibernate.

== Time to upgrade

Hibernate Validator http://in.relation.to/2017/03/23/hibernate-validator-541-final-out/[5.4.1] and
http://in.relation.to/2017/03/30/hibernate-validator-600-alpha2-out/[6.0.0 Alpha 2] are out.

http://grailsblog.objectcomputing.com/posts/2017/03/27/gorm-6.1-released.html[GORM 6.1] has been released with support for Hibernate 5.2.

== Questions and answers

* https://www.quora.com/Is-connection-pooling-a-best-practice-with-Hibernate/answer/Vlad-Mihalcea-1[Is connection pooling a best practice with Hibernate?]
* http://stackoverflow.com/questions/42953410/hibernate-change-query-dynamically/42953640#42953640[Hibernate and database functions with packages]
* http://stackoverflow.com/questions/26328187/is-it-possible-to-limit-the-size-of-a-onetomany-collection-with-hibernate-or-jp/26329733#26329733[Is it possible to limit the size of a `@OneToMany` collection with Hibernate or JPA Annotations?]
* http://stackoverflow.com/questions/40437848/copy-data-between-different-databases-both-are-jdbc-supported/42960998#42960998[Copy data between different databases (both are supporting JDBC)]
* http://stackoverflow.com/questions/24758888/hibernate-inheritance-cascade-on-delete/24759849#24759849[Cascade on delete for Hibernate Inheritance model]
* http://stackoverflow.com/questions/43119982/hibernate-statistical-logging/43135269#43135269[Hibernate Statistics Logging]
* http://stackoverflow.com/questions/4713563/what-are-the-main-problems-when-using-hibernate-lazy-loading[What are the main problems when using Hibernate lazy loading?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044158[Hibernate fails because InetAddress.getLocalHost() fails]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044154[Why @DynamicInsert, @DynamicUpdate are disabled by default]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044169[Database Flyweight pattern with JPA and Hibernate]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044157[UnsupportedOperationException with SAP HANA and Hibernate]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044116[How to prevent updates for unchanged entities]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044140[Mapping single parent column to multiple child columns]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044142[Hibernate Statistics via JMX is missing in 5.2]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044155[Second-level Cache with `DetachedCriteria`]
