= Hibernate Community Newsletter 8/2017
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM", "Newsletter" ]
:awestruct-layout: blog-post
---

Welcome to the Hibernate community newsletter in which we share blog posts, forum, and StackOverflow questions that are especially relevant to our users.

== Articles

The Hibernate `ResultTransformer` is extremely useful to customize the way you fetch data from the database.
Check out https://vladmihalcea.com/2017/04/03/why-you-should-use-the-hibernate-resulttransformer-to-customize-result-set-mappings/[this article]
to learn more about this topic.

JPA and Hibernate use the first-level cache as a staging buffer for every read/write operation,
and understanding its inner workings is very important if you want to use JPA effectively.
For more details, you should definitely read http://www.kubrynski.com/2017/04/understanding-jpa-l1-caching.html[this article].

Marco Behler offers https://www.marcobehler.com/series/2-practical-hibernate-beginners[6 very practical video tutorials] for Hibernate beginners.

Dealing with difficult software problems is easier than you might think.
Check out https://vladmihalcea.com/2017/04/05/2-best-tools-that-can-help-you-solve-any-software-development-problem/[this article]
for more details on how you can solve any software issue with the help of our wonderful software community.

If you wonder why you should choose Hibernate over plain JDBC,
http://habiletechnologies.com/blog/reasons-to-choose-hibernate-over-jdbc/[this article] gives you 15 reasons why Hibernate is worth using.

This http://www.thoughts-on-java.org/hibernate-tips-map-bidirectional-many-one-association/[very short article] offers
a quick introduction to mapping a bidirectional one-to-many association.
If you want to know what is the best way to map a one-to-many database relationship,
then you should definitely read https://vladmihalcea.com/2017/03/29/the-best-way-to-map-a-onetomany-association-with-jpa-and-hibernate/[this article] as well.

Database concurrency control is a very complex topic. PostgreSQL advisory locks are a very useful concurrency control API which you can use
to implement multi-node coordination mechanisms.
Check out https://vladmihalcea.com/2017/04/12/how-do-postgresql-advisory-locks-work/[this article] for more details on this topic.

== Time to upgrade

http://in.relation.to/2017/04/14/hibernate-orm-5210-final-release/[Hibernate ORM 5.2.10] has been released,
as well as http://in.relation.to/2017/04/15/HibernateSearchNowSpeakingEs5/[Hibernate Search 5.8.0.Beta1] which is now compatible with ElasticSearch 5.

== Questions and answers

* https://www.quora.com/Which-is-the-best-book-to-learn-Hibernate-framework/answer/Krishna-Srinivasan-6[Which is the best book to learn the Hibernate framework?]
* http://stackoverflow.com/questions/43202801/entity-not-dound-exception-or-null-value/43203515#43203515[JPA `@ManyToOne` - EntityNotFoundException or null value?]
* http://stackoverflow.com/questions/29551983/how-to-join-tables-on-non-primary-key-using-jpa-and-hibernate/29643115#29643115[How to join tables on non Primary Key using JPA and Hibernate]
* http://stackoverflow.com/questions/24724152/jpa-clear-collection-and-add-new-items/25251602#25251602[JPA clear collection and add new items]
* http://stackoverflow.com/questions/3303104/logging-jdbc-hibernate-jpa-transaction-isolation-levels/27633043#27633043[Logging JDBC/Hibernate/JPA transaction isolation levels]
* http://stackoverflow.com/questions/43312696/mapping-entities-with-composite-foreign-keys-in-jpa/43337256#43337256[Mapping entities with composite foreign keys in JPA]
* http://stackoverflow.com/questions/27202235/how-hibernate-keep-track-detached-object-to-persistent-object-in-different-sessi/27202580#27202580[How does Hibernate keep track of Detached and Persistent object from different Sessions]
* http://stackoverflow.com/questions/25280815/how-to-create-relationships-between-objects-in-spring-jdbc/25281889#25281889[How to create relationships between objects in Spring JDBC?]
* http://stackoverflow.com/questions/23917771/how-to-update-the-first-n-rows-with-jpa-and-hibernate/23921399#23921399[How to update the first N rows with JPA and Hibernate]
* http://stackoverflow.com/questions/28865222/mapping-java-boolean-to-oracle-number-column-with-jpa-and-hibernate/28866011#28866011[Mapping Java boolean to Oracle Number column with JPA and Hibernate]
* http://stackoverflow.com/questions/30875863/can-hibernate-schema-generation-be-used-to-generate-ddl-without-database-connect/30884476#30884476[Can Hibernate Schema generation be used to generate DDL without database connection]
* http://stackoverflow.com/questions/17780394/hibernate-identity-vs-sequence/27461625#27461625[Hibernate IDENTITY vs. SEQUENCE]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044174[HHH000104: firstResult/maxResults specified..warnings]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044177[How to save the child entity in unidirectional one-to-many]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044179[Fetching Hibernate entities take too long]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044181[Choosing the right strategy for JPA Inheritance Mapping]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044183[How to utilize the metadata model in the mappedBy attribute?]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044203[Bidirectional @OneToMany - infinitely nested JSON objects]
* https://forum.hibernate.org/viewtopic.php?f=1&t=1044205[Retyring after StaleObjectStateException in a batch process]