= Hibernate Community Newsletter 02/2018
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM", "Newsletter" ]
:awestruct-layout: blog-post
---

Welcome to the Hibernate community newsletter in which we share blog posts, forum, and StackOverflow questions that are especially relevant to our users.

== Forum

The Hibernate forum has gone through a massive transformation and is https://discourse.hibernate.org/[powered by Discourse now].

The [old forum was locked](http://forum.hibernate.org/) for good, and you can only use it in read-only mode.

From now on, we are waiting for you on the new https://discourse.hibernate.org/[Discourse-based forum].

== Workshop

If you haven't visited the beautiful city of Budapest, now you have one more reason.

In May, during CraftConf (probably one of the best conferences in the world),
I'm giving my https://ti.to/bpconferences/craft-conference-2018#tito-ticket-f7zfk7umtb4[High-Performance Java Persistence workshop].

If you want to learn how to run your data access layer at warp speed, then you should definitely attend my workshop.

== Articles

We are proud that Hibernate was picked as the https://sourceforge.net/blog/january-2018-staff-pick-project-month-hibernate/[Project of the Month by SourceForge].

Jörn Hameister wrote a very good article about doing http://www.hameister.org/SpringBootUsingIdsForBulkImports.html[Bulk and Batch Inserts using Spring Boot].

While on the topic, I also wrote an article about building
https://vladmihalcea.com/jpa-criteria-api-bulk-update-delete/[Bulk Update and Delete statements dynamically using JPA 2.1 Criteria].

For our Portuguese readers, I found this article about why we need database transactions -
http://db4beginners.com/blog/db-relacional-transacao/[Porque você precisa conhecer transações?].

If you haven't heard of it, you should know that I've been started the https://github.com/vladmihalcea/hibernate-types[hibernate-types] open-source project
so that you can map JSON, ARRAY, PostgreSQL Enum Types using Hibernate.

Lately, I've added support for https://vladmihalcea.com/hibernate-hsqldb-array-type/[VARCHAR-backed `String[]` arrays when using HSQLDB].

If you want to learn about the difference between Hibernate and EclipseLink, then check out
https://www.thoughts-on-java.org/difference-jpa-hibernate-eclipselink/[this article].

== Time to upgrade

Hibernate ORM has released two new versions:

- http://in.relation.to/2018/01/10/hibernate-orm-5111-final-release/[Hibernate ORM 5.1.11],
- http://in.relation.to/2018/01/18/hibernate-orm-530-beta1-release/[Hibernate 5.3 Beta1] with support for JPA 2.2].

== Questions and answers

- https://www.quora.com/What-are-some-best-tutorials-to-learn-batch-file-programming/answer/Vlad-Mihalcea-1[What are some best tutorials to learn batch file programming?]
- https://discourse.hibernate.org/t/set-primary-key-and-foreign-key-on-a-single-column-in-hibernate-mapping-having-type-string/108[Set Primary key and Foreign key on a single column in Hibernate mapping having type String]
- https://discourse.hibernate.org/t/mappingexception-repeated-column-in-mapping-for-collection-manytomany/88[MappingException: Repeated column in mapping for collection ManyToMany]
- https://discourse.hibernate.org/t/cannot-persist-a-new-record-due-to-identity-insert-is-set-to-off/95[Cannot persist a new record due to IDENTITY_INSERT is set to OFF]
- https://discourse.hibernate.org/t/using-dynamicupdate-and-optimisticlocktype-dirty-for-optimistic-locks/[Using `@DynamicUpdate` and `@OptimisticLockType.DIRTY` for Optimistic Locks]
- https://discourse.hibernate.org/t/does-hibernate-persistentset-maintain-order-when-using-orderby/[Does Hibernate PersistentSet maintain order when using @OrderBy]
- https://discourse.hibernate.org/t/hibernate-query-cache-and-aggregate-queries/[Hibernate Query Cache and Aggregate Queries]
- https://discourse.hibernate.org/t/pagination-with-hibernate-set-long-as-offset/[Pagination with Hibernate. Set Long as ‘offset’]
- https://discourse.hibernate.org/t/hi-how-to-query-embedded-object-in-hibernate/[How to query embedded object in Hibernate?]
- https://discourse.hibernate.org/t/hibernate-memory-management/32[Hibernate memory management]
- https://stackoverflow.com/questions/17600961/jpa-batch-bulk-update-what-is-the-better-approach/48211427#48211427[JPA - Batch/Bulk Update - What is the better approach?]
- https://stackoverflow.com/questions/3572626/48147962#48147962[Calling stored procedure from Java / JPA]
- https://stackoverflow.com/questions/30918154/mysql-or-hibernate-caching-issue-receiving-old-data/30934186#30934186[MySQL or Hibernate caching issue receiving old data]
- https://stackoverflow.com/questions/24806909/pessimisticlockscope-normal-and-locking-relationships/24878652#24878652[PessimisticLockScope.NORMAL and locking “relationships”]
- https://stackoverflow.com/questions/23846618/bulk-delete-in-jpa-2-1-using-the-criteria-api/48165489#48165489[Bulk delete in JPA 2.1 using the criteria API]




