= Hibernate Community Newsletter 15/2018
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM", "Newsletter" ]
:awestruct-layout: blog-post
---

Welcome to the Hibernate community newsletter in which we share blog posts, forum, and StackOverflow questions that are
especially relevant to our users.

== Interviews

Don't miss our Hibernate developer interview with http://in.relation.to/2018/08/07/meet-jan-willem-gmelig-meyling/[Jan-Willem Gmelig Meyling].

If you want to share your story about Hibernate, let us know, and we can share it with our huge community of passionate developers.

== Articles

Ikhiloya Imokhai explains https://medium.com/skillhive/how-to-retrieve-a-parent-field-from-a-child-entity-in-a-one-to-many-bidirectional-jpa-relationship-4b3cd707bfb7[how to implement a REST service to fetch entities that form a bidirectional JPA relationship when using Spring Boot].

Since cloud computing becomes more and more popular, the need for database multitenancy becomes even more obvious.
https://vladmihalcea.com/database-multitenancy/[This article] is a short introduction to database multitenancy, and explains how you can achieve it at catalog, schema or table level.

Hibernate Validator is the reference implementation of the Bean Validation specification, and it allows you to decouple the domain model validation logic from the business one.
For more details, check out https://howtodoinjava.com/hibernate/hibernate-validator-java-bean-validation/[this introductory tutorial].

For our Czech readers,
https://www.zdrojak.cz/clanky/java-na-webovem-serveru-prace-s-databazi-ii/[this tutorial] shows you how to write data access code using
both the Hibernate and the Spring JdbcTemplate.

In http://www.kodnito.com/posts/microprofile-rest-api-with-mongodb-hibernate-ogm-and-thorntail/[this article],
Hayri Cicek explains how to develop a MicroProfile REST API with MongoDB, Hibernate OGM and Thorntail (previously known as WildFly Swarm).

When using JPA inheritance, you might want to restrict a given polymorphic query to fetch only a subset of subclasses.
https://vladmihalcea.com/query-entity-type-jpa-criteria-api/[This article] explains how you can achieve this goal when using the JPA Criteria API.

If you want to retrieve the underlying database connection when using Hibernate,
https://www.thoughts-on-java.org/hibernate-tips-get-the-sql-connection-used-by-your-hibernate-session/[this article] explains how to do so.

== Time to upgrade

There were several Hibernate project releases since the last newsletter:

- http://in.relation.to/2018/07/24/hibernate-orm-533-final-out/[Hibernate ORM 5.3.3] and http://in.relation.to/2018/08/02/hibernate-orm-534-final-out/[Hibernate ORM 5.3.4]
- http://in.relation.to/2018/07/25/hibernate-search-5-10-3-Final/[Hibernate Search 5.10.3]

== Questions and answers

- https://discourse.hibernate.org/t/get-detatchedcriteria-for-specific-class/1151/2[Filter entities by a specific subclass type using Criteria]
- https://discourse.hibernate.org/t/how-to-fetch-one-side-of-a-many-to-many-association-while-on-the-other-side-all-records-match-a-given-filtering-criteria/1095[How to fetch one side of a many-to-many association while on the other side all records match a given filtering criteria]
- https://stackoverflow.com/questions/31725820/hql-returning-timestamp-for-given-timezone/31741171#31741171[How to use the MySQL CONVERT_TZ function in a JPQL or HQL query]
- https://discourse.hibernate.org/t/limit-clause-is-not-working-in-jpa-named-queries/1112[LIMIT clause is not working in JPA Named Queries ]
- https://discourse.hibernate.org/t/how-i-can-create-select-from-select-query/1156[How can I create SELECT FROM SELECT query with JPA and Hibernate? ]
- https://discourse.hibernate.org/t/how-to-fetch-a-transient-property-from-the-database-using-jpa-and-hibernate/1160[How to fetch a @Transient property from the database using JPA and Hibernate?]
- https://discourse.hibernate.org/t/how-to-get-the-default-transaction-isolation-level-using-hibernate-api/1165[How to get the default transaction isolation level using Hibernate API]
- https://discourse.hibernate.org/t/criteriaimpl-and-stream/1144[How to call stream() on the Hibernate CriteriaImpl object]
- https://discourse.hibernate.org/t/sqlquery-and-org-hibernate-query-are-deprecated-what-to-use-instead/1179[SQLQuery and org.hibernate.Query are deprecated. What to use instead?]
- https://stackoverflow.com/questions/25893476/can-you-have-multiple-transactions-within-one-hibernate-session/26026394#26026394[Can you have multiple transactions within one Hibernate Session?]
- https://stackoverflow.com/questions/34371128/jpa-2-0how-to-fetch-whole-of-entity-graph/34374600#34374600[How to fetch a whole entity graph using JPA]
- https://stackoverflow.com/questions/11938253/whats-the-difference-between-joincolumn-and-mappedby-when-using-a-jpa-onetoma/51055434#51055434[What's the difference between `@JoinColumn` and `mappedBy` when using a JPA `@OneToMany` association]
- https://stackoverflow.com/questions/23708905/application-cache-v-s-hibernate-second-level-cache-which-to-use/23710646#23710646[Application cache v.s. Hibernate second-level cache, which one to use?]
- https://stackoverflow.com/questions/25047226/jpa-generationtype-auto-not-considering-column-with-auto-increment/25052275#25052275[JPA GenerationType.AUTO not considering column with auto increment]
- https://stackoverflow.com/questions/25746509/hibernate-nativequery-transaction/25830441#25830441[How to run native SQL queries in the same Hibernate transaction?]