= Hibernate Community Newsletter 05/2018
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM", "Newsletter" ]
:awestruct-layout: blog-post
---

Welcome to the Hibernate community newsletter in which we share blog posts, forum, and StackOverflow questions that are
especially relevant to our users.

== Articles

Bruno Borges wrote an article about
https://medium.com/@brunoborges/setting-up-database-servers-for-development-on-mac-os-x-using-docker-b7f2fad056f3[setting up database servers for development using Docker].

Chang Chao wrote an article about the
https://www.changchao.me/?p=782[Open Session In View Spring Boot implementation causing cache-related problems].

For our Chinese readers, Yang Chuang wrote an article about using the
https://ifrenzyc.github.io/2017/11/16/mysql-streaming/[MySQL streaming] feature with JDBC.

If you want to know how to map a JPA entity to a View or SQL query using Hibernate,
you should read https://vladmihalcea.com/map-jpa-entity-to-view-or-sql-query-with-hibernate/[this article].

When using Oracle, you might want to get the actual execution plan for a given Hibernate JPQL, Criteria API or even
native SQL query.
https://vladmihalcea.com/execution-plan-oracle-hibernate-query-hints/[This article] explains how you can get the actual execution plan
when using Oracle.

The `hibernate-types` project adds support for custom Hibernate Types like JSON, ARRAY or PostgreSQL Enum.
The version 2.1.1 adds support for customizing the underlying Jackson `ObjectMapper`.
For more details, you should read
https://vladmihalcea.com/hibernate-types-customize-jackson-objectmapper/[this article].

Thorben Janssen wrote an article about the difference between
https://www.thoughts-on-java.org/composition-vs-inheritance-jpa-hibernate/[Composition and Inheritance]
when using JPA entities.


== Time to upgrade

There were many Hibernate project releases since the last newsletter:

- http://in.relation.to/2018/03/08/hibernate-orm-5215-final-release/[Hibernate ORM 5.2.15] and http://in.relation.to/2018/02/27/hibernate-orm-5214-final-release/[Hibernate ORM 5.2.14]
- http://in.relation.to/2018/02/23/hibernate-search-5-10-0-Beta1/[Hibernate Search 5.10.0.Beta1]
- http://in.relation.to/2018/02/20/hibernate-ogm-5-3-Final-released/[Hibernate OGM 5.3.0.Final]
- http://in.relation.to/2018/03/08/hibernate-validator-608-final-out/[Hibernate Validator 6.0.8.Final]

== Questions and answers

- https://stackoverflow.com/questions/40115158/how-to-make-hibernate-lock-annotation-work-for-oracle-db/40121788#40121788[How to make Hibernate `@Lock` annotation work for Oracle DB?]
- https://stackoverflow.com/questions/27968877/how-to-avoid-two-different-threads-read-the-same-rows-from-db-hibernate-and-ora/27974036#27974036[How to avoid two different threads read the same rows from DB with Hibernate and Oracle]
- https://stackoverflow.com/questions/30288464/when-should-i-use-joincolumn-or-jointable/30292348#30292348[When Should I Use `@JoinColumn` or `@JoinTable`?]
- https://stackoverflow.com/questions/11822302/how-to-join-two-unrelated-entities-using-jpa-and-hibernate/36479380#36479380[How to join two unrelated entities using JPA and Hibernate]
- https://discourse.hibernate.org/t/query-specified-join-fetching-but-the-owner-of-the-fetched-association-was-not-present-in-the-select-list/258[Query specified join fetching, but the owner of the fetched association was not present in the select list]
- https://discourse.hibernate.org/t/hibernate-referencedcolumnname/272[Hibernate throws `org.hibernate.TypeMismatchException`: Provided id of the wrong type for class. Expected: class java.lang.Integer, got class java.lang.Long]
- https://discourse.hibernate.org/t/do-i-still-need-to-implement-serializable-when-using-hibernate/287[Do I still need to implement `Serializable` when using Hibernate?]
- https://discourse.hibernate.org/t/entityexistsexception-when-reset-a-arraylist-and-refill-before-merge/301/2[EntityExistsException when resetting an `ArrayList` and refilling it before merge]