= Hibernate Community Newsletter 18/2018
Vlad Mihalcea
:awestruct-tags: [ "Discussions", "Hibernate ORM", "Newsletter" ]
:awestruct-layout: blog-post
---

Welcome to the Hibernate community newsletter in which we share blog posts, forum, and StackOverflow questions that are especially relevant to our users.

== Articles

Starting with JPA and Hibernate is fairly easy. However, getting the best out of the underlying database system,
JDBC driver or JPA implementation is what many developers find challenging.
https://vladmihalcea.com/hibernate-performance-tuning-tips/[These Hibernate performance tuning tips] are going to
help you speed uo your data access layer, as well as getting a better understanding of how Hibernate works behind the scenes.

Eugen Paraschiv wrote a very good article which teaches you
https://stackify.com/java-performance/[how to improve the performance of a Java application].

Marko Bekhta wrote an article about
https://that-java-guy.blogspot.com/2018/09/bean-validation-validation-based-on.html[validating multiple properties with Bean Validation].

When using JPA and Hibernate, it's not uncommon to want to clone or duplicate a given entity.
https://vladmihalcea.com/clone-duplicate-entity-jpa-hibernate/[This article] shows you how to use the copy constructor to clone an entity so that you control the associations being cloned.

If you want to know how to leverage the full-text search capabilities of SAP HANA using Hibernate, check out
https://www.sap.com/developer/tutorials/hxe-gcp-hibernate-text-search.html[this article]
written by Jonathan Bregler.

https://www.baeldung.com/database-auditing-jpa[This article] shows you three ways you can implement an audit log
when using JPA and Hibernate:

- custom JPA callbacks,
- Hibernate Envers or
- Spring Data Audit capabilities

In https://www.baeldung.com/hibernate-query-to-custom-class[this article], you will see how to map an entity query to a custom DTO class using the JPA constructor result or the Hibernate-specific `ResultTransformer`.

== Time to upgrade

Hibernate Search has released
http://in.relation.to/2018/09/13/hibernate-search-5-10-4-Final-5-9-3-Final-5-6-6-Final/[three versions  (5.10.4, 5.9.3, 5.6.6)]. If you're using Hibernate Search, you might want to upgrade to the latest version of your branch and benefit from all the enhancements being added to the project.

JHipster https://www.jhipster.tech/2018/09/03/jhipster-release-5.3.0.html[5.3.0 has been released], and it now supports the https://github.com/jhipster/generator-jhipster/issues/8146[`hibernate.connection.provider_disables_autocommit`] Hibernate configuration property.

== Questions and answers

- https://discourse.hibernate.org/t/hibernate-query-cache-invalidation-after-persisting-entity/1334[Hibernate Query Cache invalidation after persisting entity]
- https://discourse.hibernate.org/t/how-to-select-multiple-many-to-many-associations-efficiently-using-jpql/1344[How to select multiple many-to-many associations efficiently using JPQL]
- https://discourse.hibernate.org/t/how-to-integrate-a-second-database-with-jpa-and-hibernate/1342[How to integrate a second database with JPA and Hibernate]
- https://stackoverflow.com/questions/11625096/cloning-jpa-entity[Cloning a JPA entity]
- https://stackoverflow.com/questions/52200422/how-to-run-a-hibernate-nativequery-in-a-type-safe-manner-returning-an-object/52251791#52251791[How to run a Hibernate NativeQuery in a type-safe manner instead of returning an `Object[]`]
- https://stackoverflow.com/questions/11043712/what-is-the-difference-between-non-repeatable-read-and-phantom-read/51123574#51123574[What is the difference between Non-Repeatable Read and Phantom Read?]
- https://stackoverflow.com/questions/52207233/hibernate-saves-retrieves-date-minus-day-if-application-uses-another-timezone-th/52211300#52211300[Hibernate saves/retrieves date minus day if the application uses another timezone than MySQL]
- https://stackoverflow.com/questions/337072/what-are-the-first-and-second-level-caches-in-hibernate/51306851#51306851[What are the First and Second Level caches in Hibernate?]
- https://discourse.hibernate.org/t/does-hibernate-provide-a-way-to-invalidate-l2-cache/1405[Does Hibernate provide a way to invalidate L2 cache?]
- https://discourse.hibernate.org/t/persisting-a-custom-uuid-class-as-a-varchar/1404[Persisting a custom UUID class as a VARCHAR]
- https://discourse.hibernate.org/t/hibernate-add-relationship-between-two-unrelated-entities-not-related-by-foreign-key/1369[Hibernate add relationship between two unrelated entities (not related by foreign key)]
- https://discourse.hibernate.org/t/logging-query-elides-where-clause/1392/2[Logging query elides where clause]
- https://discourse.hibernate.org/t/oracle-ht-tables-are-created-for-inheritence-type-table-per-class/1388/7[Oracle: HT_ tables are created for inheritance type table-per-class]
- https://discourse.hibernate.org/t/how-to-clone-an-entity-with-jpa-and-hibernate/1149/3[How to clone an entity with JPA and Hibernate]
- https://stackoverflow.com/questions/39382213/can-you-give-me-some-tips-for-hibernate-performance-tuning[Hibernate performance tuning tips]
