= Hibernate Validator 9.0.0.Beta3 is out
Marko Bekhta
:awestruct-tags: [ "Hibernate Validator", "Releases" ]
:awestruct-layout: blog-post
:hibernate-validator-doc-url-prefix: https://docs.hibernate.org/validator/9.0/reference/en-US/html_single/
:hibernate-validator-jira-url-prefix: https://hibernate.atlassian.net/browse
:hibernate-validator-version-family: 9.0
:hibernate-validator-jira-project-id: 10060
:hibernate-validator-jira-version-id: 32328
---

We just published Hibernate Validator 9.0.0.Beta3,
the next beta release of the new 9.0 series of Hibernate Validator.

This series targets Jakarta EE 11. It is the implementation of the Jakarta Validation 3.1.
Compared to the previous release in this series, this version
removes a few more constraints, configuration properties and APIs,
which have been deprecated for several major versions.
We have also identified some possible areas to improve while testing
the previous version in the downstream projects.
Also, there are some bug fixes.

== What's new

[NOTE]
====
For a summary of all new features and improvements since 8.0,
head to https://hibernate.org/validator/releases/9.0/#whats-new[the dedicated page on hibernate.org].
====

=== Jakarta EE 11 and Jakarta Validation 3.1

As a reminder: the 9.0 series targets Jakarta EE 11 and implements Jakarta Validation 3.1.
The 3.1 update of the specification does not bring many https://jakarta.ee/specifications/bean-validation/3.1/jakarta-validation-spec-3.1#whatsnew-31[changes]:

- The minimum required Java version is set to 17.
- The specification was renamed from _Jakarta Bean Validation_ to _Jakarta Validation_.
- Validation of Java `record` types was clarified (this has been supported by Hibernate Validator for some time).


=== Removal of the deprecated APIs

There were a few constraints, configuration properties,
and public API methods/classes that have been deprecated for several major versions now,
with available alternatives to migrate to.
With this new major version of Hibernate Validator some of these are removed.
For a detailed list of removed deprecated items see the https://hibernate.org/validator/documentation/migration-guide#9-0-x[migration guide].

[[osgi]]
=== OSGi integration clarification

Starting with Hibernate Validator 9.0, the Hibernate team no longer tests nor maintains the OSGi integration.
For users who would want to experiment with Hibernate Validator in an OSGi environment,
we will keep the existing manifest entries in place as they were.

[WARNING]
====
Even though we no longer maintain the Hibernate Validator OSGi integration,
we do encourage the community members interested in it to come forward with pull requests
if they encounter some issues. In such a case, we will try to guide the submitter through the contribution process
and assess the suggested patch for inclusion in the build.
====

[[other-changes]]
=== Other improvements and bug fixes

* link:{hibernate-validator-jira-url-prefix}/HV-2031[HV-2031]:
Make `PredefinedScopeHibernateValidatorFactory` aware of types for which constraint mappings are defined only in XML
* link:{hibernate-validator-jira-url-prefix}/HV-2029[HV-2029]:
Fix an issue when an exactly the same `ConvertGroup` is defined on both original and overridden methods in a class hierarchy leads to a constraint declaration exception.
* link:{hibernate-validator-jira-url-prefix}/HV-2018[HV-2018]:
Fix an issue related to validating values via `Validator#validateValue(..)`,
when the supplied bean type is an interface.

And more.
Please see the link:https://hibernate.atlassian.net/issues/?jql=project={hibernate-validator-jira-project-id}+AND+fixVersion={hibernate-validator-jira-version-id}[release notes]
for a complete list of changes since the previous releases.

== How to get this release

**Hibernate Validator 9 targets the upcoming Jakarta EE 11.**

All details are available and up to date on the
link:https://hibernate.org/validator/releases/{hibernate-validator-version-family}/#get-it[dedicated page on hibernate.org].

== Getting started, migrating

For new applications, please refer to the getting started guide:

* link:{hibernate-validator-doc-url-prefix}#validator-gettingstarted[Getting started with Hibernate Validator]

For existing applications, Hibernate Validator {hibernate-validator-version-family} in most cases is a drop-in replacement for 8.0,
assuming you also upgrade the other Jakarta EE 11 related dependencies and were not relying on the removed deprecated APIs.
Information about deprecated configuration and API
is included in the https://hibernate.org/validator/documentation/migration-guide/#migration-guide-9-0-x[migration guide].

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate-validator[hibernate-validator tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-validator/7[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HV[Issue tracker] (bug reports, feature requests)
* https://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
* https://accounts.eclipse.org/mailing-list/bean-validation-dev[Jakarta Validation development mailing list] (discussions about the Jakarta Validation specification)
