= Hibernate Search 7.2.0.CR1 is out
Marko Bekhta
:awestruct-tags: [ "Hibernate Search", "Lucene", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
:hsearch-doc-url-prefix: https://docs.jboss.org/hibernate/search/7.2/reference/en-US/html_single/
:hsearch-getting-started-orm-url-prefix: https://docs.jboss.org/hibernate/search/7.2/getting-started/orm/en-US/html_single/
:hsearch-getting-started-standalone-url-prefix: https://docs.jboss.org/hibernate/search/7.2/getting-started/standalone/en-US/html_single/
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse
:hsearch-version-family: 7.2
:hsearch-jira-project-id: 10061
:hsearch-jira-version-id: 32313
---

We just published Hibernate Search 7.2.0.CR1,
a first candidate release of the next minor version of Hibernate Search.

This version brings a new `prefix` predicate and a few improvements for the `knn` predicate,
compatibility with OpenSearch 2.15,
upgrades to Hibernate ORM 6.6,
and addresses a few bugs.

== What's new

[NOTE]
====
For a summary of all new features and improvements since 7.1,
head to https://hibernate.org/search/releases/7.2/#whats-new[the dedicated page on hibernate.org].
====

=== Dependency upgrades

[[orm-version]]
Hibernate ORM (link:{hsearch-jira-url-prefix}/HSEARCH-5217[HSEARCH-5217])::
Hibernate Search now depends on Hibernate ORM 6.6.0.CR2.
[[lucene-version]]
Lucene (link:{hsearch-jira-url-prefix}/HSEARCH-5184[HSEARCH-5184])::
The Lucene backend now uses Lucene 9.11.1.
[[elasticsearch-version]]
OpenSearch (link:{hsearch-jira-url-prefix}/HSEARCH-5181[HSEARCH-5181])::
The Elasticsearch backend now is compatible with OpenSearch 2.15 as well as with other versions that were already compatible.
[[others-version]]
Others::
* link:{hsearch-jira-url-prefix}/HSEARCH-5202[HSEARCH-5202]: Upgrade to Elasticsearch **client** 8.14.3
* link:{hsearch-jira-url-prefix}/HSEARCH-5200[HSEARCH-5200]: Upgrade to Jackson 2.17.2.
* link:{hsearch-jira-url-prefix}/HSEARCH-5212[HSEARCH-5212]: Upgrade to Avro 1.12.0.
* link:{hsearch-jira-url-prefix}/HSEARCH-5167[HSEARCH-5167]: Upgrade to HPPC 0.10.0.
* link:{hsearch-jira-url-prefix}/HSEARCH-5179[HSEARCH-5179]: Upgrade to AWS SDK 2.26.4.

[[search-dsl-predicate-knn]]
=== `knn` predicate updates

The OpenSearch 2.14 release introduced a way to apply score/similarity filters to a knn query.
This means that previous limitations imposed on the vector search filtering when using the OpenSearch distribution
of the Elasticsearch backend are now removed.
It is worth mentioning that because of how this filter is implemented on the OpenSearch side,
applying the similarity filter will result in ignoring the `k` value.

The `knn` predicate, besides the existing `.requiredMinimumSimilarity(..)` filter,
now also has a score-based alternative: `requiredMinimumScore(..)`.
With knn search, similarity and score are derived one from the other, and in some scenarios, it may be simpler to use score,
while in others -- similarity.

To remind you how the vector search works: for vector fields to be indexed, they should be annotated with a  `@VectorField` annotation:

[source, Java, indent=0, subs="+attributes"]
----
@Entity
@Indexed
public class Book {

    @Id
    private Integer id;

    @VectorField(dimension = 512)
    private float[] coverImageEmbeddings;

    // Other properties ...
}
----

Then, searching for vector similarities is performed via a `knn` predicate:

====
[source, Java, indent=0, subs="+callouts"]
----
float[] coverImageEmbeddingsVector = /*...*/

List<Book> hits = searchSession.search( Book.class )
.where( f ->
    f.knn( 5 ) // <1>
        .field( "coverImageEmbeddings" ) // <2>
        .matching( coverImageEmbeddingsVector ) // <3>
        .requiredMinimumSimilarity( similarity ) // <4>
).fetchHits( 20 );
----
<1> Provide the number of similar documents to look for.
<2> Specify the name of the vector field.
<3> Provide a reference vector; matched documents will be the ones whose indexed vector
is "most similar" to this vector.
<4> Specify the minimum required similarity between the reference and indexed vectors;
documents where indexed vector similarity is less than the specified `similarity` value will be filtered out.
Alternatively, the `requiredMinimumScore( score )` filter can be applied instead of the `requiredMinimumSimilarity( similarity )`.
====

See this section of the reference documentation on link:{hsearch-doc-url-prefix}#mapping-directfieldmapping-annotations-vectorfield[vector fields]
and the one on a link:{hsearch-doc-url-prefix}#search-dsl-predicate-knn[`knn` predicate]
for more information.

[[search-dsl-predicate-prefix]]
=== Prefix predicate

The `prefix` predicate matches documents for which a given field has a value starting with a given string.

====
[source, JAVA, indent=0, subs="+callouts"]
----
List<Book> hits = searchSession.search( Book.class )
    .where( f -> f.prefix().field( "description" )
        .matching( "rob" ) )
    .fetchHits( 20 );
----
====

See this section of the reference documentation on the link:{hsearch-doc-url-prefix}#search-dsl-predicate-prefix[`prefix` predicate]
for more information.

[[search-dsl-value-convert]]
=== `ValueConvert` gets deprecated

The Search DSL has been using `ValueConvert` enum to let the user specify how the values in search queries have to be converted,
be it the ones passed to the predicates/aggregations/sorts or the ones returned by projections/aggregations.
Moving forward, to better support new use cases and bring better clarity on the expectations, this enum is replaced with the new one: `ValueModel`.
At the moment `ValueModel` provides these options:

`MAPPING`:: This is the default model that allows working with the types as defined on the entity side.
`INDEX`:: This model does not apply conversion and allows working with the types as defined on the index side.
`STRING`:: This model applies formatting and parsing allowing working with the string representation of values.
`RAW`:: This model does not apply conversion and allows working with the types that the backend operates with on a low level.

For each deprecated method accepting the `ValueConvert` input, there is now an alternative that accepts `ValueModel` instead.
Replace `ValueConvert.YES` with `ValueModel.MAPPING` and `ValueConvert.NO` with `ValueModel.INDEX` in your code where the values were set explicitly.

See this section of the reference documentation on the link:{hsearch-doc-url-prefix}#search-dsl-argument-type[types of arguments passed to the DSL]
and on the link:{hsearch-doc-url-prefix}#search-dsl-projected-value-type[types of projected values]
for more information.

[[other-changes]]
=== Other improvements and bug fixes

* link:{hsearch-jira-url-prefix}/HSEARCH-5170[HSEARCH-5170]:
Fix a potential issue when setting an association to `null` before removing an entity may not trigger indexing

And more. For a full list of changes since the previous releases,
please see the link:https://hibernate.atlassian.net/issues/?jql=project={hsearch-jira-project-id}+AND+fixVersion={hsearch-jira-version-id}[release notes].

== How to get this release

All details are available and up to date on the
link:https://hibernate.org/search/releases/{hsearch-version-family}/#get-it[dedicated page on hibernate.org].

== Getting started, migrating

For new applications,
refer to the getting started guide:

* link:{hsearch-getting-started-orm-url-prefix}[here for the Hibernate ORM integration]
* link:{hsearch-getting-started-standalone-url-prefix}[here for the Standalone POJO Mapper]

For existing applications, Hibernate Search {hsearch-version-family} is a drop-in replacement for 7.1,
assuming you also upgrade the dependencies.
Information about deprecated configuration and API
is included in the https://docs.jboss.org/hibernate/search/{hsearch-version-family}/migration/html_single/[migration guide].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
