= Hibernate Search 7.2.4.Final maintenance release
Marko Bekhta
:awestruct-tags: [ "Hibernate Search", "Lucene", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
:hsearch-doc-url-prefix: https://docs.hibernate.org/search/7.2/reference/en-US/html_single/
:hsearch-getting-started-orm-url-prefix: https://docs.hibernate.org/search/7.2/getting-started/orm/en-US/html_single/
:hsearch-getting-started-standalone-url-prefix: https://docs.hibernate.org/search/7.2/getting-started/standalone/en-US/html_single/
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse
:hsearch-version-family: 7.2
:hsearch-jira-project-id: 10061
:hsearch-jira-version-id: 33175
---

We are pleased to announce the release of Hibernate Search 7.2.4.Final.

This release brings compatibility with Elasticsearch  8.16-8.18 and dependency upgrades.

+++<!-- more -->+++

== What's new in Hibernate Search 7.2.4.Final

=== Dependency upgrades

[[orm-version]]
Hibernate ORM (link:{hsearch-jira-url-prefix}/HSEARCH-5389[HSEARCH-5389])::
Hibernate Search now depends on Hibernate ORM 6.6.16.Final.
[[elasticsearch-version]]
Elasticsearch (link:{hsearch-jira-url-prefix}/HSEARCH-5269[HSEARCH-5269]/link:{hsearch-jira-url-prefix}/HSEARCH-5289[HSEARCH-5289]/link:{hsearch-jira-url-prefix}/HSEARCH-5365[HSEARCH-5365])::
The Elasticsearch backend is compatible with Elasticsearch 8.16, 8.17 and 8.18, as well as other already compatible versions.

And more. For a full list of changes since the previous releases,
please see the link:https://hibernate.atlassian.net/issues/?jql=project={hsearch-jira-project-id}+AND+fixVersion={hsearch-jira-version-id}[release notes].

=== How to get this release

All details are available and up to date on the
link:https://hibernate.org/search/releases/{hsearch-version-family}/#get-it[dedicated page on hibernate.org].

== Getting started, migrating

For new applications, refer to the getting started guide:

* link:{hsearch-getting-started-orm-url-prefix}[here for the Hibernate ORM integration]
* link:{hsearch-getting-started-standalone-url-prefix}[here for the Standalone POJO Mapper]

For existing applications, this release of Hibernate Search is a drop-in replacements of their previous micros within the same minors,
assuming you also upgrade the dependencies.
To upgrade to a newer major/minor, see https://hibernate.org/search/documentation/migrate/[migration guides].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
