= Hibernate Search 8.0.0.Beta1 is out
Marko Bekhta
:awestruct-tags: [ "Hibernate Search", "Lucene", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
:hsearch-doc-url-prefix: https://docs.jboss.org/hibernate/search/8.0/reference/en-US/html_single/
:horm-doc-url-prefix: https://docs.jboss.org/hibernate/orm/7.0/userguide/html_single/Hibernate_User_Guide.html
:hsearch-getting-started-orm-url-prefix: https://docs.jboss.org/hibernate/search/8.0/getting-started/orm/en-US/html_single/
:hsearch-getting-started-standalone-url-prefix: https://docs.jboss.org/hibernate/search/8.0/getting-started/standalone/en-US/html_single/
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse
:hsearch-version-family: 8.0
:hsearch-jira-project-id: 10061
:hsearch-jira-version-id: 33109
---

We just published Hibernate Search 8.0.0.Beta1,
the first beta release of the next major version of Hibernate Search.

This version includes the first implementation of the type-safe field references and Hibernate Search's static metamodel,
compatibility with the latest versions of Elasticsearch 9.0 and OpenSearch 3.0,
and other small adjustments and dependency upgrades.

== What's new

[NOTE]
====
Hibernate Search 8.0 is still in its early stages of development:
some features still need to be completed or may change in a backwards-incompatible way.
====

=== Dependency upgrades

[[orm-version]]
Hibernate ORM (link:{hsearch-jira-url-prefix}/HSEARCH-5367[HSEARCH-5367])::
Hibernate Search targets the Hibernate ORM 7.0 series, which implements Jakarta Persistence 3.2.0.
In particular, it is currently based on Hibernate ORM 7.0.0.CR1.
[[lucene-version]]
Lucene (link:{hsearch-jira-url-prefix}/HSEARCH-5373[HSEARCH-5373])::
The Lucene-next backend now uses Lucene 10.2.1.
[[elasticsearch-version]]
Elasticsearch (link:{hsearch-jira-url-prefix}/HSEARCH-5361[HSEARCH-5361]/(link:{hsearch-jira-url-prefix}/HSEARCH-5365[HSEARCH-5365]::
The Elasticsearch backend works with Elasticsearch 9.0 and 8.18, as well as other already compatible versions.
[[opensearch-version]]
OpenSearch (link:{hsearch-jira-url-prefix}/HSEARCH-5363[HSEARCH-5363]::
The Elasticsearch backend works with OpenSearch 3.0, as well as other already compatible versions.
[[others-version]]
Others::
* link:{hsearch-jira-url-prefix}/HSEARCH-5374[HSEARCH-5374]: Upgrade to Elasticsearch **client** 9.0.1
* link:{hsearch-jira-url-prefix}/HSEARCH-5370[HSEARCH-5370]: Upgrade to GSON 2.13.1.Final
* link:{hsearch-jira-url-prefix}/HSEARCH-5368[HSEARCH-5368]: Upgrade to Jandex 3.3
* link:{hsearch-jira-url-prefix}/HSEARCH-5371[HSEARCH-5371]: Upgrade to Jackson 2.19.0

[[static-metamodel]]
=== Static metamodel

Hibernate Search's link:{hsearch-doc-url-prefix}#static-metamodel[static metamodel] is a set of generated classes that represents the structure of each entity's index,
thereby allowing type-safe references to index fields when creating search queries through the link:{hsearch-doc-url-prefix}#search-dsl[Search DSL].

The basic principles are very similar to the link:{horm-doc-url-prefix}#tooling-modelgen[JPA static metamodel available in Hibernate ORM],
but in the case of Search the metamodel is about indexes rather than entities.

To try out this new feature, add the annotation processor to the build configuration:

====
[source,XML,subs="+attributes"]
----
<plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <executions>
        <execution>
            <id>default-compile</id>
            <configuration>
                <annotationProcessors>
                    <annotationProcessor>org.hibernate.search.processor.HibernateSearchProcessor</annotationProcessor> <1>
                </annotationProcessors>
                <annotationProcessorPaths>
                    <path>
                        <groupId>org.hibernate.search</groupId>
                        <artifactId>hibernate-search-processor</artifactId> <2>
                    </path>
                    <path>
                        <groupId>org.hibernate.search</groupId>
                        <artifactId>hibernate-search-backend-lucene</artifactId> <3>
                    </path>
                </annotationProcessorPaths>
            </configuration>
        </execution>
    </executions>
</plugin>
----

<1> Provide the fully qualified class name of the annotation processor that generates the metamodel.
<2> Add the `org.hibernate.search:hibernate-search-processor` dependency to the annotation processor path (a superset of the compile path),
so the Java compiler can find the processor.
<3> Add the backend dependency, in this example, the Lucene backend, to the annotation processor path.

NOTE: The version of both annotation processor and backend dependencies can be omitted in the definition of the annotation paths,
because they are defined in the Hibernate Search BOM, which we recommend you import via dependency management.
This way the generated metamodel classes will be based on the same backend that the application uses.
====

And then use the generated metamodel classes to create search queries, e.g.:

====
[source, JAVA, indent=0, subs="+callouts"]
----
SearchSession searchSession = /* ... */; // <1>
var scope = Book__.INDEX.scope( searchSession ); // <2>

List<Book> hits = searchSession.search( scope )
    .where( f -> f.match()
        .field( Book__.INDEX.title ).field( Book__.INDEX.description ) // <3>
        .matching( "robot" ) )
    .fetchHits( 20 );
----
<1> Obtain the search session.
<2> Create the search scope over the book index. Using such scope in the link:{hsearch-doc-url-prefix}#search-dsl[Search DSL] will automatically
limit acceptable field references to the ones obtained from the `Book__.INDEX`
<3> Use the metamodel to reference the fields when creating the queries.
====

See the corresponding section on link:{hsearch-doc-url-prefix}#static-metamodel[static metamodel]
to find out more.

[[other-changes]]
=== Other improvements and bug fixes

* link:{hsearch-jira-url-prefix}/HSEARCH-5305[HSEARCH-5305]:
Allow vector embeddings up to 16,000 dimensions with the Lucene backends.
* link:{hsearch-jira-url-prefix}/HSEARCH-5358[HSEARCH-5358]:
Fail faster if an enclosing instance parameter is encountered in a projection constructor on JDK 25+.

And more.
Please see the link:https://hibernate.atlassian.net/issues/?jql=project={hsearch-jira-project-id}+AND+fixVersion={hsearch-jira-version-id}[release notes]
for a complete list of changes since the previous releases.

== How to get this release

All details are available and up to date on the
link:https://hibernate.org/search/releases/{hsearch-version-family}/#get-it[dedicated page on hibernate.org].

== Getting started, migrating

For new applications,
refer to the getting started guide:

* link:{hsearch-getting-started-orm-url-prefix}[here for the Hibernate ORM integration]
* link:{hsearch-getting-started-standalone-url-prefix}[here for the Standalone POJO Mapper]

For existing applications, Hibernate Search {hsearch-version-family} is a drop-in replacement for 7.2,
assuming you also upgrade the dependencies.
Information about deprecated configuration and API
is included in the https://docs.jboss.org/hibernate/search/{hsearch-version-family}/migration/html_single/[migration guide].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
