= Hibernate Validator 9.1.0.Alpha1 is out
Marko Bekhta
:awestruct-tags: [ "Hibernate Validator", "Releases" ]
:awestruct-layout: blog-post
:hibernate-validator-doc-url-prefix: https://docs.hibernate.org/validator/9.1/reference/en-US/html_single/
:hibernate-validator-jira-url-prefix: https://hibernate.atlassian.net/browse
:hibernate-validator-version-family: 9.1
:hibernate-validator-jira-project-id: 10060
:hibernate-validator-jira-version-id: 33605
---

We just published Hibernate Validator 9.1.0.Alpha1,
the first release of the new 9.1 series of Hibernate Validator.

This series primarily aims to improve performance.
It also contains a few improvements, fixes and dependency updates.


[NOTE]
====
As this release includes significant changes to the processed bean tracking,
path implementation and related areas, we encourage users to give it a try,
especially if there are non-trivial validation scenarios.
====

== What's new

[[performance-improvements]]
=== Performance improvements

In this version, we have changed the `jakarta.validation.Path` implementation,
approach to processed bean tracking and slightly modified the message interpolation to improve both overall performance
and performance of cascading validation when beans require a lot of cascading operations.
We plan to publish a more detailed report with benchmark results, so stay tuned if you are interested in the details and numbers.

[[deprecating-valid]]
=== Deprecating the use of `@Valid` at the container level

Since Bean Validation 2.0, which introduced type argument constraints,
the approach of placing the `@Valid` annotation at the container level to apply cascading validation to container elements
has been considered a "legacy" approach.
Users have been encouraged to move their constraints to the type argument level.

.Legacy approach to cascading validation for container elements
====
[source, Java, indent=0, subs="+attributes"]
----
class MyBean {
    @Valid <1>
    List<MyContainerElement> list;
}
----
<1> Cascading validation is requested at the container level,
whereas the expectation is that container elements will be considered for cascading, not the container itself.
====

.Current approach to cascading validation for container elements
====
[source, Java, indent=0, subs="+attributes"]
----
class MyBean {
    List<@Valid MyContainerElement> list; <1>
}
----
<1> Cascading validation is requested at the container element level.
This clearly communicates the intention that elements are expected to be cascaded into and not the container itself.
====

Starting with 9.1, Hibernate Validator will produce warnings during the metadata building step
if it detects the legacy approach to cascading validation of container elements.
In the future version, this support of Bean Validation 1.0/1.1 legacy behaviour will be dropped.
Placing the `@Valid` at the container level would result in cascading into the container itself rather than into its elements.

[NOTE]
====
There is still some work ahead of us before we can turn off this legacy behaviour.
For example, we must address the case where the container does not have type arguments
but still requires cascading into its elements.
This is currently tracked at the Jakarta Validation specification level through the following link:https://github.com/jakartaee/validation/issues/266[issue].

We encourage users to review and update their validation mapping where necessary.
Additionally, if you encounter a particular use case that you believe is not covered, please don't hesitate to contact us.
====

[[hibernate-path]]
=== Extended validation path

This version introduces an extension the `jakarta.validation.Path`: `org.hibernate.validator.path.Path`.
We identified that there are a lot of use cases that require the leaf node of the path, and to get to it,
one usually would need to iterate through the path to get to the very last element:

.Iterate through the path to get the leaf node
====
[source, Java, indent=0, subs="+attributes"]
----
Path path = constraintViolation.getPropertyPath();
// use a for loop to iterate over the path nodes:
Node leaf = null;
for (Node node: path) {
    leaf = node;
}

// request the path node iterator explicitly:
Iterator<Path.Node> nodes = constraintViolation.getPropertyPath().iterator();
Path.Node leafNode = null;
while (nodes.hasNext()) {
    leafNode = nodes.next();
}
----
====

This approach might result in unnecessary allocations and operations,
especially if the underlying path implementation has a direct reference to the leaf node.

With that in mind `org.hibernate.validator.path.Path` introduces the `getLeafNode()` method.

.Using the Hibernate Validator extension to the `jakarta.validation.Path`
====
[source, Java, indent=0, subs="+attributes"]
----
Path path = constraintViolation.getPropertyPath();
if ( path instanceof org.hibernate.validator.path.Path hvPath ) {
    Node leaf = hvPath.getLeafNode();
	// ...
}
----
====

[[other-changes]]
=== Other improvements and bug fixes

Please see the link:https://hibernate.atlassian.net/issues/?jql=project={hibernate-validator-jira-project-id}+AND+fixVersion={hibernate-validator-jira-version-id}[release notes]
for a complete list of changes since the previous releases.

== How to get this release

**Hibernate Validator 9 targets the Jakarta EE 11.**

All details are available and up to date on the
link:https://hibernate.org/validator/releases/{hibernate-validator-version-family}/#get-it[dedicated page on hibernate.org].

== Getting started, migrating

For new applications, please refer to the getting started guide:

* link:{hibernate-validator-doc-url-prefix}#validator-gettingstarted[Getting started with Hibernate Validator]

For existing applications, Hibernate Validator {hibernate-validator-version-family} is a drop-in replacement for 9.0.
Information about deprecated configuration and API
is included in the https://hibernate.org/validator/documentation/migration-guide/#migration-guide-9-1-x[migration guide].

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate-validator[hibernate-validator tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-validator/7[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HV[Issue tracker] (bug reports, feature requests)
* https://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
* https://accounts.eclipse.org/mailing-list/bean-validation-dev[Jakarta Validation development mailing list] (discussions about the Jakarta Validation specification)
