= Hibernate Validator 9.0.1.Final is out
Marko Bekhta
:awestruct-tags: [ "Hibernate Validator", "Releases" ]
:awestruct-layout: blog-post
:hibernate-validator-doc-url-prefix: https://docs.hibernate.org/validator/9.0/reference/en-US/html_single/
:hibernate-validator-jira-url-prefix: https://hibernate.atlassian.net/browse
:hibernate-validator-version-family: 9.0
:hibernate-validator-jira-project-id: 10060
:hibernate-validator-jira-version-id: 33604
---

We are pleased to announce the release of Hibernate Validator 9.0.1.Final.

This release contains a few bug fixes and improvements to the recently included constraints.

== What's new

[NOTE]
====
For a summary of all new features and improvements since 8.0,
head to https://hibernate.org/validator/releases/9.0/#whats-new[the dedicated page on hibernate.org],
or check a more detailed list below.
====

[[other-changes]]
=== Other improvements and bug fixes

* link:{hibernate-validator-jira-url-prefix}/HV-2117[HV-2117]:
NIP validation incorrectly accepts values ending in 0
* link:{hibernate-validator-jira-url-prefix}/HV-2116[HV-2116]:
Do not recreate PersistenceUtil in the built-in JPATraversableResolver
* link:{hibernate-validator-jira-url-prefix}/HV-2114[HV-2114]:
Add support for Korean foreigner resident registration number (RRN) validation
* link:{hibernate-validator-jira-url-prefix}/HV-2113[HV-2113]:
Adding Date Validation Condition in KorRRNValidator


And more.
Please see the link:https://hibernate.atlassian.net/issues/?jql=project={hibernate-validator-jira-project-id}%20AND%20fixVersion%20IN%20({hibernate-validator-jira-version-id})[release notes]
for a complete list of changes since the previous releases.

== How to get this release

**Hibernate Validator 9 targets Jakarta EE 11.**

All details are available and up to date on the
link:https://hibernate.org/validator/releases/{hibernate-validator-version-family}/#get-it[dedicated page on hibernate.org].

== Getting started, migrating

For new applications, please refer to the getting started guide:

* link:{hibernate-validator-doc-url-prefix}#validator-gettingstarted[Getting started with Hibernate Validator]

For existing applications, Hibernate Validator {hibernate-validator-version-family} in most cases is a drop-in replacement for 8.0,
assuming you also upgrade the other Jakarta EE 11 related dependencies and were not relying on the removed deprecated APIs.
Information about deprecated configuration and API
is included in the https://hibernate.org/validator/documentation/migration-guide/#migration-guide-9-0-x[migration guide].

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate-validator[hibernate-validator tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-validator/7[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HV[Issue tracker] (bug reports, feature requests)
* https://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
* https://accounts.eclipse.org/mailing-list/bean-validation-dev[Jakarta Validation development mailing list] (discussions about the Jakarta Validation specification)
