= Hibernate Search 8.0.0.Alpha2 is out
Marko Bekhta
:awestruct-tags: [ "Hibernate Search", "Lucene", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
:hsearch-doc-url-prefix: https://docs.jboss.org/hibernate/search/8.0/reference/en-US/html_single/
:hsearch-getting-started-orm-url-prefix: https://docs.jboss.org/hibernate/search/8.0/getting-started/orm/en-US/html_single/
:hsearch-getting-started-standalone-url-prefix: https://docs.jboss.org/hibernate/search/8.0/getting-started/standalone/en-US/html_single/
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse
:hsearch-version-family: 8.0
:hsearch-jira-project-id: 10061
:hsearch-jira-version-id: 32366
---

We just published Hibernate Search 8.0.0.Alpha2,
the second alpha release of the next major version of Hibernate Search.

While testing the previous alpha, we've identified a few things that had to be adjusted and included them in this version.

It also upgrades Lucene and Hibernate ORM dependencies and includes compatibility with the latest
Elasticsearch and OpenSearch versions.

== What's new

[NOTE]
====
Hibernate Search 8.0 is still in its early stages of development:
some features still need to be completed or may change in a backwards-incompatible way.
====

=== Dependency upgrades

[[orm-version]]
Hibernate ORM (link:{hsearch-jira-url-prefix}/HSEARCH-5298[HSEARCH-5298])::
Hibernate Search now targets the Hibernate ORM 7.0 series, which implements Jakarta Persistence 3.2.0.
In particular, it is currently based on Hibernate ORM 7.0.0.Beta4.
[[lucene-version]]
Lucene (link:{hsearch-jira-url-prefix}/HSEARCH-5295[HSEARCH-5295])::
The Lucene-next backend now uses Lucene 10.1.0.
[[opensearch-version]]
OpenSearch (link:{hsearch-jira-url-prefix}/HSEARCH-5317[HSEARCH-5317]::
The Elasticsearch backend works with OpenSearch 2.19, as well as other already compatible versions.
[[others-version]]
Others::
* link:{hsearch-jira-url-prefix}/HSEARCH-5331[HSEARCH-5331]: Upgrade to Elasticsearch **client** 8.17.3
* link:{hsearch-jira-url-prefix}/HSEARCH-5312[HSEARCH-5312]: Upgrade to GSON 2.12.1.Final
* link:{hsearch-jira-url-prefix}/HSEARCH-5330[HSEARCH-5330]: Upgrade to Jackson 2.18.3
* link:{hsearch-jira-url-prefix}/HSEARCH-5238[HSEARCH-5238]: Upgrade to commons-codec 1.18.0
* link:{hsearch-jira-url-prefix}/HSEARCH-5343[HSEARCH-5343]: Upgrade to AWS SDK 2.31.2

[[other-changes]]
=== Other improvements and bug fixes

* link:{hsearch-jira-url-prefix}/HSEARCH-3204[HSEARCH-3204]:
Better detection of collection changes in the ORM mapper.
* link:{hsearch-jira-url-prefix}/HSEARCH-5334[HSEARCH-5334]:
Fix possible issue with sorting in the Lucene backend
* link:{hsearch-jira-url-prefix}/HSEARCH-5342[HSEARCH-5342]:
Improve class loading strategy in the Standalone mapper.

And more.
Please see the link:https://hibernate.atlassian.net/issues/?jql=project={hsearch-jira-project-id}+AND+fixVersion={hsearch-jira-version-id}[release notes]
for a complete list of changes since the previous releases.

== How to get this release

All details are available and up to date on the
link:https://hibernate.org/search/releases/{hsearch-version-family}/#get-it[dedicated page on hibernate.org].

== Getting started, migrating

For new applications,
refer to the getting started guide:

* link:{hsearch-getting-started-orm-url-prefix}[here for the Hibernate ORM integration]
* link:{hsearch-getting-started-standalone-url-prefix}[here for the Standalone POJO Mapper]

For existing applications, Hibernate Search {hsearch-version-family} is a drop-in replacement for 7.1,
assuming you also upgrade the dependencies.
Information about deprecated configuration and API
is included in the https://docs.jboss.org/hibernate/search/{hsearch-version-family}/migration/html_single/[migration guide].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
