= Hibernate Validator 9.1.0.Alpha2 is out
Marko Bekhta
:awestruct-tags: [ "Hibernate Validator", "Releases" ]
:awestruct-layout: blog-post
:hibernate-validator-doc-url-prefix: https://docs.hibernate.org/validator/9.1/reference/en-US/html_single/
:hibernate-validator-jira-url-prefix: https://hibernate.atlassian.net/browse
:hibernate-validator-version-family: 9.1
:hibernate-validator-jira-project-id: 10060
:hibernate-validator-jira-version-id: 35122
---

We just published Hibernate Validator 9.1.0.Alpha2,
the next release of the new 9.1 series of Hibernate Validator.

This series primarily aims to improve performance.
It also contains a few improvements, fixes and dependency updates.

[NOTE]
====
As this release includes significant changes to the processed bean tracking,
path implementation and related areas, we encourage users to give it a try and report any findings,
especially if there are non-trivial validation scenarios.
====

== What's new

[[performance-improvements]]
=== Performance improvements

In this version, we kept improving the performance.
We also finished preparing a more detailed report on performance improvements and will publish it soon,
so stay tuned if you are interested in the details and numbers.

[[hibernate-path]]
=== Extended validation path

This version introduces another extension of the `jakarta.validation.Path`: `org.hibernate.validator.path.RandomAccessPath`.
There are scenarios where the first couple of nodes have to be inspected to determine how to process the constraint violation.
For cases when the path is represented by an array or some other collection that allows easy random access to the nodes,
it would be simple enough to expose the access to the nodes by index:

.Random access to the path nodes
====
[source, Java, indent=0, subs="+attributes"]
----
Path path = constraintViolation.getPropertyPath();
if ( path instanceof org.hibernate.validator.path.RandomAccessPath hvPath ) {
    Node rootNode = hvPath.getRootNode();
    // ...
    int index = ...
    Node someNode = hvPath.getNode(index);
    // ...
    for(int i; i < hvPath.length(); i++) {
        hvPath.getNode(i);
    }
}
----
====

[[initialization-data]]
=== Constraint initialization shared data

Constraint initialization shared data opens up a way for constraint validators to access a shared instance within the `initialize(..)`.
This can be used to cache and reuse elements required to construct a constraint validator. For example,
internally, this mechanism is used by the pattern constraint validator to reuse the `java.util.regex.Pattern` instances

.Accessing the constraint validator's lazy initialization shared data in a constraint validator
====
[source, JAVA, indent=0]
----
public class ParsableDateTimeFormatValidator
    implements HibernateConstraintValidator<ParsableDateTimeFormat, String> { // <1>

    private DateTimeFormatter formatter;

    @Override
    public void initialize(ConstraintDescriptor<ParsableDateTimeFormat> constraintDescriptor,
            HibernateConstraintValidatorInitializationContext initializationContext) {
        formatter = initializationContext.getSharedData( DateTimeFormatterCache.class, DateTimeFormatterCache::new ) // <2>
                .get( constraintDescriptor.getAnnotation().dateFormat() ); // <3>
    }

    @Override
    public boolean isValid(String dateTime, ConstraintValidatorContext constraintContext) {
        if ( dateTime == null ) {
            return true;
        }

        try {
            formatter.parse( dateTime );
        }
        catch (DateTimeParseException e) {
            return false;
        }
        return true;
    }

    private static class DateTimeFormatterCache { // <4>
        private final Map<String, DateTimeFormatter> cache = new ConcurrentHashMap<>();

        DateTimeFormatter get(String format) {
            return cache.computeIfAbsent( format, DateTimeFormatter::ofPattern );
        }
    }
}
----
<1> Implement the Hibernate Validator `HibernateConstraintValidator` extension to have access to the initialization context.
<2> Retrieve the shared data from the initialization context, providing the supplier that will be executed
if the `DateTimeFormatterCache` is not yet available in the current initialization context.
<3> Perform some actions with the shared data instance.
<4> A simple wrapper around the map to cache the formatters.
Compared to the use of a static field cache, using the shared data has the benefit that it is tied to the initialization context
and will be garbage collected along with it.
====

See the corresponding section on link:{hibernate-validator-doc-url-prefix}#constraint-validator-shared-data[constraint initialization shared data]
to find out more.

[[other-changes]]
=== Other improvements and bug fixes

* link:{hibernate-validator-jira-url-prefix}/HV-2004[HV-2004]:
`java.util.regex.Pattern` cache for `@Pattern` constraints

Please see the link:https://hibernate.atlassian.net/issues/?jql=project={hibernate-validator-jira-project-id}+AND+fixVersion={hibernate-validator-jira-version-id}[release notes]
for a complete list of changes since the previous releases.

== How to get this release

**Hibernate Validator 9 targets the Jakarta EE 11.**

All details are available and up to date on the
link:https://hibernate.org/validator/releases/{hibernate-validator-version-family}/#get-it[dedicated page on hibernate.org].

== Getting started, migrating

For new applications, please refer to the getting started guide:

* link:{hibernate-validator-doc-url-prefix}#validator-gettingstarted[Getting started with Hibernate Validator]

For existing applications, Hibernate Validator {hibernate-validator-version-family} is a drop-in replacement for 9.0.
Information about deprecated configuration and API
is included in the https://hibernate.org/validator/documentation/migration-guide/#migration-guide-9-1-x[migration guide].

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate-validator[hibernate-validator tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-validator/7[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HV[Issue tracker] (bug reports, feature requests)
* https://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
* https://accounts.eclipse.org/mailing-list/bean-validation-dev[Jakarta Validation development mailing list] (discussions about the Jakarta Validation specification)
