= Hibernate Search 8.4.0.Final is out
Marko Bekhta
:awestruct-tags: [ "Hibernate Search", "Lucene", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
:hsearch-doc-url-prefix: https://docs.hibernate.org/search/8.4/reference/en-US/html_single/
:hsearch-getting-started-orm-url-prefix: https://docs.hibernate.org/search/8.4/getting-started/orm/en-US/html_single/
:hsearch-getting-started-standalone-url-prefix: https://docs.hibernate.org/search/8.4/getting-started/standalone/en-US/html_single/
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse
:hsearch-version-family: 8.4
:hsearch-jira-project-id: 10061
:hsearch-jira-version-id: 39072
---

We just published Hibernate Search 8.4.0.Final.

Compared to the previously released 8.4.0.CR1, this version is mostly identical,
and only adds a few changes to adapt to the final release of Hibernate ORM 7.4.0.Final
and improve the Hibernate Search ORM mapper integration.

== What's new

=== Dependency upgrades

[[orm-version]]
Hibernate ORM (link:{hsearch-jira-url-prefix}/HSEARCH-5623[HSEARCH-5623])/(link:{hsearch-jira-url-prefix}/HSEARCH-5630[HSEARCH-5630])::
Hibernate Search targets the Hibernate ORM 7.4 series.
[[elasticsearch-version]]
Elasticsearch (link:{hsearch-jira-url-prefix}/HSEARCH-5620[HSEARCH-5620])/(link:{hsearch-jira-url-prefix}/HSEARCH-5625[HSEARCH-5625])::
The Elasticsearch backend works with Elasticsearch 9.4, as well as other already compatible versions.
[[opensearch-version]]
OpenSearch (link:{hsearch-jira-url-prefix}/HSEARCH-5606[HSEARCH-5606])::
The Elasticsearch backend works with OpenSearch 3.6, as well as other already compatible versions.
[[others-version]]
Others::
* link:{hsearch-jira-url-prefix}/HSEARCH-5626[HSEARCH-5626]: Upgrade to Elasticsearch **client** 9.4.1 (`elasticsearch-rest-client`)
* link:{hsearch-jira-url-prefix}/HSEARCH-5624[HSEARCH-5624]: Upgrade to Elasticsearch **client** 9.4.1 (`elasticsearch-rest5-client`)
* link:{hsearch-jira-url-prefix}/HSEARCH-5607[HSEARCH-5607]: Upgrade to OpenSearch **client** 3.6.0 (`opensearch-rest-client`)
* link:{hsearch-jira-url-prefix}/HSEARCH-5617[HSEARCH-5617]: Upgrade to AWS SDK 2.44.1
* link:{hsearch-jira-url-prefix}/HSEARCH-5611[HSEARCH-5611]: Upgrade to Apache HTTP Client Components 5.6.1
* link:{hsearch-jira-url-prefix}/HSEARCH-5599[HSEARCH-5599]: Upgrade to Apache HTTP Core Client components 5.4.2

[[behavior-stateless-session]]
=== `StatelessSession` usage with indexed entities now throws an explicit exception

Hibernate Search now explicitly detects when
link:{hsearch-doc-url-prefix}#limitations-stateless-session[listener-triggered indexing]
is used with a `StatelessSession` and throws an exception.

Previously, this scenario could lead to confusing errors.

If you need to use a `StatelessSession` to persist or update indexed entities,
see the link:{hsearch-doc-url-prefix}#limitations-stateless-session-solution[workarounds documented in the reference guide].

[[other-changes]]
=== Other improvements and bug fixes

Please see the link:https://hibernate.atlassian.net/issues/?jql=project={hsearch-jira-project-id}+AND+fixVersion={hsearch-jira-version-id}[release notes]
for a complete list of changes since the previous releases.

== How to get this release

All details are available and up to date on the
link:https://hibernate.org/search/releases/{hsearch-version-family}/#get-it[dedicated page on hibernate.org].

== Getting started, migrating

For new applications,
refer to the getting started guide:

* link:{hsearch-getting-started-orm-url-prefix}[here for the Hibernate ORM integration]
* link:{hsearch-getting-started-standalone-url-prefix}[here for the Standalone POJO Mapper]

For existing applications, Hibernate Search {hsearch-version-family} is a drop-in replacement for 8.3,
assuming you also upgrade the dependencies.
Information about deprecated configuration and API
is included in the https://docs.hibernate.org/search/{hsearch-version-family}/migration/html_single/[migration guide].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
