= Hibernate Search 8.3.0.Final is out
Marko Bekhta
:awestruct-tags: [ "Hibernate Search", "Lucene", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
:hsearch-doc-url-prefix: https://docs.hibernate.org/search/8.3/reference/en-US/html_single/
:hsearch-getting-started-orm-url-prefix: https://docs.hibernate.org/search/8.3/getting-started/orm/en-US/html_single/
:hsearch-getting-started-standalone-url-prefix: https://docs.hibernate.org/search/8.3/getting-started/standalone/en-US/html_single/
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse
:hsearch-version-family: 8.3
:hsearch-jira-project-id: 10061
:hsearch-jira-version-id: 37774
---

We just published Hibernate Search 8.3.0.Final.

Compared to the previously released 8.3.0.CR1, this version is mostly identical,
and only adds a few changes to adapt to the final release of Hibernate ORM 7.3.0.Final.

== What's new

=== Dependency upgrades

[[orm-version]]
Hibernate ORM (link:{hsearch-jira-url-prefix}/HSEARCH-5591[HSEARCH-5591])::
Hibernate Search targets the Hibernate ORM 7.3 series.
[[elasticsearch-version]]
Elasticsearch (link:{hsearch-jira-url-prefix}/HSEARCH-5564[HSEARCH-5564])::
The Elasticsearch backend works with Elasticsearch 9.3, as well as other already compatible versions.
[[opensearch-version]]
OpenSearch (link:{hsearch-jira-url-prefix}/HSEARCH-5543[HSEARCH-5543])/(link:{hsearch-jira-url-prefix}/HSEARCH-5568[HSEARCH-5568])::
The Elasticsearch backend works with OpenSearch 3.4 and 3.5, as well as other already compatible versions.
Lucene (link:{hsearch-jira-url-prefix}/HSEARCH-5586[HSEARCH-5586])::
The Lucene-next backend is now based on Lucene 10.4.0.
[[others-version]]
Others::
* link:{hsearch-jira-url-prefix}/HSEARCH-5580[HSEARCH-5580]: Upgrade to Elasticsearch **client** 9.3.1 (`elasticsearch-rest-client`)
* link:{hsearch-jira-url-prefix}/HSEARCH-5587[HSEARCH-5587]: Upgrade to Elasticsearch **client** 9.3.2 (`elasticsearch-rest5-client`)
* link:{hsearch-jira-url-prefix}/HSEARCH-5545[HSEARCH-5545]: Upgrade to OpenSearch **client** 3.5.0 (`opensearch-rest-client`)
* link:{hsearch-jira-url-prefix}/HSEARCH-5594[HSEARCH-5594]: Upgrade to AWS SDK 2.42.14

[[other-changes]]
=== Other improvements and bug fixes

Please see the link:https://hibernate.atlassian.net/issues/?jql=project={hsearch-jira-project-id}+AND+fixVersion={hsearch-jira-version-id}[release notes]
for a complete list of changes since the previous releases.

== How to get this release

All details are available and up to date on the
link:https://hibernate.org/search/releases/{hsearch-version-family}/#get-it[dedicated page on hibernate.org].

== Getting started, migrating

For new applications,
refer to the getting started guide:

* link:{hsearch-getting-started-orm-url-prefix}[here for the Hibernate ORM integration]
* link:{hsearch-getting-started-standalone-url-prefix}[here for the Standalone POJO Mapper]

For existing applications, Hibernate Search {hsearch-version-family} is a drop-in replacement for 8.2,
assuming you also upgrade the dependencies.
Information about deprecated configuration and API
is included in the https://docs.hibernate.org/search/{hsearch-version-family}/migration/html_single/[migration guide].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
