= First candidate release for Hibernate Search with Elasticsearch!
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
---

It's finally here! We just published the first candidate release of Hibernate Search with experimental Elasticsearch integration (5.6.0.CR1), along with 5.7.0.Beta2.

Version 5.6.0.CR1 brings the https://hibernate.atlassian.net/issues/?jql=fixVersion%20%3D%205.6.0.CR1[latest bugfixes and previously missing features] for our experimental Elasticsearch integration. This is the version to use with Hibernate ORM versions 5.0 and 5.1.

Version 5.7.0.Beta2 brings the exact same changes as 5.6.0.CR1, and it still features the compatibility with Hibernate ORM
version 5.2 that was introduced with 5.7.0.Alpha1.

== What's new?

 * https://hibernate.atlassian.net/browse/HSEARCH-2348[HSEARCH-2348]: Elasticsearch queries are now logged at the
   `DEBUG` level on the `org.hibernate.search.fulltext_query` logger, just as embedded Lucene queries.
 * https://hibernate.atlassian.net/browse/HSEARCH-2449[HSEARCH-2449]: more configuration options have been added regarding
   the connection to Elasticsearch, including the size of connection pools, the connection/read timeouts, and
   the automatic discovery of new nodes in the Elasticsearch cluster for client-side loadbalancing and (limited) failover.
 * https://hibernate.atlassian.net/browse/HSEARCH-2219[HSEARCH-2219]: analyzer definitions are now automatically
   translated and added to the Elasticsearch settings when Elasticsearch indexes are created.
   Please note there are still some limitations, most notably the definitions are not updated automatically (no support
   for the MERGE schema management strategy).
   See the https://docs.jboss.org/hibernate/search/5.6/reference/en-US/html_single/#elasticsearch-mapping-analyzer[documentation]
   for more information about analyzers with Elasticsearch.
 * https://hibernate.atlassian.net/browse/HSEARCH-2387[HSEARCH-2387]: Elasticsearch mappings generated by Hibernate Search
   used to be strictly static. This can be an issue in some cases, which is why opt-in dynamic mappings are now available,
   either through a global option (see `org.hibernate.search.elasticsearch.cfg.ElasticsearchEnvironment.DYNAMIC_MAPPING`)
   or locally on metadata-providing field bridges (`builder.field( name, FieldType.OBJECT ).mappedOn( Elasticsearch.class ).dynamic( DynamicType.TRUE )`).
   Thanks to Alex Laptseu for reporting this!
 * ... and much more, mainly bug fixes.
   The full change log can be found on https://hibernate.atlassian.net/secure/ReleaseNote.jspa?projectId=10061&version=25900[our JIRA instance].

== When will 5.6 be released?

As far as we are concerned, 5.6 is ready.
Version 5.6.0.CR1 is the last opportunity for the community to test it and report bugs before the release
which, if all goes well, will happen in early January.

== What about Elasticsearch 5 support?

As mentioned in the http://in.relation.to/2016/11/29/hibernate-search-5-6-0-Beta4-and-5-7-0-Beta1/[blog post about the previous release], Elasticsearch 5.x is not supported yet.

Quoting:

_____
The main reason is it brings several backward-incompatible changes that would require quite a bit of work if we still want to support the 2.x series. And we don't want to postpone the Hibernate Search 5.6.0 release any more.

Our plan is to release a 5.6 supporting Elasticsearch 2.x, and add Elasticsearch 5 support in Hibernate Search 6.0 or, maybe, in an early 5.8 release. You may refer to https://hibernate.atlassian.net/browse/HSEARCH-2434[HSEARCH-2434] to track the status of Elasticsearch 5.0 support.
_____

== When will 5.7 be released?

We are planning to publish a candidate release for 5.7 soon after 5.6.0.Final has been released.

== How to get these releases

All versions are available on Hibernate Search's https://hibernate.org/search/[web site].

Ideally use a tool to fetch it from Maven central; these are the coordinates:

====
[source, XML]
----
<dependency>
   <groupId>org.hibernate</groupId>
   <artifactId>hibernate-search-orm</artifactId>
   <version>5.6.0.CR1</version>
</dependency>
----
====

Or, for Hibernate Search 5.7:

====
[source, XML]
----
<dependency>
   <groupId>org.hibernate</groupId>
   <artifactId>hibernate-search-orm</artifactId>
   <version>5.7.0.Beta2</version>
</dependency>
----
====

To use the experimental Elasticsearch integration you'll also need:

====
[source, XML]
----
<dependency>
   <groupId>org.hibernate</groupId>
   <artifactId>hibernate-search-elasticsearch</artifactId>
   <version>5.6.0.CR1</version>
</dependency>
----
====

Change the version to `5.7.0.Beta2` in order to test the Elasticsearch integration within Hibernate Search 5.7.

Downloads from https://sourceforge.net/projects/hibernate/files/hibernate-search/[Sourceforge] are available as well.

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://forum.hibernate.org/viewforum.php?f=9[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)

