= Hibernate Search 5.9.0.Beta1 was just released
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
:awestruct-project: search
---

We just published 5.9.0.Beta1, the first beta release for the 5.9 branch.
This release brings several bug fixes, but most importantly a new mass indexer
based on the JSR 352 specification, "Batch Applications for the Java Platform"!

== What's new?

Here are the most notable changes since Hibernate Search 5.8.0.Final:

 * https://hibernate.atlassian.net/browse/HSEARCH-2883[HSEARCH-2594]:
   A JSR 352 mass indexing job was added, adding in particular the ability to restart
   from a checkpoint when indexing fails.
   We will soon post a blog post with more information about
   how it is better than the original mass indexer
   and how to use it, so stay tuned!
 * https://hibernate.atlassian.net/browse/HSEARCH-2832[HSEARCH-2832]:
   Exception messages when an Elasticsearch work fails are now a bit less
   verbose. In particular they don't include the failing request anymore,
   because it can often be huge and ends up flooding the logs (especially due to request bulking).
   You can still log every Elasticsearch request
   https://docs.jboss.org/hibernate/search/5.9/reference/en-US/html_single/#elasticsearch-logging[as explained in the documentation].
 * https://hibernate.atlassian.net/browse/HSEARCH-2883[HSEARCH-2883]:
   Requests to Elasticsearch clusters with URL-based access control
   used to fail because of a trailing slash. This is no longer the case.
 * https://hibernate.atlassian.net/browse/HSEARCH-2886[HSEARCH-2886]:
   In certain circumstances, Elasticsearch requests containing 3 or 4-byte unicode characters
   could fail. These encoding issues have been resolved.
 * https://hibernate.atlassian.net/browse/HSEARCH-2909[HSEARCH-2909]:
   Annotations in the default package will no longer make the annotation processing fail.
 * https://hibernate.atlassian.net/browse/HSEARCH-2935[HSEARCH-2935]:
   The CPU cost of static initialization of Hibernate Search loggers
   has been sensibly reduced, improving startup performance.

For a full list of changes since 5.8.0.Final,
please see https://hibernate.atlassian.net/secure/ReleaseNote.jspa?projectId=10061&version=31616[the release notes].

== How to get this release

All the necessary information is available (and updated regularly)
on https://hibernate.org/search/releases/5.9/#get-it[hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://forum.hibernate.org/viewforum.php?f=9[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
