= Hibernate Search 5.8.0.Beta2 is out!
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
---

We just published Hibernate Search version 5.8.0.Beta2,
with bugfixes and improvements over http://in.relation.to/2017/04/15/HibernateSearchNowSpeakingEs5/[5.8.0.Beta1].

[WARNING]
====
Hibernate Search 5.8.0.Beta2, just as 5.7.0.Final, is only compatible with Hibernate ORM 5.2.3 and later.

If you need to use Hibernate ORM 5.0.x or 5.1.x and cannot upgrade,
please use Hibernate Search 5.6.1.Final.
====

== About 5.8

Hibernate Search 5.8 is about:

 * making the Elasticsearch integration compatible with Elasticsearch 5.x (done);
 * improving performance of the Elasticsearch integration (in progress);
 * introducing a new DSL for defining analyzers (in progress);
 * ensuring that Hibernate Search will work well with Java 9 (done, though Java 9 may still change);
 * improving and documenting Wildfly Swarm integration (in discussion);
 * removing the need for class definition on master nodes in JMS/JGroups integration (in discussion);
 * and of course, fixing reported bugs. 

You can have a look at https://hibernate.org/search/roadmap/[the roadmap] for more details.

== What's new since the first Beta?

For a full list of changes since 5.8.0.Beta1, please see https://hibernate.atlassian.net/issues/?jql=project=10061+AND+fixVersion=29000[the release notes].

Below is a summary of the main changes:

 * https://hibernate.atlassian.net/browse/HSEARCH-2606[HSEARCH-2606]: duplicate parameters in analyzer definitions
   are now detected automatically and trigger an error on startup.
 * https://hibernate.atlassian.net/browse/HSEARCH-2014[HSEARCH-2014] (local Lucene indexes only):
   index size is now reported as part of Hibernate Search statistics,
   available over JMX in particular if enabled.
 * https://hibernate.atlassian.net/browse/HSEARCH-2208[HSEARCH-2208]: use of `org.apache.lucene.search.Filter`
   throughout the APIs has been deprecated. You should use `org.apache.lucene.search.Query` instead,
   because `org.apache.lucene.search.Filter` will be removed when we next upgrade the Lucene dependency (in Hibernate Search 6).
   See the https://docs.jboss.org/hibernate/search/5.8/reference/en-US/html_single/#query-filter[updated documentation]
   for examples on how to achieve filters using queries
   (you might need to refresh your browser cache to see the latest version of the documentation).
 * https://hibernate.atlassian.net/browse/HSEARCH-2675[HSEARCH-2675]: master election when the current master fails
   now works correctly with the JGroups backend.
 * https://hibernate.atlassian.net/browse/HSEARCH-1886[HSEARCH-1886]: we made preliminary changes to make dynamic sharding
   work correctly with replicated (JGroups/JMS) backends.
   You can follow progress on https://hibernate.atlassian.net/browse/HSEARCH-2676[HSEARCH-2676].
 * https://hibernate.atlassian.net/browse/HSEARCH-2502[HSEARCH-2502]: the worker can now be set to execute works asynchronously
   even when using Elasticsearch, by setting the
   https://docs.jboss.org/hibernate/search/5.8/reference/en-US/html_single/#configuration-worker[same `*.worker.execution` configuration option]
   as when using local Lucene indexes.

We'd also like to thank Andrej Golovnin for his work on https://hibernate.atlassian.net/browse/HSEARCH-2691[HSEARCH-2691],
fixing a bug related to query caching.

== How to get this release

All versions are available on Hibernate Search's https://hibernate.org/search/[web site].

Ideally use a tool to fetch it from Maven central; these are the coordinates:

====
[source, XML]
----
<dependency>
   <groupId>org.hibernate</groupId>
   <artifactId>hibernate-search-orm</artifactId>
   <version>5.8.0.Beta2</version>
</dependency>
----
====

To use the experimental Elasticsearch integration you'll also need:

====
[source, XML]
----
<dependency>
   <groupId>org.hibernate</groupId>
   <artifactId>hibernate-search-elasticsearch</artifactId>
   <version>5.8.0.Beta2</version>
</dependency>
----
====

Downloads from https://sourceforge.net/projects/hibernate/files/hibernate-search/[Sourceforge] are available as well.

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://forum.hibernate.org/viewforum.php?f=9[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)

