= Hibernate Search 5.8.0.Final is out!
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
---

We just published 5.8.0.Final, the first stable release in the 5.8 branch.
Hibernate Search is now compatible with every recent, stable versions of Elasticsearch!


== What's new?

Here are the most notable changes since Hibernate Search 5.7:

 * Hibernate Search now
   http://in.relation.to/2017/04/15/HibernateSearchNowSpeakingEs5/[integrates with all version of Elasticsearch from 2.0 to 5.6]
 * A new type of query is available in the DSL:
   http://in.relation.to/2017/04/27/simple-query-string-what-about-it/[Simple Query Strings]
 * We introduced http://in.relation.to/2017/06/13/hibernate-search-5-8-0-Beta3/#analyzer-providers[analyzer providers]
   to allow for smoother, mapping-independent analyzer definitions, especially in the Elasticsearch case.
 * We introduced http://in.relation.to/2017/06/13/hibernate-search-5-8-0-Beta3/#normalizers[normalizers]
   to make it easier to deal with non-tokenized text (which includes sort fields in particular).

And much more! For a full list of changes since 5.7, please see https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20fixVersion%20in%20(5.8.0.Final%2C%205.8.0.CR1%2C%205.8.0.Beta4%2C%205.8.0.Beta3%2C%205.8.0.Beta2%2C%205.8.0.Beta1)%20ORDER%20BY%20updated[this list of tickets on our JIRA instance].

For those of you keeping track of the Alpha/Beta/CR releases:
the candidate release phase went rather well, with only a few bugs fixed since CR1.
For a full list of changes since 5.8.0.CR1,
please see https://hibernate.atlassian.net/issues/?jql=project=10061+AND+fixVersion=30900[the release notes].

== How to get these releases

All versions are available on Hibernate Search's https://hibernate.org/search/[web site].

Ideally use a tool to fetch it from Maven Central; these are the coordinates:

====
[source, XML]
----
<dependency>
   <groupId>org.hibernate</groupId>
   <artifactId>hibernate-search-orm</artifactId>
   <version>5.8.0.Final</version>
</dependency>
----
====

To use the experimental Elasticsearch integration you'll also need:

====
[source, XML]
----
<dependency>
   <groupId>org.hibernate</groupId>
   <artifactId>hibernate-search-elasticsearch</artifactId>
   <version>5.8.0.Final</version>
</dependency>
----
====

To use Amazon's proprietary IAM authentication mechanism to access your Elasticsearch cluster you'll also need:

====
[source, XML]
----
<dependency>
   <groupId>org.hibernate</groupId>
   <artifactId>hibernate-search-elasticsearch-aws</artifactId>
   <version>5.8.0.Final</version>
</dependency>
----
====

Downloads from https://sourceforge.net/projects/hibernate/files/hibernate-search/[Sourceforge] are available as well.

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://forum.hibernate.org/viewforum.php?f=9[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
