= Hibernate Search 5.7.0.Final release is out!
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
---

You asked for it, we deliver: Hibernate Search 5.7.0.Final, with support for Hibernate ORM 5.2.8, is out!
And of course, like previous versions, it features experimental support for Elasticsearch integration
(even with some improvements).

Stuck on an older ORM version? Don't worry, we also released a bugfix version for 5.6, namely 5.6.1.Final.

[WARNING]
====
Hibernate Search 5.7.0.Final is only compatible with Hibernate ORM 5.2.3 and later. There isn't any version of Hibernate Search compatible Hibernate ORM 5.2.0 to 5.2.2.

If you need to use Hibernate ORM 5.0.x or 5.1.x and cannot upgrade,
please use Hibernate Search 5.6.1.Final.
====

== What's new on 5.7 since the candidate release?

Below are the main changes since the candidate release.

If you are looking for advice on how to migrate, please refer to the
http://hibernate.org/search/documentation/migrate/5.7/[migration guide].

For a full list of changes since 5.7.0.CR1, please see https://hibernate.atlassian.net/secure/ReleaseNote.jspa?projectId=10061&version=27300[the release notes].
For a full list of changes since 5.6.0.Final, please see https://hibernate.atlassian.net/issues/?jql=fixVersion%20in%20(5.7.0.Alpha1%2C%205.7.0.Beta1%2C%205.7.0.Beta2%2C%205.7.0.CR1%2C%205.7.0.Final)%20AND%20fixVersion%20not%20in%20(5.6.0.Alpha1%2C%205.6.0.Alpha2%2C%205.6.0.Alpha3%2C%205.6.0.Beta1%2C%205.6.0.Beta2%2C%205.6.0.Beta3%2C%205.6.0.Beta4%2C%205.6.0.CR1%2C%205.6.0.Final)[this list of tickets on our JIRA instance].

=== General improvements

 * https://hibernate.atlassian.net/browse/HSEARCH-2574[HSEARCH-2574]: when it makes sense,
   you can now repeat Hibernate Search annotations on a single attribute/method.
   For example, if you want to add two index fields on the same `title` attribute, you can write:
+
====
[source, Java]
----
    @Field(analyzer = @Analyzer(definition = "myAnalyzer")
    @Field(name = "title_sort", analyzer = @Analyzer(definition = "myAnalyzerForSort")
    private String title;
====
+
Thus you don't have to use the composite annotations (`@Fields`) anymore.
But of course, those are still available.
 * https://hibernate.atlassian.net/browse/HSEARCH-2588[HSEARCH-2588]: some methods in the Sort DSL allowed to specify
   the sort field type explicitly, which was useful when sorting on fields added through custom field bridges.
   We improved support for `MetadataProvidingFieldBridge`,
   so that you now only need to implement this interface on your custom field bridges,
   and won't need anything special when using the sort DSL anymore.
   As a result, the `byField(String, SortField.Type)` and `andByField(String, SortField.Type)` methods
   in the sort DSL have been deprecated.  
 * https://hibernate.atlassian.net/browse/HSEARCH-2587[HSEARCH-2587]: an NPE could occur when using the Sort DSL to sort on embedded (`@IndexedEmbedded`) fields; this is now fixed.
 * https://hibernate.atlassian.net/browse/HSEARCH-2576[HSEARCH-2576]: unnecessary memory allocations within queries have
   been removed, resulting in better query throughput.
 * And several improvements for other solutions integrating Hibernate Search, like https://hibernate.atlassian.net/browse/HSEARCH-2597[HSEARCH-2597], https://hibernate.atlassian.net/browse/HSEARCH-2561[HSEARCH-2561], https://hibernate.atlassian.net/browse/HSEARCH-2418[HSEARCH-2418] or https://hibernate.atlassian.net/browse/HSEARCH-2585[HSEARCH-2585].


=== Elasticsearch-specific improvements

 * https://hibernate.atlassian.net/browse/HSEARCH-2453[HSEARCH-2453]: Elasticsearch authentication is now fully implemented: there are dedicated `username` and `password` properties so that you don't need to embed the credentials in the URL anymore.
 * https://hibernate.atlassian.net/browse/HSEARCH-2593[HSEARCH-2593]: when using automatic node discovery on Elasticsearch, a scheme (HTTP or HTTPS) cannot be detected automatically for newly discovered nodes; by default it is HTTP. You can now customize this to use HTTPS instead: just add `hibernate.search.default.elasticsearch.discovery.default_scheme https` to your configuration.
 * https://hibernate.atlassian.net/browse/HSEARCH-2590[HSEARCH-2590]: queries using pagination could allocate too much memory in certain circumstances; this is now fixed.

== What's new on 5.6?

5.6.1.Final contains exclusively backported fixes from 5.7. You can see a full list of changes since 5.6.0.Final in https://hibernate.atlassian.net/secure/ReleaseNote.jspa?projectId=10061&version=26102[the release notes].

== What's next?

We're now focusing on the next two big improvements: 

 * support for Elasticsearch 5 without losing support for Elasticsearch 2 (https://hibernate.atlassian.net/browse/HSEARCH-2434[HSEARCH-2434],
   https://hibernate.atlassian.net/browse/HSEARCH-2581[HSEARCH-2581]). This will be in a 5.8 release.
 * streamlining our APIs, in particular to better fit remote indexing services (like Elasticsearch),
   but also to support Lucene 6.
   Due to the breaking changes this requires, we will include these changes in a new major release,
   Hibernate Search 6.0.

== How to get these releases

All versions are available on Hibernate Search's http://hibernate.org/search/[web site].

Ideally use a tool to fetch it from Maven central; these are the coordinates:

====
[source, XML]
----
<dependency>
   <groupId>org.hibernate</groupId>
   <artifactId>hibernate-search-orm</artifactId>
   <version>5.7.0.Final</version>
</dependency>
----
====

To use the experimental Elasticsearch integration you'll also need:

====
[source, XML]
----
<dependency>
   <groupId>org.hibernate</groupId>
   <artifactId>hibernate-search-elasticsearch</artifactId>
   <version>5.7.0.Final</version>
</dependency>
----
====

Downloads from https://sourceforge.net/projects/hibernate/files/hibernate-search/[Sourceforge] are available as well.

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://forum.hibernate.org/viewforum.php?f=9[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)

