= Hibernate Search 5.8.1.Final was just released
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
---

We just published 5.8.1.Final, a maintenance release for the 5.8 branch.
This release brings several Elasticsearch-related bug fixes.


== What's new?

Here are the most notable changes since Hibernate Search 5.8.0.Final:

 * https://hibernate.atlassian.net/browse/HSEARCH-2883[HSEARCH-2883]:
   Requests to Elasticsearch clusters with URL-based access control
   used to fail because of a trailing slash. This is no longer the case.
 * https://hibernate.atlassian.net/browse/HSEARCH-2886[HSEARCH-2886]:
   In certain circumstances, Elasticsearch requests containing 3 or 4-byte unicode characters
   could fail. These encoding issues have been resolved.

For a full list of changes since 5.8.0.Final,
please see https://hibernate.atlassian.net/issues/?jql=project=10061+AND+fixVersion=26101[the release notes].

== How to get these releases

All the necessary information is available (and updated regularly)
on https://hibernate.org/search/releases/5.8/#get-it[hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://forum.hibernate.org/viewforum.php?f=9[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
