= Third maintenance release for Hibernate Search 5.10
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
---

While we are still working on Hibernate Search 6 to get it ready for an Alpha,
things are relatively quiet on the Search 5 side.
However, we did not forget about it: we just published Hibernate Search version 5.10.3.Final,
the third maintenance release of Hibernate Search 5.10.
This release upgrades Hibernate Search to Hibernate ORM 5.3.3.Final, and adds a few minor improvements.

== What's new?

* https://hibernate.atlassian.net/browse/HSEARCH-3234[HSEARCH-3234]
and https://hibernate.atlassian.net/browse/HSEARCH-3210[HSEARCH-3210]:
Upgrade to ORM 5.3.3.Final and Hibernate Common Annotations 5.0.4.Final.
Hibernate ORM 5.3.3.Final includes quite a few bug fixes and improvements,
so be sure to http://in.relation.to/2018/07/24/hibernate-orm-533-final-out/[check it out]!
* https://hibernate.atlassian.net/browse/HSEARCH-3233[HSEARCH-3233]:
Overriding an analyzer in the QueryBuilder with an unknown analyzer should now lead to a proper SearchException.
* https://hibernate.atlassian.net/browse/HSEARCH-3228[HSEARCH-3228]:
The Elasticsearch integration now uses Gson 2.8.5, thanks to Leandro Freitas.
* https://hibernate.atlassian.net/browse/HSEARCH-3215[HSEARCH-3215] and https://hibernate.atlassian.net/browse/HSEARCH-3216[HSEARCH-3216]:
A few typos in the documentation were fixed, thanks to José Santos.

The other changes are mainly related to our build process, working toward testing Hibernate Search on JDK11.

For a full list of changes since the previous releases,
please see the https://hibernate.atlassian.net/issues/?jql=project=10061+AND+fixVersion=31686[release notes].

== How to get this release

All details are available and up to date on https://hibernate.org/search/releases/5.10/#get-it[the dedicated page on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
