= Hibernate Search 5.10.0.Beta2 is out!
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
---

We just published 5.10.0.Beta2, the second beta release for the 5.10 branch.
This release mainly includes an upgrade to WildFly 12 for the JBoss modules,
but it also adds a few bugfixes and improvements: see below!

== What's new?

Here are some notable changes since Hibernate Search 5.10.0.Beta1:

* https://hibernate.atlassian.net/browse/HSEARCH-3022[HSEARCH-3022]:
Hibernate Search's JBoss modules now target WildFly 12 and are tested against it instead of WildFly 11.
* https://hibernate.atlassian.net/browse/HSEARCH-2598[HSEARCH-2598]:
The JGroups backend now integrates with JGroups 4 and is no longer compatible with JGroups 3.
* https://hibernate.atlassian.net/browse/HSEARCH-3030[HSEARCH-3030]:
We moved the JGroups backend's JBoss modules out of the engine feature pack to
https://docs.jboss.org/hibernate/search/5.10/reference/en-US/html_single/#_jgroups_feature_pack[a dedicated feature pack].
* https://hibernate.atlassian.net/browse/HSEARCH-3026[HSEARCH-3026]:
If your Elasticsearch cluster is accessed through a URL with a non-root path,
you can now use `hibernate.search.default.elasticsearch.path_prefix` to tell Hibernate Search about that path.
* https://hibernate.atlassian.net/browse/HSEARCH-3039[HSEARCH-3039]:
We removed the ability to analyze document identifiers from Search a few versions ago,
but some parts of Hibernate Search still performed analysis on document identifiers in some cases,
in particular when querying them and when embedding a document ID using `@IndexedEmbedded`.
This has been fixed: Hibernate Search now consistently skips analysis on document identifiers.
* https://hibernate.atlassian.net/browse/HSEARCH-3021[HSEARCH-3021]:
The integration to dependency injection frameworks is now
https://docs.jboss.org/hibernate/search/5.10/reference/en-US/html_single/#section-bridge-dependency-injection[properly documented].

For a full list of changes since 5.10.0.Beta1,
please see https://hibernate.atlassian.net/secure/ReleaseNote.jspa?projectId=10061&version=31627[the release notes].

== Next

We are currently still waiting for Hibernate ORM 5.3.0.Final to be released.
You can expect a CR1 of Hibernate Search 5.10 soon after the ORM 5.3.0.Final release.

== How to get this release

All details are available and up to date on https://hibernate.org/search/releases/5.10/#get-it[the dedicated page on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
