= Maintenance release for Hibernate Search 5.10
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
---

We just published Hibernate Search 5.10.5.Final, a bugfix release for the 5.10 branch.

+++<!-- more -->+++

== What's new?

* https://hibernate.atlassian.net//browse/HSEARCH-3407[HSEARCH-3407]:
When using the Elasticsearch integration, multi-valued boolean fields used to only take the very first value into account.
This is no longer the case, all values are properly indexed.

The other changes are mainly related to our build process.

For a full list of changes since the previous releases,
please see the https://hibernate.atlassian.net/secure/ReleaseNote.jspa?projectId=10061&version=31717[release notes].

== How to get these releases

All details are available and up to date on the http://hibernate.org/search/releases/5.10/#get-it[dedicated pages on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
