= Hibernate Search 5.9.0.CR1 was just released
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
---

We just published 5.9.0.CR1, with bugfixes and improvements over
http://in.relation.to/2017/11/27/hibernate-search-5-9-0-Beta1/[5.9.0.Beta1].

Version 5.9.0.CR1 is the last opportunity for the community to test it and report bugs before the release.

== What's new?

Here are the most notable changes since Hibernate Search 5.9.0.Beta1:

* https://hibernate.atlassian.net/browse/HSEARCH-1885[HSEARCH-1885]:
Custom bridges with specific dependencies such as Tika bridges
can now be used in a modular environment such as WildFly.
* https://hibernate.atlassian.net/browse/HSEARCH-2955[HSEARCH-2955]:
Faceting queries will no longer fail when the index is empty
or only contains document without any value in the faceting field.
* https://hibernate.atlassian.net/browse/HSEARCH-2983[HSEARCH-2983]:
Boost is now consistently taken into account when building numeric or null encoding queries with the DSL.
* https://hibernate.atlassian.net/browse/HSEARCH-2191[HSEARCH-2191]:
The Hibernate Search JBoss Modules, for use in WildFly or JBoss EAP,
are now distributed as Wildfly feature packs, which makes provisioning
a WildFly server with an upgraded Hibernate Search version easier than ever.
The feature packs can also be consumed using http://wildfly-swarm.io/[WildFly Swarm].
+
Also, the modules are now distributed as *multiple* feature packs,
which means for example that you won't need to add the Elasticsearch clients
to your server if you only use Lucene.
+
See https://docs.jboss.org/hibernate/search/5.9/reference/en-US/html_single/#search-configuration-deploy-on-wildfly[the documentation]
for more information on the available feature packs and how to consume them.

For a full list of changes since 5.9.0.Beta1,
please see https://hibernate.atlassian.net/secure/ReleaseNote.jspa?projectId=10061&version=31617[the release notes].

== How to get this release

All the necessary information is available (and updated regularly)
on http://hibernate.org/search/releases/5.9/#get-it[hibernate.org].

== Next

We are still working on Hibernate Search 6,
but before that we will slip in a Hibernate Search 5.10 release.

5.10 will mainly bring support for Hibernate ORM 5.3 and JPA 2.2.
These releases could be of interest to CDI or Spring DI users in particular,
since they will bring support for injecting CDI or Spring beans into Hibernate Search,
in particular field bridges.
CDI support is already working on our development branches,
and Spring support will probably come as soon as the Spring team integrates Hibernate ORM 5.3.

Check out the http://hibernate.org/search/roadmap/#hibernate-search-5-10[roadmap] for more information,
and stay tuned!

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://forum.hibernate.org/viewforum.php?f=9[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
