= Hibernate Search 5.11.0.CR1 is out!
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Lucene", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
---

We just published 5.11.0.CR1, the first candidate release for the 5.11 branch.
This release mainly includes an upgrade to Hibernate ORM 5.4.0.CR2.

+++<!-- more -->+++

== What's new

Here are some notable changes since Hibernate Search 5.10.5.Final:

* https://hibernate.atlassian.net/browse/HSEARCH-3410[HSEARCH-3410]:
Hibernate Search's ORM integration now depends on Hibernate ORM 5.4.0.CR2.
* https://hibernate.atlassian.net/browse/HSEARCH-3420[HSEARCH-3420]:
Hibernate Search is now systematically built and tested against JDK11,
meaning it will work out-of-the box on JDK11.
* https://hibernate.atlassian.net/browse/HSEARCH-3364[HSEARCH-3364]:
The WildFly feature packs now target WildFly 14.

For a full list of changes since 5.10.5.Final,
please see https://hibernate.atlassian.net/secure/ReleaseNote.jspa?projectId=10061&version=31731[the release notes].

== How to get this release

All details are available and up to date on http://hibernate.org/search/releases/5.11/#get-it[the dedicated page on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
