= Hibernate Search 5.11.6.Final released
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Lucene", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
:hsearch-doc-url-prefix: https://docs.jboss.org/hibernate/search/5.11/reference/en-US/html_single/
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse
:hsearch-version-family: 5.11
:hsearch-jira-project-id: 10061
:hsearch-jira-version-id: 31830
---

We just published a bugfix release for Hibernate Search:
5.11.6.Final.

This release mainly upgrades Hibernate Search to the latest compatible Hibernate ORM version
and fixes one issue with Spring Boot 2.4.0 / Spring Framework 5.3.

== What's new

* link:{hsearch-jira-url-prefix}/HSEARCH-4085[HSEARCH-4085]:
Upgrade to Hibernate Annotations 5.1.2.Final
* link:{hsearch-jira-url-prefix}/HSEARCH-4087[HSEARCH-4087]:
Upgrade to Hibernate ORM 5.4.23.Final
* link:{hsearch-jira-url-prefix}/HSEARCH-4107[HSEARCH-4107]:
Creating a `FullTextSession` from an `EntityManager` created by Spring Boot 2.4.0 / Spring Framework 5.3 used to fail with a `ClassCastException`.
This is no longer the case.
More information https://github.com/spring-projects/spring-framework/issues/26090[here].

For a full list of changes since the previous release,
please see the link:https://hibernate.atlassian.net/issues/?jql=project={hsearch-jira-project-id}+AND+fixVersion={hsearch-jira-version-id}[release notes].

== How to get these releases

All details are available and up to date on the
link:https://hibernate.org/search/releases/{hsearch-version-family}/#get-it[dedicated page on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
