= Hibernate Search 6.1.0.Beta2 released
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Lucene", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
:hsearch-doc-url-prefix: https://docs.jboss.org/hibernate/search/6.1/reference/en-US/html_single/
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse
:hsearch-version-family: 6.1
:hsearch-jira-project-id: 10061
:hsearch-jira-version-id: 32005
---

We just published Hibernate Search 6.1.0.Beta2,
another beta release of the next minor version of Hibernate Search.

Among the main changes:
persistence and management of aborted events with the "outbox-polling" coordination,
definition of Lucene analyzers without referring to Lucene classes,
Elasticsearch 7.16 compatibility,
OpenSearch 1.2 compatibility,
and more.

== What's new

[NOTE]
====
Hibernate Search 6.1 is still in development:
some features are still incomplete or may change in a backward-incompatible way.
====

=== Dependency upgrades

[[orm-version]]Hibernate ORM (link:{hsearch-jira-url-prefix}/HSEARCH-4400[HSEARCH-4400])::
Hibernate Search 6.1 now relies on Hibernate ORM 5.6.2.
[[lucene-version]]Lucene (link:{hsearch-jira-url-prefix}/HSEARCH-4420[HSEARCH-4420])::
The Lucene backend now uses Lucene 8.11.1.
[[elasticsearch-version]]Elasticsearch (link:{hsearch-jira-url-prefix}/HSEARCH-4340[HSEARCH-4340])::
The Elasticsearch backend is now tested to be compatible with Elasticsearch servers in version 5.6, 6.8, 7.10 or 7.16.
[[opensearch-version]]OpenSearch (link:{hsearch-jira-url-prefix}/HSEARCH-4412[HSEARCH-4412])::
The Elasticsearch backend is now tested to be compatible with OpenSearch servers in version 1.0 or 1.2.
[[others-version]]
Others::
* link:{hsearch-jira-url-prefix}/HSEARCH-4422[HSEARCH-4422]: Upgrade to Jackson 2.13.1
* link:{hsearch-jira-url-prefix}/HSEARCH-4410[HSEARCH-4410]: Upgrade to Elasticsearch **client** 7.16.2

[[log4j]]
=== Log4j upgrade

As mentioned https://in.relation.to/2021/12/16/log4j-cve/[here],
Hibernate projects do not use Log4j at runtime and thus are not affected
by the various vulnerabilities discovered in Log4j 2 recently.

However, Hibernate Search does use Log4j during its own build, when executing tests,
which is why we had to link:{hsearch-jira-url-prefix}/HSEARCH-4421[update our test dependency to Log4j 2.17.1] anyway.

Incidentally, this might help with some security sniffers that do not correctly
understand the difference between runtime dependencies and test dependencies,
leading to Hibernate Search being (falsely) reported as affected by the Log4j vulnerabilities.

[[async-indexing-aborted-event-management]]
=== Persistence and management of aborted events with the "outbox-polling" coordination

As of link:{hsearch-jira-url-prefix}/HSEARCH-4283[HSEARCH-4283],
the link:{hsearch-doc-url-prefix}#coordination-database-polling[`outbox-polling` coordination strategy]
now persists events whose processing failed 3 times, but with the "aborted" status that prevents their re-processing.

link:{hsearch-doc-url-prefix}#_aborted_events[Several API methods are available] to count aborted events, clear them or request their re-processing.

[[lucene-analyzer-definition-using-names]]
=== Lucene analyzer definition using tokenizer/filter names

As of link:{hsearch-jira-url-prefix}/HSEARCH-4404[HSEARCH-4404],
a `LuceneAnalysisConfigurer` can be implemented without referring to Lucene classes at all,
link:{hsearch-doc-url-prefix}#backend-lucene-analysis-analyzers-component-by-factory-name[referring to tokenizers and filters using their name]
instead.

This is useful in some modular environments where the application might have access to Hibernate Search classes,
but not to Lucene classes.

[[breaking-changes]]
=== Breaking changes

No breaking changes compared to version 6.1.0.Beta1.

[[other-changes]]
=== Other improvements and bug fixes

* link:{hsearch-jira-url-prefix}/HSEARCH-4423[HSEARCH-4423]:
Hibernate Search will no longer incorrectly detect a cycle and fail to process `@IndexingDependency(derivedFrom = ...)`
when the path to source properties contains two properties with the same name, but on different types.
Thanks to fraf for https://discourse.hibernate.org/t/cyclic-dependency-wrong-error-report/5936?u=yrodiere[reporting this]!
* link:{hsearch-jira-url-prefix}/HSEARCH-4401[HSEARCH-4401]:
The Lucene backend now correctly raises an error when running a search query where offset + limit is higher than `Integer.MAX_VALUE`,
instead of incorrectly ignoring the limit.
* link:{hsearch-jira-url-prefix}/HSEARCH-4398[HSEARCH-4398]:
Hibernate Search no longer has an unnecessary transitive dependency to `org.apache.lucene:lucene-sandbox`.
* link:{hsearch-jira-url-prefix}/HSEARCH-4391[HSEARCH-4391]:
Fixed images not being displayed in the documentation.
* link:{hsearch-jira-url-prefix}/HSEARCH-4408[HSEARCH-4408]:
Fixed syntax highlighting for code example not working anymore in the documentation.

And more. For a full list of changes since the previous releases,
please see the link:https://hibernate.atlassian.net/issues/?jql=project={hsearch-jira-project-id}+AND+fixVersion={hsearch-jira-version-id}[release notes].

== How to get this release

All details are available and up to date on the
link:https://hibernate.org/search/releases/{hsearch-version-family}/#get-it[dedicated page on hibernate.org].

== Getting started, migrating

For new applications,
refer to the link:{hsearch-doc-url-prefix}#getting-started[getting started guide].

For existing applications, Hibernate Search {hsearch-version-family} is a drop-in replacement for 6.0,
assuming you also upgrade the dependencies.
Information about deprecated configuration and API
is included in the https://docs.jboss.org/hibernate/search/{hsearch-version-family}/migration/html_single/[migration guide].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
