= Hibernate Search 6.1.0.CR1 released
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Lucene", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
:hsearch-doc-url-prefix: https://docs.jboss.org/hibernate/search/6.1/reference/en-US/html_single/
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse
:hsearch-version-family: 6.1
:hsearch-jira-project-id: 10061
:hsearch-jira-version-id: 32016
---

We just published Hibernate Search 6.1.0.CR1,
the first release candidate of Hibernate Search 6.1.

Among the main changes since Beta2:
better defaults and optional operators for the regexp predicate,
additional Maven artifacts compatible with Hibernate ORM 6,
and more.

== What's new

[NOTE]
====
For a summary of all new features and improvements since 6.0,
head to https://hibernate.org/search/releases/6.1/#whats-new[the dedicated page on hibernate.org].
====

=== Dependency upgrades

[[orm-version]]Hibernate ORM (link:{hsearch-jira-url-prefix}/HSEARCH-4436[HSEARCH-4436])::
Hibernate Search 6.1 now depends on Hibernate ORM 5.6.3.
[[others-version]]
Others::
* link:{hsearch-jira-url-prefix}/HSEARCH-4446[HSEARCH-4446]:
  Upgrade to Elasticsearch **client** 7.16.3
* link:{hsearch-jira-url-prefix}/HSEARCH-4448[HSEARCH-4448]:
  Upgrade to JBoss logging 3.4.3.Final
* link:{hsearch-jira-url-prefix}/HSEARCH-4449[HSEARCH-4449]:
  Upgrade to slf4j 1.7.33 (only affects artifacts related to the AWS integration)

[[regexp-operators]]
=== Better defaults and optional operators for the regexp predicate

The regexp predicate, introduced in Hibernate Search 6.1,
now allows selecting optional operators explicitly using flags (link:{hsearch-jira-url-prefix}/HSEARCH-4362[HSEARCH-4362]).

These operators are no longer enabled by default,
which should avoid problems such as the regexp `.*@jboss.org` matching `something@lists.jboss.org`
because `@` is an optional operator matching any string...

For more information about optional operators,
head to link:{hsearch-doc-url-prefix}#search-dsl-predicate-regexp-flags[this section of the reference documentation].

[[orm6]]
=== Hibernate ORM 6

Thanks to link:{hsearch-jira-url-prefix}/HSEARCH-3277[HSEARCH-3277],
beside the traditional artifacts targeting Java EE (JPA, CDI, ...) and Hibernate ORM 5.x,
Hibernate Search now provides link:{hsearch-doc-url-prefix}#other-integrations-orm6[alternative, experimental artifacts that target Hibernate ORM 6.0.0.Beta3 and Jakarta EE 9.1]
(Jakarta Persistence 3, Jakarta CDI 3).

These artifacts have their artifact ID suffixed with "-orm6".

In Hibernate Search 6.1.0.CR1, this includes the following ORM 6 artifacts:

* `org.hibernate.search:hibernate-search-mapper-orm-orm6:6.1.0.Beta1`
* `org.hibernate.search:hibernate-search-mapper-orm-coordination-outbox-polling-orm6:6.1.0.Beta1`
* `org.hibernate.search:hibernate-search-mapper-orm-batch-jsr352-core-orm6:6.1.0.Beta1`
* `org.hibernate.search:hibernate-search-mapper-orm-batch-jsr352-jberet-orm6:6.1.0.Beta1`
* `org.hibernate.search:hibernate-search-v5migrationhelper-orm-orm6:6.1.0.Beta1`

Note that in order to switch to Hibernate ORM 6 and Jakarta EE, you will need to switch to these artifacts, but also:

* Use Hibernate ORM 6 instead of 5.x; this involves
https://in.relation.to/2018/12/06/hibernate-orm-600-alpha1-out/#artifacts[changing the group ID for Hibernate ORM artifacts], not just the version:
`org.hibernate` becomes `org.hibernate.orm`.
* Use Jakarta EE-specific artifacts for your other Java EE dependencies.
* Convert your code to Jakarta EE APIs. This should be rather straightforward:
simply replace `import javax.persistence.<something>` with `import jakarta.persistence.<something>` everywhere in your code
(same with `javax.enterprise`, `javax.transaction`, etc.).
* Find a new version of your framework or application server that supports Jakarta EE.
This might be hard to come by, as Jakarta EE is still young,
but some application servers already provide at least a preview.

[[breaking-changes]]
=== Breaking changes

* link:{hsearch-jira-url-prefix}/HSEARCH-4362[HSEARCH-4362], link:{hsearch-jira-url-prefix}/HSEARCH-4443[HSEARCH-4443]:
The `regexp` predicate link:{hsearch-doc-url-prefix}#search-dsl-predicate-regexp-flags[no longer enables optional operators by default].
To restore the previous behavior, call `.flags( EnumSet.allOf( RegexpQueryFlag.class ) )` when setting the predicate options.
* link:{hsearch-jira-url-prefix}/HSEARCH-4425[HSEARCH-4425], link:{hsearch-jira-url-prefix}/HSEARCH-4443[HSEARCH-4443]:
The structure of the tables holding the outbox events and the list of connected agents has changed.
You will need to drop your current outbox event and agent tables
and link:{hsearch-doc-url-prefix}#coordination-database-polling-schema[re-create the necessary tables].

[[other-changes]]
=== Other improvements and bug fixes

* link:{hsearch-jira-url-prefix}/HSEARCH-4425[HSEARCH-4425]:
Mark non-nullable properties as such in OutboxPollingOutboxEventAdditionalJaxbMappingProducer
* link:{hsearch-jira-url-prefix}/HSEARCH-4443[HSEARCH-4443]:
Enum properties in outbox-polling entities (agent, outboxevent) have a weird type in database
* link:{hsearch-jira-url-prefix}/HSEARCH-4438[HSEARCH-4438]:
More detailed error message for syntax errors in custom mapping/settings file

And more. For a full list of changes since the previous releases,
please see the link:https://hibernate.atlassian.net/issues/?jql=project={hsearch-jira-project-id}+AND+fixVersion={hsearch-jira-version-id}[release notes].

== How to get this release

All details are available and up to date on the
link:https://hibernate.org/search/releases/{hsearch-version-family}/#get-it[dedicated page on hibernate.org].

== Getting started, migrating

For new applications,
refer to the link:{hsearch-doc-url-prefix}#getting-started[getting started guide].

For existing applications, Hibernate Search {hsearch-version-family} is a drop-in replacement for 6.0,
assuming you also upgrade the dependencies.
Information about deprecated configuration and API
is included in the https://docs.jboss.org/hibernate/search/{hsearch-version-family}/migration/html_single/[migration guide].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
