= Hibernate Search 6.1.4.Final released
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Lucene", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
:hsearch-doc-url-prefix: https://docs.jboss.org/hibernate/search/6.1/reference/en-US/html_single/
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse
:hsearch-version-family: 6.1
:hsearch-jira-project-id: 10061
:hsearch-jira-version-id: 32057
---

We just published a maintenance release for Hibernate Search:
6.1.4.Final.

This releases mainly upgrades to Hibernate ORM 6.0.0.Final for -orm6 artifacts,
upgrades to the latest version of Jakarta dependencies for -orm6/-jakarta artifacts,
and fixes a few bugs.

== What's new

* link:{hsearch-jira-url-prefix}/HSEARCH-4523[HSEARCH-4523]:
Upgrade -orm6 artifacts to Hibernate ORM 6.0.0.Final
* link:{hsearch-jira-url-prefix}/HSEARCH-4528[HSEARCH-4528]:
Upgrade to latest version of Jakarta dependencies for -orm6/-jakarta artifacts
* link:{hsearch-jira-url-prefix}/HSEARCH-4529[HSEARCH-4529]:
Upgrade to Hibernate Commons Annotations 6.0.0.Final for -orm6 artifacts
* link:{hsearch-jira-url-prefix}/HSEARCH-4513[HSEARCH-4513]:
Using a `SearchSort` instance in multiple queries with the Lucene backend no longer has side effects leading to unexpected results.
* link:{hsearch-jira-url-prefix}/HSEARCH-4531[HSEARCH-4531]:
Sorting on a dynamic field that has never been indexed no longer fails with the Elasticsearch backend.

For a full list of changes since the previous release,
see the link:https://hibernate.atlassian.net/secure/ReleaseNote.jspa?projectId={hsearch-jira-project-id}&version={hsearch-jira-version-id}[release notes].

== How to get this release

All details are available and up to date on the
link:https://hibernate.org/search/releases/{hsearch-version-family}/#get-it[dedicated page on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
