= Hibernate Search 6.2.0.Alpha2 is out
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Lucene", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
:hsearch-doc-url-prefix: https://docs.jboss.org/hibernate/search/6.2/reference/en-US/html_single/
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse
:hsearch-version-family: 6.2
:hsearch-jira-project-id: 10061
:hsearch-jira-version-id: 32091
---

We just published Hibernate Search 6.2.0.Alpha2,
an alpha release of the next minor version of Hibernate Search.

This version brings simpler `and`/`or`/`not` predicates,
mass indexing for multiple tenants,
and a switch to UUIDs for identifiers in the `outbox-polling` coordination strategy.

6.2.0.Alpha2 also includes many bugfixes and improvements,
compatibility with Elasticsearch 8.6 and OpenSearch 2.5,
an upgrade of `-orm6` artifacts to Hibernate ORM 6.2.0.CR2,
and more.

== Thanks

Thanks to https://github.com/YannisBres[Yannis Bres] for https://github.com/hibernate/hibernate-search/pull/3152[his work on AND/OR predicates].

== What's new

[NOTE]
====
Hibernate Search 6.2 is still in development:
some features are still incomplete or may change in a backward-incompatible way.
====

=== Dependency upgrades

[[orm-version]]
Hibernate ORM (link:{hsearch-jira-url-prefix}/HSEARCH-4747[HSEARCH-4747]/link:{hsearch-jira-url-prefix}/HSEARCH-4791[HSEARCH-4791])::
Hibernate Search now depends on Hibernate ORM 5.6.14.Final,
or Hibernate ORM 6.2.0.CR2 for -orm6 artifacts.
[[elasticsearch-version]]
Elasticsearch (link:{hsearch-jira-url-prefix}/HSEARCH-4777[HSEARCH-4777])::
The Elasticsearch backend now works with Elasticsearch 8.6
as well as other versions that were already compatible.
[[opensearch-version]]
OpenSearch (link:{hsearch-jira-url-prefix}/HSEARCH-4790[HSEARCH-4790])::
The Elasticsearch backend now works with OpenSearch 2.5
as well as other versions that were already compatible.
[[others-version]]
Others::
* link:{hsearch-jira-url-prefix}/HSEARCH-4793[HSEARCH-4793]: Upgrade to Elasticsearch **client** 8.6.1
* link:{hsearch-jira-url-prefix}/HSEARCH-4659[HSEARCH-4659]: Upgrade to Avro 1.11.1
* link:{hsearch-jira-url-prefix}/HSEARCH-4660[HSEARCH-4660]: Upgrade to GSON 2.9.1
* link:{hsearch-jira-url-prefix}/HSEARCH-4661[HSEARCH-4661]: Upgrade to JBeret 1.4.8.Final
* link:{hsearch-jira-url-prefix}/HSEARCH-4697[HSEARCH-4697]: Upgrade to Jackson 2.13.4
* link:{hsearch-jira-url-prefix}/HSEARCH-4739[HSEARCH-4739]: Upgrade to jackson-databind 2.13.4.2
* link:{hsearch-jira-url-prefix}/HSEARCH-4694[HSEARCH-4694]: Compatibility with Jandex 3.0
* link:{hsearch-jira-url-prefix}/HSEARCH-4798[HSEARCH-4798]: Upgrade to AWS SDK 2.20.2

[[mapper-pojo-standalone]]
=== Standalone POJO Mapper

The Standalone POJO Mapper enables mapping arbitrary POJOs to indexes, even without Hibernate ORM.
See link:{hsearch-doc-url-prefix}#mapper-pojo-standalone[this section of the reference documentation]
for more information,
or link:{hsearch-doc-url-prefix}#mapper-pojo-standalone-getting-started[this getting started guide].

In this release, there were several improvements to the configuration of the Standalone POJO mapper:

* link:{hsearch-jira-url-prefix}/HSEARCH-4615[HSEARCH-4615]:
More configuration is set simply through configuration properties.
* link:{hsearch-jira-url-prefix}/HSEARCH-4620[HSEARCH-4620]:
Indexing plan synchronization is now configured through strategies,
just like with the ORM mapper.

[[mapping-projection]]
=== Mapping index content to custom types (projection constructors)

In a previous release, Hibernate Search 6.2 introduced the ability to define projections through the mapping of custom types (typically records),
by applying the `@ProjectionConstructor` annotation to those types or their constructor.
See link:{hsearch-doc-url-prefix}#mapping-projection[this section of the reference documentation]
for more information.

In this release, there were several improvements to the projection constructors:

* link:{hsearch-jira-url-prefix}/HSEARCH-4579[HSEARCH-4579]:
With the Standalone POJO Mapper, when searching on an entity type with no loading configured,
Hibernate Search will now attempt to use that entity type's projection constructor if it exists.
* link:{hsearch-jira-url-prefix}/HSEARCH-4591[HSEARCH-4591]:
Object projections are now allowed on single-valued, flattened object fields with the Lucene backend.
* link:{hsearch-jira-url-prefix}/HSEARCH-4669[HSEARCH-4669]:
Hibernate Search will provide more information when a projection constructor cannot be applied to an index.
* link:{hsearch-jira-url-prefix}/HSEARCH-4673[HSEARCH-4673]:
The `-parameters` compiler flag is no longer necessary when using the default constructor of records as projection constructor.

[[mapping-improvements]]
=== Mapping improvements

* link:{hsearch-jira-url-prefix}/HSEARCH-4714[HSEARCH-4714]:
Property names in the mapping, e.g. @IndexingDependency(derivedFrom = ...),
will now be checked early to provide a clear error message in case of incorrect syntax.
* link:{hsearch-jira-url-prefix}/HSEARCH-4782[HSEARCH-4782]:
Hibernate Search will now infer a default decimal scale automatically for identifiers of Hibernate ORM entities;
previously it was only inferred for non-identifier properties.

[[search-dsl-improvements]]
=== Search DSL improvements

[[predicate-and-or-not]]
Simpler boolean operators with the link:{hsearch-doc-url-prefix}#search-dsl-predicate-and[`and`]/link:{hsearch-doc-url-prefix}#search-dsl-predicate-or[`or`]/link:{hsearch-doc-url-prefix}#search-dsl-predicate-not[`not`] predicates (link:{hsearch-jira-url-prefix}/HSEARCH-4601[HSEARCH-4601]/link:{hsearch-jira-url-prefix}/HSEARCH-4645[HSEARCH-4645])::
For simpler use cases, you can now avoid the rather complex link:{hsearch-doc-url-prefix}#search-dsl-predicate-boolean[`bool` predicate]
and use the new link:{hsearch-doc-url-prefix}#search-dsl-predicate-and[`and`]/link:{hsearch-doc-url-prefix}#search-dsl-predicate-or[`or`]/link:{hsearch-doc-url-prefix}#search-dsl-predicate-not[`not`]
predicates instead:
+
[source, JAVA, indent=0]
----
List<Book> hits = searchSession.search( Book.class )
        .where( f -> f.and(
                        f.match().field( "title" )
                                .matching( "robot" ),
                        f.match().field( "description" )
                                .matching( "crime" )
        ) )
        .fetchHits( 20 );
----
+
[source, JAVA, indent=0]
----
List<Book> hits = searchSession.search( Book.class )
        .where( f -> f.or(
                        f.match().field( "title" )
                                .matching( "robot" ),
                        f.match().field( "description" )
                                .matching( "investigation" )
        ) )
        .fetchHits( 20 );
----
+
[source, JAVA, indent=0]
----
List<Book> hits = searchSession.search( Book.class )
        .where( f -> f.not(
                f.match()
                        .field( "genre" )
                        .matching( Genre.SCIENCE_FICTION )
        ) )
        .fetchHits( 20 );
----
[[predicate-bool-new-syntax-root]]
Simpler `and` predicate for link:{hsearch-doc-url-prefix}#search-dsl-predicate-boolean-lambda[`where( (f, b) -> ... )`] (link:{hsearch-jira-url-prefix}/HSEARCH-4676[HSEARCH-4676])::
Instead of a `bool` predicate as in 6.2.0.Alpha1, `where( (f, b) -> ... )` now provides a simpler <<predicate-and-or-not,`and` predicate>>:
+
[source, JAVA, indent=0]
----
MySearchParameters searchParameters = getSearchParameters();
List<Book> hits = searchSession.search( Book.class )
        .where( (f, root) -> {
            root.add( f.matchAll() );
            if ( searchParameters.getGenreFilter() != null ) {
                root.add( f.match().field( "genre" )
                        .matching( searchParameters.getGenreFilter() ) );
            }
            if ( searchParameters.getFullTextFilter() != null ) {
                root.add( f.match().fields( "title", "description" )
                        .matching( searchParameters.getFullTextFilter() ) );
            }
            if ( searchParameters.getPageCountMaxFilter() != null ) {
                root.add( f.range().field( "pageCount" )
                        .atMost( searchParameters.getPageCountMaxFilter() ) );
            }
        } )
        .fetchHits( 20 );
----
[[predicate-nested-new-syntax]]
Simpler `and` predicate for the link:{hsearch-doc-url-prefix}#search-dsl-predicate-nested[`nested` predicate] (link:{hsearch-jira-url-prefix}/HSEARCH-4676[HSEARCH-4676])::
Instead of a `bool` predicate as in as in 6.2.0.Alpha1, `f.nested( ... )` now provides a simpler <<predicate-and-or-not,`and` predicate>>:
+
[source, JAVA, indent=0]
----
List<Book> hits = searchSession.search( Book.class )
        .where( f -> f.nested( "authors" )
                .add( f.match().field( "authors.firstName" )
                        .matching( "isaac" ) )
                .add( f.match().field( "authors.lastName" )
                        .matching( "asimov" ) ) )
        .fetchHits( 20 );
----

[[mass-indexing-improvements]]
=== Mass indexing improvements

Mass indexing multiple tenants (link:{hsearch-jira-url-prefix}/HSEARCH-4321[HSEARCH-4321])::
In multi-tenant applications, mass indexing can now handle multiple tenants at once,
provided you don't pass any tenant identifier when creating the mass indexer,
and you provided a list of tenants in the Hibernate Search configuration.
See link:{hsearch-doc-url-prefix}#indexing-massindexer-multitenancy[this section of the reference documentation]
for more information.
Setting up thread locals during mass indexing (link:{hsearch-jira-url-prefix}/HSEARCH-1809[HSEARCH-1809])::
The mass indexer now has a concept of "mass indexing environment",
allowing for instance to set up custom thread locals in mass indexing threads.
See the `environment` parameter in link:{hsearch-doc-url-prefix}#indexing-massindexer-parameters[this section of the reference documentation]
for more information.
Better exception handling (link:{hsearch-jira-url-prefix}/HSEARCH-4541[HSEARCH-4541])::
Exceptions thrown by Hibernate ORM during mass indexing
are now passed to the failure handler as every other exception, instead of aborting the whole mass indexing.
Smarter defaults for parameters (link:{hsearch-jira-url-prefix}/HSEARCH-4612[HSEARCH-4612])::
`purgeAllOnStart` is now disabled by default in the mass indexer when `dropAndCreateSchemaOnStart` is enabled.

[[outbox-polling-improvements]]
=== `outbox-polling` coordination improvements

Outbox events and agents now use UUIDs for their identifiers (link:{hsearch-jira-url-prefix}/HSEARCH-4678[HSEARCH-4678]/link:{hsearch-jira-url-prefix}/HSEARCH-4748[HSEARCH-4748])::
The primary key of the relevant tables are now using UUIDs instead of longs,
to avoid reliance on sequences that were slowing down event processing on some databases.
The migration guide includes migration scripts for the necessary database schema changes.
See link:{hsearch-doc-url-prefix}#_custom_schematable_nameetc[this section of the reference documentation]
for more information.

[[other-changes]]
=== Other improvements and bug fixes

* link:{hsearch-jira-url-prefix}/HSEARCH-4618[HSEARCH-4618]:
`BooleanPredicateOptionsCollector`/`SimpleBooleanPredicateClausesCollector` now expose a `hasClause()` method.
* link:{hsearch-jira-url-prefix}/HSEARCH-4294[HSEARCH-4294]:
The Search DSL now allows targeting "implicit" Elasticsearch fields such as `_index`.
* link:{hsearch-jira-url-prefix}/HSEARCH-4644[HSEARCH-4644]:
Hibernate Search is now tested regularly against CockroachDB.
* link:{hsearch-jira-url-prefix}/HSEARCH-4679[HSEARCH-4679]:
Hibernate Search will now automatically simplify boolean predicates with a single clause.
* link:{hsearch-jira-url-prefix}/HSEARCH-4305[HSEARCH-4305], link:{hsearch-jira-url-prefix}/HSEARCH-4708[HSEARCH-4708]:
Automatic reindexing will no longer be skipped when changing a property annotated with `@OneToOne(mappedBy = ...) @IndexedEmbedded`
* link:{hsearch-jira-url-prefix}/HSEARCH-4727[HSEARCH-4727]:
With `outbox-polling` coordination and when using DB2,
`OutboxEvent` table used to be created with a `payload` column with the wrong type `blob(255)`,
making it almost unusable. It is no longer the case.
* link:{hsearch-jira-url-prefix}/HSEARCH-4634[HSEARCH-4634], link:{hsearch-jira-url-prefix}/HSEARCH-4647[HSEARCH-4647]:
`outbox-polling` coordination now works with CockroachDB.
* link:{hsearch-jira-url-prefix}/HSEARCH-4652[HSEARCH-4652]:
Schema validation with the Elasticsearch backend will no longer fail
when setting `searchAnalyzer` to the same value as `analyzer` on a full-text field.
* link:{hsearch-jira-url-prefix}/HSEARCH-4654[HSEARCH-4654]:
Hibernate Search will no longer deadlock when experiencing a large number of concurrent failures
during startup or schema validation.
* link:{hsearch-jira-url-prefix}/HSEARCH-4701[HSEARCH-4701]:
When running Hibernate Search as a Java module (in the modulepath),
Elasticsearch schema management will no longer lead to exceptions
caused by missing inter-module dependencies.
* link:{hsearch-jira-url-prefix}/HSEARCH-4703[HSEARCH-4703]:
Fixed missing entries in the Java module descriptor of `hibernate-search-mapper-orm-coordination-outbox-polling`
leading to errors when running Hibernate Search in the modulepath.
* link:{hsearch-jira-url-prefix}/HSEARCH-4724[HSEARCH-4724]:
Classpath scanning (for projection constructors in particular)
no longer ignores classes within Spring Boot's "repackaged" JARs.

And more. For a full list of changes since the previous releases,
please see the link:https://hibernate.atlassian.net/issues/?jql=project={hsearch-jira-project-id}+AND+fixVersion={hsearch-jira-version-id}[release notes].

== How to get this release

All details are available and up to date on the
link:https://hibernate.org/search/releases/{hsearch-version-family}/#get-it[dedicated page on hibernate.org].

== Getting started, migrating

For new applications,
refer to the getting started guide:

* link:{hsearch-doc-url-prefix}#mapper-orm-getting-started[here for the Hibernate ORM integration]
* link:{hsearch-doc-url-prefix}#mapper-pojo-standalone-getting-started[here for the Standalone POJO Mapper]

For existing applications, Hibernate Search {hsearch-version-family} is a drop-in replacement for 6.1,
assuming you also upgrade the dependencies.
Information about deprecated configuration and API
is included in the https://docs.jboss.org/hibernate/search/{hsearch-version-family}/migration/html_single/[migration guide].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
