= Hibernate Search 6.2.1.Final released
Yoann Rodière
:awestruct-tags: [ "Hibernate Search", "Lucene", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
:hsearch-doc-url-prefix: https://docs.jboss.org/hibernate/search/6.2/reference/en-US/html_single/
:hsearch-jira-url-prefix: https://hibernate.atlassian.net/browse
:hsearch-version-family: 6.2
:hsearch-jira-project-id: 10061
:hsearch-jira-version-id: 32172
---

We just published a maintenance release for Hibernate Search:
6.2.1.Final.

This release mainly upgrades to Hibernate ORM 6.2.7.Final for `-orm6` artifacts,
upgrades to Elasticsearch client 8.9.0,
adds compatibility with Elasticsearch 8.9 and OpenSearch 2.9,
and fixes several bugs.

== What's new

* link:{hsearch-jira-url-prefix}/HSEARCH-4744[HSEARCH-4744]:
Hibernate Search is now able to read Jandex indexes of repackaged Spring applications (uberjars),
providing the application runs on Java 13+.
* link:{hsearch-jira-url-prefix}/HSEARCH-4915[HSEARCH-4915]:
Search queries with partial failures (some successful shards, some failing)
can now trigger an exception if you set the configuration property
link:{hsearch-doc-url-prefix}#backend-elasticsearch-search-ignore-partial-shard-failure[`hibernate.search.backend.query.shard_failure.ignore`]
to `false`.
+
This will be the default behavior in Hibernate Search 7.
* link:{hsearch-jira-url-prefix}/HSEARCH-4903[HSEARCH-4903]:
Upgrade `-orm6` artifacts to Hibernate ORM 6.2.7.Final
* link:{hsearch-jira-url-prefix}/HSEARCH-4904[HSEARCH-4904]:
Upgrade to Elasticsearch client 8.9.0 and add compatibility with Elasticsearch 8.9.0
* link:{hsearch-jira-url-prefix}/HSEARCH-4905[HSEARCH-4905]:
Add compatibility with OpenSearch 2.9.0

For a full list of changes since the previous release,
see the link:https://hibernate.atlassian.net/issues/?jql=project={hsearch-jira-project-id}+AND+fixVersion={hsearch-jira-version-id}[release notes].

== How to get this release

All details are available and up to date on the
link:https://hibernate.org/search/releases/{hsearch-version-family}/#get-it[dedicated page on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-search[hibernate-search tag on Stackoverflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-search[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HSEARCH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
