= Hibernate ORM 5.0.8.Final
Gail Badner
:awestruct-tags: ["Hibernate ORM", "Releases"]
:awestruct-layout: blog-post

Hibernate ORM 5.0.8.Final has just been http://github.com/hibernate/hibernate-orm/releases/tag/5.0.8[tagged] and published.  

The complete list of changes can be found https://hibernate.atlassian.net/projects/HHH/versions/22250[here] (or https://hibernate.atlassian.net/issues/?jql=project=10031+AND+fixVersion=22250[here] for people without a Hibernate Jira account).

As of Hibernate ORM 5.0.8.Final, Oracle12cDialect has been changed to map byte[] and Byte[] to BLOB 
(https://hibernate.atlassian.net/browse/HHH-10345[HHH-10345])

Previous versions of Hibernate have mapped `byte[]` and `Byte[]` to Oracle's `LONG RAW` data type (via the JDBC
LONGVARBINARY type).  Oracle have deprecated the `LONG RAW` data type for many releases - possibly as far back
as 8i.  Therefore it was decided to start having Hibernate map `byte[]` and `Byte[]` to `BLOB` for Oracle.

However, in the interest of backwards compatibility and not breaking existing applications it was also decided to
limit this change to just the Oracle12cDialect.  So starting in 5.0.8, applications using Oracle12cDialect and
implicitly mapping `byte[]` and `Byte[]` values will start seeing those handled as `BLOB` data rather than `LONG RAW`
data.  For existing applications that want to continue to use Oracle12cDialect and still continue to implicitly map
`byte[]` and `Byte[]` attributes to `LONG RAW`, there is a new configuration setting you can use to enable that:
`hibernate.dialect.oracle.prefer_longvarbinary`, which is false by default (map to `BLOB`).

These details regarding https://hibernate.atlassian.net/browse/HHH-10345[HHH-10345] will be added to the 
https://github.com/hibernate/hibernate-orm/blob/5.0/migration-guide.adoc[5.0 Migration Guide] shortly.

For information on consuming the release via your favorite dependency-management-capable build tool, see https://hibernate.org/orm/downloads/

The release bundles can be obtained from: 
http://sourceforge.net/projects/hibernate/files/hibernate-orm/5.0.8.Final/[SourceForge] or 
http://bintray.com/hibernate/bundles/hibernate-orm/5.0.8.Final[BinTray].
