= "Hibernate OGM 5.3 Final is out"
Fabio Massimo Ercoli
:awestruct-tags: [ "Hibernate OGM", "Releases" ]
:awestruct-layout: blog-post
---

We're happy to announce the release of:
http://hibernate.org/ogm/releases/5.3/#get-it[Hibernate OGM 5.3 Final]

Hibernate OGM is now compatible with Hibernate ORM 5.2!

== Components upgrade

 * Upgrade ORM to 5.2.13.Final
 * Upgrade Hibernate Search to 5.9.0.Final
 * Upgrade Infinispan to 9.1.6.Final
 * Upgrade MongoDB driver to 3.6.3 and MongoDB test instance to 3.6.2
 * Upgrade Neo4J to 3.3.3

== Release Notes

All the changes are described in the
https://hibernate.atlassian.net/secure/ReleaseNote.jspa?projectId=10160&version=31638

== Where can I get it?

You can include in your project the dialect of your choice using this Maven coordinates:

* http://infinispan.org[Infinispan]
** Embedded: _org.hibernate.ogm:hibernate-ogm-infinispan-embedded:5.3.0.Final_
** Remote: _org.hibernate.ogm:hibernate-ogm-infinispan-remote:5.3.0.Final_
* https://www.mongodb.com[MongoDB]: _org.hibernate.ogm:hibernate-ogm-mongodb:5.3.0.Final_
* http://neo4j.com[Neo4j]: _org.hibernate.ogm:hibernate-ogm-neo4j:5.3.0.Final_

Alternatively, you can download archives containing all the binaries, source code and documentation
https://sourceforge.net/projects/hibernate/files/hibernate-ogm/5.3.0.Final[from Sourceforge].

If you are interested about available versions, you can check the official
http://hibernate.org/ogm/releases[Hibernate OGM download page].

== How can I get in touch?

You can find us through the following channels:

* https://discourse.hibernate.org/c/hibernate-ogm[User forum]
* https://hibernate.atlassian.net/browse/OGM[Issue tracker]
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list]
* http://stackoverflow.com[Stack Overflow]: we monitor the tag _hibernate-ogm_
* https://www.hipchat.com/gXEjW5Wgg[HipChat]: Hibernate OGM hipchat room

We are looking forward to hearing your feedback!


