= "Hibernate OGM 5.3 CR1 is out"
Fabio Massimo Ercoli
:awestruct-tags: [ "Hibernate OGM", "Releases" ]
:awestruct-layout: blog-post
---

We're happy to announce the release of:
http://hibernate.org/ogm/releases/5.3/#get-it[Hibernate OGM 5.3 CR1]

== Components upgrade

* Hibernate ORM version is upgraded to 5.2
* Hibernate Search version is upgraded to 5.9

== Infinispan embedded sequences and id generation improvements

When using `@SequenceGenerator`, Hibernate OGM will create Clustered Counter at start up.
This change will lead to better performance because it doesn't have to check if the Clustered Counter already exists each time.
See http://infinispan.org/docs/stable/user_guide/user_guide.html#clustered_counters[Clustered Counters].

When these are used for id generation their names now also contain the table name and not only the column name.
Given the following example:

====
[source,java]
----
@Entity
@Table(name = "Ruby")
private static class Ruby {
	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "gen")
	@TableGenerator(name = "gen", table = "Ruby_generators", initialValue = 0, pkColumnValue = "ruby_sequence")
	Long id;
}
----
====

The name of the Clustered Counter will be `Ruby_generators.ruby_sequence` instead of only `ruby_sequence`.
This is to avoid collision when different `@TableGenerator` are defined with different table attribute but the same pkColumn values.

[NOTE]
Keep in mind that if you already have some generators Hibernate OGM won't recognize them.
Make sure to update the model with a different initialValue higher than the one you have currently reached.

== Release Notes

All the changes are described in the
https://hibernate.atlassian.net/secure/ReleaseNote.jspa?projectId=10160&version=31626

== Where can I get it?

You can include in your project the dialect of your choice using this Maven coordinates:

* http://infinispan.org[Infinispan]
** Embedded: _org.hibernate.ogm:hibernate-ogm-infinispan-embedded:5.3.0.CR1_
** Remote: _org.hibernate.ogm:hibernate-ogm-infinispan-remote:5.3.0.CR1_
* https://www.mongodb.com[MongoDB]: _org.hibernate.ogm:hibernate-ogm-mongodb:5.3.0.CR1_
* http://neo4j.com[Neo4j]: _org.hibernate.ogm:hibernate-ogm-neo4j:5.3.0.CR1_

Alternatively, you can download archives containing all the binaries, source code and documentation
https://sourceforge.net/projects/hibernate/files/hibernate-ogm/5.3.0.CR1[from Sourceforge].

If you are interested about available versions, you can check the official
http://hibernate.org/ogm/releases[Hibernate OGM download page].

== How can I get in touch?

You can find us through the following channels:

* https://discourse.hibernate.org/c/hibernate-ogm[User forum]
* https://hibernate.atlassian.net/browse/OGM[Issue tracker]
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list]
* http://stackoverflow.com[Stack Overflow]: we monitor the tag _hibernate-ogm_
* https://hibernate.zulipchat.com/#narrow/stream/132091-hibernate-ogm-dev[Zulip]: Hibernate OGM Zulip stream

We are looking forward to hearing your feedback!


