= "Friends with Java 9 - Hibernate Validator 5.2.3.Final is out"
Gunnar Morling
:awestruct-tags: [ "Hibernate Validator", "Releases" ]
:awestruct-layout: blog-post
---
It's my pleasure to announce the release of Hibernate Validator 5.2.3.Final!

Wait, didn't we already do another Hibernate Validator release earlier this month?
That's right, indeed we pushed out the first Alpha of the 5.3 family a link:/2016/01/18/hibernate-validator-530-alpha1-out/[couple of days ago].
And normally, that'd mean that there would be no further releases of earlier version families.

But in this case we decided to do an exception from the rule as we noticed that Hibernate Validator couldn't be used with Java 9
(check out issue https://hibernate.atlassian.net/browse/HV-1048[HV-1048] if you are interested in the details).
As we don't want to keep integrators and users of Hibernate Validator from testing their own software on Java 9, we decided to fix that issue on the current stable release line
(in fact we strongly encourage you to test your applications on Java 9 to learn as early as possible about any potential changes you might need to make).

While we were at it, we backported some further bugfixes from 5.3 to 5.2, amongst them one for ensuring https://hibernate.atlassian.net/browse/HV-1048[compatability with the Google App Engine].
As always, you can find the complete list of fixes in the https://github.com/hibernate/hibernate-validator/blob/5.2.3.Final/changelog.txt[changelog].

== Where do I get it?

Use the GAV coordinates _org.hibernate:{hibernate-validator|hibernate-validator-cdi|hibernate-validator-annotation-processor}:5.2.3.Final_ to fetch the release with Maven, Gradle etc.
Alternatively, you can find distribution bundles containing all the bits on SourceForge (http://sourceforge.net/projects/hibernate/files/hibernate-validator/5.2.3.Final/hibernate-validator-5.2.3.Final-dist.tar.gz/download[TAR.GZ], http://sourceforge.net/projects/hibernate/files/hibernate-validator/5.2.3.Final/hibernate-validator-5.2.3.Final-dist.zip/download[ZIP]).

Found a bug? Have a feature request? Then let us know through the following channels:

* https://forum.hibernate.org/viewforum.php?f=31[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HV[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
