= "Hibernate Validator 5.2.4.Final is out"
Gunnar Morling
:awestruct-tags: [ "Hibernate Validator", "Releases" ]
:awestruct-layout: blog-post
---
It's my pleasure to announce the release of Hibernate Validator 5.2.4.Final!

This is a rather small bugfix release which addresses two nasty issues around one of the more advanced features of Bean Validation, http://beanvalidation.org/1.1/spec/#constraintdeclarationvalidationprocess-groupsequence-redefiningdefaultgroup[redefined default group sequences].

Please refer to the issues themselves (https://hibernate.atlassian.net/browse/HV-1055[HV-1055], https://hibernate.atlassian.net/browse/HV-1057[HV-1057]) for all the details.

== Where do I get it?

Use the GAV coordinates _org.hibernate:{hibernate-validator|hibernate-validator-cdi|hibernate-validator-annotation-processor}:5.2.4.Final_ to fetch the release with Maven, Gradle etc.
Alternatively, you can find distribution bundles containing all the bits on SourceForge (http://sourceforge.net/projects/hibernate/files/hibernate-validator/5.2.4.Final/hibernate-validator-5.2.4.Final-dist.tar.gz/download[TAR.GZ], http://sourceforge.net/projects/hibernate/files/hibernate-validator/5.2.4.Final/hibernate-validator-5.2.4.Final-dist.zip/download[ZIP]).

Found a bug? Have a feature request? Then let us know through the following channels:

* https://forum.hibernate.org/viewforum.php?f=31[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HV[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
