# Default page title
title: In Relation To

# Project id name
project: in.relation.to

# Default minify settings
minify: true
minified: .min
css_minifier: enabled
js_minifier: enabled
html_minifier: disabled

# Various settings
enable_google_analytics: true
google_analytics:
  id: G-C4TCX4V6QY
ignore_older_than_days: -1
legacy_post_syntax_highlighting: enabled
date_format: '%b %-d, %Y'

# Various resources
jborg_fonts_url: https://static.jboss.org/theme/fonts
jborg_images_url: https://static.jboss.org/theme/images
project_images_url: https://static.jboss.org/hibernate/images
jquery_js_url: https://code.jquery.com/jquery-3.1.1
jquery_js_url_integrity: "sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7"
semantic_ui_js_url: https://cdn.jsdelivr.net/npm/semantic-ui@2.2.14/dist/semantic
semantic_ui_js_url_integrity: "sha384-KfrAxmzWxzKdfquWGNOhm/N9kEjIgoP2yBPMQmAjQ+Is0hp+3BlcWT6PcI7NuKEP"
semantic_ui_css_url: https://cdn.jsdelivr.net/npm/semantic-ui@2.2.14/dist/semantic

hibernate_org:
  base_url: https://hibernate.org/
jira:
  base_url: https://hibernate.atlassian.net/
github:
  organization_url: https://github.com/hibernate/
twitter:
  base_url: https://twitter.com/hibernate/
google_plus:
  base_url: https://plus.google.com/112681342290762837955/posts
forum:
  base_url: https://discourse.hibernate.org/

####################################################################################################
# Asciidoctor config
####################################################################################################
asciidoctor:
  :safe: safe
  :attributes:
    #sitename: WriteAdapt
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    toclevels: 3
    icons: font
    source-highlighter: coderay
    coderay-css: style

####################################################################################################
# Site Profiles
####################################################################################################
# Update resource URLs based on the profile
profiles:
  development:
    minify: false
    minified: ""
    css_minifier: disabled
    js_minifier: disabled
    html_minifier: disabled
    # Different checksums because we're not using the minified files
    jquery_js_url_integrity: "sha384-VC7EHu0lDzZyFfmjTPJq+DFyIn8TUGAJbEtpXquazFVr00Q/OOx//RjiZ9yU9+9m"
    semantic_ui_js_url_integrity: "sha384-/OCHdyuUZjDPStDj7ti/VaVeGQ4U9HxuJhh0FNfMTf0eO1VeBLAam8EiKCIK+jso"
    legacy_post_syntax_highlighting: disabled
    ignore_older_than_days: 366
    disqus_shortname: staging-in-relation-to
    enable_google_analytics: false
    base_url: http://0.0.0.0:4242
    asciidoctor:
      :attributes:
        base_url: "http://localhost/"

  staging:
    disqus_shortname: staging-in-relation-to
    enable_google_analytics: false
    base_url: https://staging.in.relation.to/
    asciidoctor:
      :attributes:
        base_url: "https://staging.in.relation.to/"

  production:
    disqus_shortname: inrelationto
    base_url: https://in.relation.to/
    asciidoctor:
      :attributes:
        base_url: "https://in.relation.to/"
