# Default page title
title: In Relation To

# Project id name
project: in.relation.to

# Default minify settings
css_minifier: disabled
js_minifier: disabled
html_minifier: disabled

# Disqus settings
disqus_shortname: otnoitalerni-8

legacy_post_syntax_highlighting: enabled

####################################################################################################
# File merger
####################################################################################################
# Merge multiple JavaScript files to improve performance
fileMerger:
  enabled: true
  outputFilePath: /javascripts/bootstrap-community.js
  paths:
    - /javascripts/_bootstrap-transition.js
    - /javascripts/_bootstrap-alert.js
    - /javascripts/_bootstrap-button.js
    - /javascripts/_bootstrap-carousel.js
    - /javascripts/_bootstrap-collapse.js
    - /javascripts/_bootstrap-dropdown.js
    - /javascripts/_bootstrap-modal.js
    - /javascripts/_bootstrap-tooltip.js
    - /javascripts/_bootstrap-popover.js
    - /javascripts/_bootstrap-scrollspy.js
    - /javascripts/_bootstrap-tab.js
    - /javascripts/_bootstrap-typeahead.js
    - /javascripts/_bootstrap-affix.js
    - /javascripts/_jbossorg-navbarfix.js
    - /javascripts/_jbossorg-misc.js
    - /javascripts/_jbossorg-tabzilla.js
    - /javascripts/_jquery-easytabs.js
    - /javascripts/_crisp-scripts.js

####################################################################################################
# WGET
####################################################################################################
# Cache hosted fonts, images and javascript
wget:
  enabled: true
  rerunEach: 86400 # seconds (24h)
  timestampFilename: _wget-timestamp
  options:
    - --no-remove-listing
    - -q
    - -r
    - --no-parent
    - -N
    - --reject 'index.html*'
    - -e robots=off
    - --directory-prefix=.wget-cache
  urls:
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.js
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.min.js
    - http://static.jboss.org/theme/js/libs/html5/pre3.6/html5.min.js
    - http://static.jboss.org/theme/js/libs/prettify/188.0.0/prettify.min.js
    - http://static.jboss.org/theme/js/libs/holder/1.9/holder.js
    - http://static.jboss.org/theme/fonts/titilliumtext/
    - http://static.jboss.org/theme/fonts/font-awesome/
    - http://static.jboss.org/theme/images/common/
    - http://static.jboss.org/images/example/
    - http://static.jboss.org/images/hibernate/

####################################################################################################
# Asciidoctor config
####################################################################################################
asciidoctor:
  :safe: safe
  :attributes:
    #sitename: WriteAdapt
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    toclevels: 3
    icons: font
    source-highlighter: coderay
    coderay-css: style

####################################################################################################
# Site Profiles
####################################################################################################
# Update resource URLs based on the profile
profiles:
  editor: &base
    minified: .min
    css_minifier: disabled
    js_minifier: disabled
    html_minifier: disabled
    legacy_post_syntax_highlighting: disabled

    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: /cache/static.jboss.org/images/hibernate
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.3/bootstrap-community
    bootstrap_js_url: /javascripts/bootstrap-community

  development:
    << : *base

  staging:
    << : *base
    legacy_post_syntax_highlighting: enabled
    project_images_url: http://static.jboss.org/images/hibernate
    wget:
      #we don't need to download cached resources when on staging
      enabled: false
    base_url: http://staging.in.relation.to/

  production:
    << : *base
    legacy_post_syntax_highlighting: enabled
    project_images_url: http://static.jboss.org/images/hibernate
    wget:
      #we don't need to download cached resources when on staging
      enabled: false
    base_url: http://in.relation.to/

google_analytics:
  account: UA-61456706-1
