= "Hibernate ORM 5.5.0.Alpha1 released"
Christian Beikov
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:released-version: 5.5.0.Alpha1
:release-id: 31844
---

We are excited to announce the release of 5.5.0.Alpha1.

== Jakarta JPA work in progress

Hibernate ORM 5.5.0.Alpha1 adds new artifacts with the name suffix "-jakarta" like hibernate-core-jakarta.
These artifacts are currently work in progress, but will eventually provide support for Jakarta JPA 3.0.

== Bytecode enhancement

The bytecode enhancement configuration was adapted to turn on enhancement-as-proxy by default and remove the switch for configuring this.

In addition, the release introduces a few minor improvements as well as bug fixes. See below for the complete list
of changes.

=== Bugfixes

You can find the full list of changes in this version https://hibernate.atlassian.net/projects/HHH/versions/{release-id}/tab/release-report-all-issues[here] (or, for people without a Hibernate Jira account, https://hibernate.atlassian.net/issues/?jql=project=10031+AND+fixVersion={release-id}[here]).

== Thank you

Specials thanks to Karel Maesen for implementing Spatial support for CockroachDB and PostgisPG10Dialect.

== Getting {released-version}

All details are available and up to date on https://hibernate.org/orm/releases/5.5/#get-it[the dedicated page on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
