= Lucene for Java EE developers virtual user group
Emmanuel Bernard
:awestruct-tags: [ "Events", "Hibernate Search", "Infinispan", "WildFly" ]
:awestruct-layout: blog-post
---
Sanne is going to do a virtual JBoss User Group session Tuesday July 4th at 6PM BST / 5PM UTC / 1PM EDT / 10 AM PDT.
He is going to talk about **Lucene in Java EE**.

He will also describe some projects dear to our heart.
If you want to know what Hibernate Search, Infinispan bring to the Lucene table and how they use Lucene internally,
that's the event to be in!

[quote]
____
Apache Lucene is the de-facto standard open source library for Java developers to implement full-text-search capabilities.

While it’s thriving in its field, it is rarely mentioned in the scope of Java EE development.

In this talk we will see for which features many developers love Lucene, make some concrete examples of common problems it elegantly solves, and see some best practices about using it in a Java EE stack.

Finally we'll see how some popular OSS projects such as Hibernate ORM (JPA provider), WildFly (Java EE runtime) and Infinispan (in-memory datagrid, JCache implementor) actually provide great Lucene integration capabilities.
____

If you are interested,
get some more info on http://www.meetup.com/JBoss-User-Group-Worldwide/events/220482490/[Meetup]
and enlist.
