= Revamped blog
Emmanuel Bernard
:awestruct-tags: ["Discussions"]
:awestruct-layout: blog-post
:hide-uri-scheme:

Welcome to the newly revamped Hibernate and friends blog.

As you can see, we made it look like https://hibernate.org
and we took the opportunity to clean up the tags to make them more useful.
But we had other reasons to migrate.

Blog early, blog often::
We have been very happy with the http://asciidoctor.org[Asciidoctor]-based writing experience
of both our reference documentation and of https://hibernate.org.
We are bringing this ease of writing to our blog and the not so secret objective is for us to blog more.
So if you don't see more content here, you can start yelling at us :)

Write once, display anywhere::
There is an added bonus to using Asciidoctor for all of our writing:
we can move content easily between systems.
What starts as a blog can easily become a how-to page on the site or a section in the reference documentation.

Maintenance::
We had a few issues with the old infrastructure
that were keeping us away from our IDEs a bit too often for comfort.  +
This blog is a statically generated site, we use http://awestruct.org[Awestruct].
This means that we can make is scale very easily and with very low maintenance.
Nothing beats plain old HTML :)

We did migrate all the old entries and comments from the old blog:
fear not, nothing is lost.

If you seen any issue, let us know in the comments or by https://twitter.com/hibernate[tweet].
Oh and enlist to our new http://in.relation.to/blog.atom[feed URL].
