= Elasticsearch integration reaches the Beta2 milestone
Sanne Grinovero
:awestruct-tags: [ "Hibernate Search", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
---

This summer was relatively quiet in terms of releases, but many have been testing and improving the Beta1 release of our Hibernate Search / Elasticsearch integration.

So today we release version `5.6.0.Beta2` with 45 fixes and enhancements!

For a detailed list of all improvements, see this https://hibernate.atlassian.net/issues/?jql=project+%3D+HSEARCH+AND+fixVersion+%3D+5.6.0.Beta2[JIRA query].

The day of a Final release gets closer, but highly depends on your feedback. Please keep the feedback coming!

Please let us know of any problem or suggestion by creating an https://hibernate.atlassian.net/projects/HSEARCH/summary[issue on JIRA],
by sending an email to the developer's  https://hibernate.org/community/[developer's mailing lists], or posting on the https://forums.hibernate.org/viewforum.php?f=9[forums].

We also monitor Stack Overflow; when posting on SO please use the tag http://stackoverflow.com/questions/tagged/hibernate-search[`hibernate-search`]. 

== How to get this release

Everything you need is available on Hibernate Search's https://hibernate.org/search/[web site].

Get it from Maven Central using the following coordinates:

====
[source, XML]
----
<dependency>
   <groupId>org.hibernate</groupId>
   <artifactId>hibernate-search-orm</artifactId>
   <version>5.6.0.Beta2</version>
</dependency>
----
====

Downloads from https://sourceforge.net/projects/hibernate/files/hibernate-search/5.6.0.Beta2/[Sourceforge] are available as well.

== Notes on compatibility

This version is compatible with Apache Lucene versions from 5.3.x to 5.5.x, and with Hibernate ORM versions 5.0.x and 5.1.x.

Compatibility with Hibernate ORM 5.2.x is not a reality yet - we expect to see that materialize in early October.
Compatibility with Lucene 6.x is scheduled for Hibernate Search 6.0, which will take longer - probably early 2017.

Finally, the version we used of Elasticsearch for all developing and tests of this version was Elasticsearch v. `2.3.1`.
We will soon upgrade this to the latest version, and discuss strategies to test against multiple versions.
