= Triple Hibernate Search release
Sanne Grinovero
:awestruct-tags: [ "Hibernate Search", "Elasticsearch", "Releases" ]
:awestruct-layout: blog-post
---

Today is a good time for some maintenance releases of Hibernate Search.

We released all three branches currently in maintenance mode:

Version 5.5.7.Final:: Maintained as it's included in WildFly, compatible with Hibernate ORM `5.0` and `5.1`: https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20fixVersion%20%3D%205.5.7.Final[change log].

Version 5.6.2.Final:: Latest stable version compatible with Hibernate ORM `5.0` and `5.1`, including first experimental support for Elasticsearch: https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20fixVersion%20%3D%205.6.2.Final[change log].

Version 5.7.1.Final:: Stable version compatible with Hibernate ORM > `5.2.3.Final` and later: https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20fixVersion%20%3D%205.7.1.Final[change log].

The master branch is also very active! Expect a new Beta release of version 5.8 with support for Elasticsearch `5+` later this week.

== Why ?

We backported various small fixes which should be welcome but of low impact. The big deal is https://hibernate.atlassian.net/browse/HSEARCH-2691[HSEARCH-2691], as you might fail to notice this problem until testing under load, which is quite inconvenient.

Big thanks to Andrej Golovnin, who spotted the problem and shared a patch; I suspect it wasn't easy to find the problem.

Also thanks to Osamu Nagano, who pointed out the importance of this fix and suggested backporting it urgently.

== How to get these releases

All versions are available for download on Hibernate Search's https://hibernate.org/search/[web site].

Ideally use a modern build tool to fetch it from Maven central; these are the coordinates:

====
[source, XML]
----
<dependency>
   <groupId>org.hibernate</groupId>
   <artifactId>hibernate-search-orm</artifactId>
   <version>5.7.1.Final</version>
</dependency>
----
====

To use the experimental Elasticsearch integration you'll also need:

====
[source, XML]
----
<dependency>
   <groupId>org.hibernate</groupId>
   <artifactId>hibernate-search-elasticsearch</artifactId>
   <version>5.7.1.Final</version>
</dependency>
----
====

Downloads from https://sourceforge.net/projects/hibernate/files/hibernate-search/[Sourceforge] are available as well.

== Feedback

Please let us know of any problem or suggestion by creating an https://hibernate.atlassian.net/projects/HSEARCH/summary[issue on JIRA],
or by sending an email to the developer's  https://hibernate.org/community/[developer's mailing lists], or posting on the https://forums.hibernate.org/viewforum.php?f=9[forums].

We also monitor Stack Overflow; when posting on SO please use the tag http://stackoverflow.com/questions/tagged/hibernate-search[`hibernate-search`]. 

