= "Release: Hibernate ORM 5.4.22.Final"
Sanne Grinovero
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:release-id: 31880
---

Last night we released Hibernate ORM version `5.4.22.Final`.

This is a micro release: the result of backporting a number of fixes to our stable branch.

== A big thank you

Special thanks to Nathan Xu, Christian Beikov, Jan-Willem Gmelig Meyling, Yanming Zhou, Falko Modler, Moritz Becker and Dmitry Gusev, for all the amazing help in maintenance, giving some space to the core team to focus on the big picture.

It's great to see that not only did people step up to contribute patches, but also help by reviewing each other's patch.

This is a very welcome new trend, as it's difficult for us otherwise to provide proper feedback to all contributions, as we're getting a significant amount of excellent feedback, on a range of subjects!

Amazing.

== Detailed changelog

You can find the full list of changes in this version https://hibernate.atlassian.net/secure/ReleaseNote.jspa?version={release-id}&styleName=Html&projectId=10031[here].

== Getting Hibernate ORM 5.4.22.Final

All details are available and up to date on https://hibernate.org/orm/releases/5.4/#get-it[the dedicated page on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)

