= "Hibernate ORM {released-version} released"
Sanne Grinovero
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:released-version: 5.6.0.CR1
:release-id: 31986
---

The main branch of Hibernate ORM, which will soon be promoted as our 5.6 release, is looking good and stable;
we're happy to announce tag `5.6.0.CR1` was released today and should already be available from your favourite Maven mirrors.

Compared to previous `5.6.0.Beta2`, you should see no differences:

* The GraalVM support module was upgraded to compile with GraalVM `21.2.0`.
* JMX integration is now marked deprecated, in preparation for Hibernate ORM 6
* JACC integration was also marked deprecated, for the same reason
* SchemaMigrator/SchemaValidator are undergoing some minor refactoring, to expose functionality to Hibernate Reactive

== Getting {released-version}

All details are available and up to date on https://hibernate.org/orm/releases/5.6/#get-it[the dedicated page on hibernate.org].

Full changelog: https://hibernate.atlassian.net/issues/?jql=project=10031%20AND%20fixVersion=31986[changelog for 5.6.0.CR1]

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
