= "Hibernate ORM {released-version} released"
Sanne Grinovero
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:released-version: 5.6.0.Final
:release-id: 31985
---

The Hibernate team is pleased to announce availability of version `5.6.0.Final` of our flagship ORM library.

Compared to previous candidate releases, not much has changed:

* a single bugfix https://hibernate.atlassian.net/browse/HHH-13295[HHH-13295] related to combining `@EmbeddedId` with `@MapsId` - this was not a regression
* Upgraded ByteBuddy to the latest
* Some more deprecation warnings, to better prepare you all for the amazing Hibernate ORM 6 - which is coming soon and https://in.relation.to/2021/10/11/orm-600-beta1/[you could already try out as Beta1 is now available.]

== Some maintenance as well

We have also released Hibernate ORM v. `5.5.8.Final`, which includes a more substantial amount of bugfixes (but which had already been incorporated in 5.6).

Going forward we'll be more conservative with backporting fixes to the `5.5` branch, but at this point the differences between `5.5` and `5.6` are fairly minimal, as we focus on the future of `6.0`.

== Getting {released-version}, detailed changelogs

All details are available and up to date on https://hibernate.org/orm/releases/5.6/#get-it[the dedicated page on hibernate.org].

Full https://hibernate.atlassian.net/issues/?jql=project=10031%20AND%20fixVersion=31985[changelog for 5.6.0.Final]

Full https://hibernate.atlassian.net/issues/?jql=project=10031%20AND%20fixVersion=5.5.8[changelog for 5.5.8.Final]

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)


