= "Hibernate ORM {released-version} released"
Sanne Grinovero
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:released-version: 5.4.27.Final
:release-id: 31910
---


Happy new year to all!

During the break we released two versions of Hibernate ORM: both `5.4.26.Final` and `5.4.27.Final`, and couldn't announce them properly.

So now feel free to ignore the already out of date `.26` and jump to `.27`.

== Micrometer Statistics

The https://micrometer.io/[Micrometer] integration with Hibernate ORM was now moved into the Hibernate ORM repository.

This should help to keep the integration more stable as ORM evolves, and improve the metrics we expose going forward.

You can still use the module from Micrometer, but this is likely going to be deprecated soon.
We suggest migrating your dependency to `org.hibernate:hibernate-micrometer`.

== Minor updates

Some other minor defects have been fixed, for a full list see:

 * https://hibernate.atlassian.net/issues/?jql=project=10031+AND+fixVersion=31910[Changelog for 5.4.27.Final]
 * https://hibernate.atlassian.net/issues/?jql=project=10031+AND+fixVersion=31904[Changelog for 5.4.26.Final]

== Getting {released-version}

All details are available and up to date on https://hibernate.org/orm/releases/5.4/#get-it[the dedicated page on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
