= "Hibernate ORM {released-version} released"
Sanne Grinovero
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:released-version: 5.5.5.Final
:release-id: 31963
---

Hibernate ORM `5.5.5.Final` was released today.

It's our most recent stable version, with only minimal changes to address issues identified in the previous release.

This is also our "lightest" release ever, in terms of memory consumption.
But this is the result of many years of work, not any specific change in this particular build, so I'll follow up with a dedicated analysis as we collect more data.

== Details

For the full changelog see the https://hibernate.atlassian.net/secure/ReleaseNote.jspa?version={release-id}&styleName=Html&projectId=10031[Release Notes].

== Getting {released-version}

All details are available and up to date on https://hibernate.org/orm/releases/5.5/#get-it[the dedicated page on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
