= "Hibernate ORM {released-version} released"
Sanne Grinovero
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:released-version: 5.6.7.Final
:release-id: 32053
---

This week we released both Hibernate ORM version `5.6.6.Final` and `5.6.7.Final`.

== 5.6.6.Final changelog

Version 5.6.6 is a regular maintenance release of our 5.6 branch: the latest stable branch.

Full https://hibernate.atlassian.net/secure/ReleaseNote.jspa?projectId=10031&version=32031[changelog for `5.6.6.Final`].

== 5.6.7.Final

Shortly after releasing 5.6.6 we realised it was emitting confusing deprecation warnings,
so we decided to fix those right away and publish 5.6.7 immediately after.

This implies you can ignore version `5.6.6.Final` and focus on `5.6.7.Final`, but to get an overview
of all interesting bugfixes we suggest to refer to the `5.6.6.Final` changelog linked above.

For completeness: the short https://hibernate.atlassian.net/secure/ReleaseNote.jspa?projectId=10031&version=32053[changelog for `5.6.7.Final`].

== Sourceforge: phasing out?

Normally each Hibernate ORM release is uploaded to both Maven central repositories and to Sourceforge.

Uploading tarballs and zip files to Sourceforge has been a very old tradition, but we suspect nowadays
most of you will get it exclusively from Maven repositories.

During these two releases the upload to Sourceforge failed as Sourceforge had some services issues;
we didn't consider this important enough to warrant postponing our releases;
we also don't think these missing represent an important enough issue to try uploading them there later.

In fact we're considering stopping uploads to Sourceforge altogether, so consider this a test;
if you have strong needs to download our releases from Sourceforge rather than a Maven repository
we would like to hear from you.

== Getting {released-version}

All details are available and up to date on https://hibernate.org/orm/releases/5.6/#get-it[the dedicated page on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)


