= "Hibernate ORM {released-version}"
Sanne Grinovero
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:released-version: 5.6.14.Final
---

Hibernate ORM `5.6.14.Final` is now available.

Just after releasing `5.6.13.Final` yesterday we discovered https://hibernate.atlassian.net/browse/HHH-15662[a critical regression], so
we decided to start a new release as soon as possible.

The only change is to fix that one problem, which was newly introduced: let's forget about the existence of `5.6.13.Final` - nothing to see there :)

All the great improvements listed in https://in.relation.to/2022/11/03/hibernate-orm-5613/[yesterday's blog] apply of course; to recap
it included both important bugfixes and significant performance improvements: might be worth your attention.


== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)

