= "Hibernate Validator 5.3.1.Final is out"
Guillaume Smet
:awestruct-tags: [ "Hibernate Validator", "Releases" ]
:awestruct-layout: blog-post
---
I am pleased to announce the first maintenance release of Hibernate Validator 5.3.

== Bug fixes

Here are the main issues we fixed in this release:

* https://hibernate.atlassian.net/browse/HV-1131[HV-1131] - An implementation of javax.el mistakenly became a hard dependency in 5.3 even if you were using a message interpolator not requiring it.
* https://hibernate.atlassian.net/browse/HV-1032[HV-1032] - Under specific inheritance scheme involving generics, you could encounter an infinite loop. This issue was already present in 5.2 and is now fixed.
* https://hibernate.atlassian.net/browse/HV-1140[HV-1140] - https://github.com/mulderbaba[Mert Çalişkan] fixed a long standing bug with our decapitalization method not being correct with specific locales (and especially the Turkish one).

You can find the complete list of all addressed issues in the https://github.com/hibernate/hibernate-validator/blob/5.3.1.Final/changelog.txt[change log].

== JDK 9 support

We upgraded our JDK 9 support to the latest release and integrated it to our automated CI testing. 5.3.1.Final is the first release benefiting from this new process.

Note that we still have some progress to do on the JDK 9 front:

* our OSGi tests are not running on JDK 9 as we are waiting for Pax and Karaf to release JDK 9 ready versions
* we can't build the full distribution with JDK 9 yet (see https://github.com/hibernate/hibernate-validator#build-on-jdk-9[our build instructions for JDK 9])

But we are definitely on the right track!

== Getting the release

Hibernate Validator 5.3.1.Final is a drop-in replacement of Hibernate Validator 5.3.0.Final.

To get the release with Maven, Gradle etc. use the GAV coordinates _org.hibernate:{hibernate-validator|hibernate-validator-cdi|hibernate-validator-annotation-processor}:5.3.1.Final_.

Alternatively, a distribution bundle containing all the bits is provided on SourceForge (http://sourceforge.net/projects/hibernate/files/hibernate-validator/5.3.1.Final/hibernate-validator-5.3.1.Final-dist.tar.gz/download[TAR.GZ], http://sourceforge.net/projects/hibernate/files/hibernate-validator/5.3.1.Final/hibernate-validator-5.3.1.Final-dist.zip/download[ZIP]).

To get in touch, use the following channels:

* http://stackoverflow.com/questions/tagged/hibernate-validator[hibernate-validator tag on Stackoverflow] (usage questions)
* https://forum.hibernate.org/viewforum.php?f=31[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HV[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)

== What's next?

We are going to prepare a 5.4 release with support for javax.money validation contributed by Lukas Niemeier and Willi Schönborn from Zalando and a lot of improvements to the annotation processor thanks to the great work of Marko Bekhta.

We are actively working on Bean Validation 2.0 and Hibernate Validator 6 with a strong focus on supporting Java 8 new features (and much more!). The more the merrier, so feel free to join us: drop ideas, comment on others' proposals, now is the time to define the future of Bean Validation. You can find all the necessary information on the http://beanvalidation.org/[Bean Validation website].

