= "Hibernate Validator 5.4.0.Final"
Guillaume Smet
:awestruct-tags: [ "Hibernate Validator", "Releases" ]
:awestruct-layout: blog-post
---

It's with great pleasure that I announce you the final release of Hibernate Validator 5.4.0. 

== What's new since 5.4.0.CR1

For those of you following closely this blog, not much to say since 5.4.0.CR1. We fixed a few bugs and polished a few things.

We shod in a small new feature: you can now require a `@ScriptAssert` constraint violation to be reported on a specific field. In the following example, the constraint violation will be reported on the `endDate` property rather than at the class level:

```java
@ScriptAssert(lang = "javascript", script = "_this.endDate.after(_this.startDate)", reportOn="endDate")
public class CalendarEvent {

 	private Date startDate;
 	private Date endDate;

	//...
}
```

You can find the complete list of all addressed issues in the https://github.com/hibernate/hibernate-validator/blob/5.4.0.Final/changelog.txt[change log].

== New documentation layout

We converted the Hibernate Validator documentation to http://asciidoctor.org/[AsciiDoctor] a loooong time ago but we were still using a Docbook output to be able to generate the PDF documentation. AsciiDoctor now has a https://github.com/asciidoctor/asciidoctor-pdf[(still in alpha but already pretty mature) PDF plugin] and we decided to take the final step and get rid of our Docbook output.

So our https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/[reference documentation] is now using a nice AsciiDoctor output and so does our https://docs.jboss.org/hibernate/stable/validator/reference/en-US/pdf/hibernate_validator_reference.pdf[PDF documentation].

We hope you'll like it. We do!

== 5.4.0 Retrospective

You might not follow our blog on a regular basis so here is a retrospective of all the good things included in 5.4.0.Final.

=== JavaMoney support

Hibernate Validator now includes http://javamoney.github.io/[JavaMoney (JSR 354)] support. You can use `@DecimalMin` and `@DecimalMax` constraints on your `MonetaryAmount` fields and we also introduced a new `@Currency` annotation allowing you to constrain the currency used in your ``MonetaryAmount``s.

See our previous blog posts for more information:

 * http://in.relation.to/2016/12/08/hibernate-validator-540-beta1-and-534-final-out/[5.4.0.Beta1 release announcement]
 * http://in.relation.to/2017/01/12/hibernate-validator-540-cr1-final-out/[5.4.0.CR1 release announcement]

This feature was initially contributed by Lukas Niemeier and Willi Schönborn from Zalando.

=== Annotation processor improvements

A special thank you goes to https://github.com/marko-bekhta[Marko Bekhta] for his work on the annotation processor. Marko invested a lot of time to get the annotation processor in a par with the latest Hibernate Validator features. Go validate your constraint definitions!

=== WildFly patch

Using WildFly and wanting to use the good things of this new version? We now provide a WildFly patch you can apply on top of your WildFly installation to use 5.4.0.Final.

You can find more information in the http://in.relation.to/2016/12/08/hibernate-validator-540-beta1-and-534-final-out/#applying-a-wildfly-patch[5.4.0.Beta1 release announcement].

=== And a whole lot of good things

 * Improvements to the `@Email` constraints
 * New constraints specific to Polish identification numbers
 * A Ukrainian translation

== Getting 5.4.0.Final

To get the release with Maven, Gradle etc. use the GAV coordinates _org.hibernate:{hibernate-validator|hibernate-validator-cdi|hibernate-validator-annotation-processor}:5.4.0.Final_.

Alternatively, a distribution bundle containing all the bits is provided on SourceForge (http://sourceforge.net/projects/hibernate/files/hibernate-validator/5.4.0.Final/hibernate-validator-5.4.0.Final-dist.tar.gz/download[TAR.GZ], http://sourceforge.net/projects/hibernate/files/hibernate-validator/5.4.0.Final/hibernate-validator-5.4.0.Final-dist.zip/download[ZIP]).

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* http://stackoverflow.com/questions/tagged/hibernate-validator[hibernate-validator tag on Stackoverflow] (usage questions)
* https://forum.hibernate.org/viewforum.php?f=31[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HV[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)

== What's next?

Bean Validation 2.0 and Hibernate Validator 6 are under active development.

As far as Bean Validation 2.0 is concerned, there are very interesting discussions going on about value extraction which is THE big BV 2.0 feature. Come and join us on http://beanvalidation.org/[Bean Validation website] to define the future of Bean Validation.

