= "Hibernate Validator 5.4.1.Final"
Guillaume Smet
:awestruct-tags: [ "Hibernate Validator", "Releases" ]
:awestruct-layout: blog-post
---

== A bugfix release

Hibernate Validator 5.4.1.Final is a bugfix release, mostly for corner cases. 5.4.1.Final is a recommended upgrade for everyone.

Here are the most prominent bugfixes of this release:

 * https://hibernate.atlassian.net/browse/HV-1088[HV-1088] - Fix a concurrency issue in validator initialization that you probably wouldn't encounter in a normal usage - you're supposed to use a shared `ConstraintValidatorFactory` which mitigates the issue
 * https://hibernate.atlassian.net/browse/HV-1280[HV-1280] - Fix a class loading conflict with Xerces in modular environements (e.g. WildFly)
 * https://hibernate.atlassian.net/browse/HV-1252[HV-1252] - Fix an issue with the annotation processor and JavaMoney support. Thanks go to https://github.com/ghusta[Guillaume Husta] for this one.
 * https://hibernate.atlassian.net/browse/HV-1253[HV-1253] - A few TYPE_USE mentions had been mistakenly introduced in 5.4 when backporting from 6 (5.4 still supports Java 6)

We also integrated a new translation, Persian, thanks to https://github.com/shahramgdz[Shahram Goodarzi].

And finally, we upgraded our build instructions for the latest JDK 9 early access build.

As usual, you can find the complete list of all addressed issues in the https://github.com/hibernate/hibernate-validator/blob/5.4.1.Final/changelog.txt[change log].

== Getting 5.4.1.Final

To get the release with Maven, Gradle etc. use the GAV coordinates _org.hibernate:{hibernate-validator|hibernate-validator-cdi|hibernate-validator-annotation-processor}:5.4.1.Final_.

Alternatively, a distribution bundle containing all the bits is provided on SourceForge (http://sourceforge.net/projects/hibernate/files/hibernate-validator/5.4.1.Final/hibernate-validator-5.4.1.Final-dist.tar.gz/download[TAR.GZ], http://sourceforge.net/projects/hibernate/files/hibernate-validator/5.4.1.Final/hibernate-validator-5.4.1.Final-dist.zip/download[ZIP]).

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* http://stackoverflow.com/questions/tagged/hibernate-validator[hibernate-validator tag on Stackoverflow] (usage questions)
* https://forum.hibernate.org/viewforum.php?f=31[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HV[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)

== What's next?

Bean Validation 2.0 and Hibernate Validator 6 are under active development. We will release a new alpha in the next few days.

As far as Bean Validation 2.0 is concerned, there are very interesting discussions going on about value extraction which is THE big BV 2.0 feature. Come and join us on http://beanvalidation.org/[Bean Validation website] to define the future of Bean Validation.

