= "Hibernate ORM 5.3.7.Final released"
Guillaume Smet
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:released-version: 5.3.7.Final
:release-id: 31714
---

Today, we released a new maintenance release of Hibernate ORM 5.3: 5.3.7.Final.

== What's new

=== Bug fixes

We fixed a couple of compatibility issues and bugs.

You can find the full list of changes https://hibernate.atlassian.net/projects/HHH/versions/{release-id}/tab/release-report-all-issues[here] (or, for people without a Hibernate Jira account, https://hibernate.atlassian.net/secure/ReleaseNote.jspa?version={release-id}&styleName=Html&projectId=10031[here]).

== Getting {released-version}

All details are available and up to date on http://hibernate.org/orm/releases/5.3/#get-it[the dedicated page on hibernate.org].

== What's next?

We are working on a 5.4 release which will contain more bugfixes, JDK 11 support improvements (see http://in.relation.to/2018/09/13/using-hibernate-orm-with-jdk11/[here] for how to use 5.3 with JDK 11) and some major improvements on entity graphs.

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)

