= "Hibernate Validator 6.0.11.Final released"
Guillaume Smet
:awestruct-tags: [ "Hibernate Validator", "Releases" ]
:awestruct-layout: blog-post
:released-version: 6.0.11.Final
---

We just released Hibernate Validator 6.0.11.Final which comes with an improved compatibility with JDK 11 and a couple of bugfixes.

This is a recommended upgrade for everyone using Hibernate Validator and it is a drop-in replacement for 6.0.10.Final in most cases (see https://developer.jboss.org/wiki/HibernateValidatorMigrationGuide[our migration guide]).

== What's new

=== JDK 11 support

JDK 11 does not include JAXB anymore. Instead of relying on an external dependency and because our XML descriptors are quite simple, we decided to update our XML parsing layer to use StAX directly.

Thus, you can now use Hibernate Validator with JDK 11 without adding a dependency to a JAXB implementation.

A big thanks to https://github.com/marko-bekhta[Marko Bekhta] for his work on this task.

All our tests (except OSGi tests for which we are waiting for a Karaf update) are now run regularly with the latest JDK 11 build.

=== Bug fixes

The main issue we fixed is https://hibernate.atlassian.net/browse/HV-1637[HV-1637], which caused an exception when using `@DecimalMax` with our German and Dutch translations.

=== Full changelog

The complete list of fixed issues can be found https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HV%20AND%20fixVersion%20%3D%20{released-version}%20order%20by%20created%20DESC[on our JIRA].

== Getting {released-version}

To get the release with Maven, Gradle etc. use the GAV coordinates _org.hibernate.validator:{hibernate-validator|hibernate-validator-cdi|hibernate-validator-annotation-processor}:{released-version}_. Note that the group id has changed from `org.hibernate` (Hibernate Validator 5 and earlier) to `org.hibernate.validator` (from Hibernate Validator 6 onwards).

Alternatively, a distribution bundle containing all the bits is provided on SourceForge (http://sourceforge.net/projects/hibernate/files/hibernate-validator/{released-version}/hibernate-validator-{released-version}-dist.tar.gz/download[TAR.GZ], http://sourceforge.net/projects/hibernate/files/hibernate-validator/{released-version}/hibernate-validator-{released-version}-dist.zip/download[ZIP]).

If you want to benefit from the new features of this version on WildFly, we also provide WildFly patches for http://search.maven.org/remotecontent?filepath=org/hibernate/validator/hibernate-validator-modules/{released-version}/hibernate-validator-modules-{released-version}-wildfly-11.0.0.Final-patch.zip[WildFly 11] and http://search.maven.org/remotecontent?filepath=org/hibernate/validator/hibernate-validator-modules/{released-version}/hibernate-validator-modules-{released-version}-wildfly-12.0.0.Final-patch.zip[WildFly 12]. You can read about how to apply such patches https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#_updating_hibernate_validator_in_wildfly[here].

== What's next?

Our efforts are now directed towards the new 6.1, which will introduce some structuring changes such as allowing getters with non standard names (`name()` instead of `getName()` for instance) and JSON validation support.

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* http://stackoverflow.com/questions/tagged/hibernate-validator[hibernate-validator tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-validator[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HV[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
* http://lists.jboss.org/pipermail/beanvalidation-dev/[Bean Validation development mailing list] (discussions about the Bean Validation specification)

