= "Hibernate ORM 5.4.0.Final released"
Guillaume Smet
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:released-version: 5.4.0.Final
:release-id: 31738
---

We just released the final version of Hibernate ORM 5.4.0.

It is designed to be a drop in replacement for ORM 5.3.x.

Apart from some changes to entity graphs to make them more user friendly, it's all about bugfixes and polishing.

== What's new

=== Bugfixes and documentation improvements

We fixed a couple of bugs and regressions and improved the documentation.

You can find the full list of changes in this version https://hibernate.atlassian.net/projects/HHH/versions/{release-id}/tab/release-report-all-issues[here] (or, for people without a Hibernate Jira account, https://hibernate.atlassian.net/secure/ReleaseNote.jspa?version={release-id}&styleName=Html&projectId=10031[here]).

=== So what's new compared to 5.3.x?

Please refer to the previous blog posts about the candidate releases:

 * http://in.relation.to/2018/11/15/hibernate-orm-540-cr1-out/[CR1 announcement]: entity graphs improvements, JDK 11 support
 * http://in.relation.to/2018/11/29/hibernate-orm-540-cr2-out/[CR2 announcement]: JAXB upgrade

The full list of changes made during the 5.4 release cycle can be found https://hibernate.atlassian.net/browse/HHH-13156?jql=project%20%3D%20HHH%20AND%20fixVersion%20in%20(5.4.0%2C%205.4.0.CR1%2C%205.4.0.CR2)[here].

== Getting {released-version}

All details are available and up to date on https://hibernate.org/orm/releases/5.4/#get-it[the dedicated page on hibernate.org].

== What's next?

We will release regular maintenance releases thereafter but the main focus of development is now Hibernate ORM 6.

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)

