= "Hibernate Validator 6.0.14.Final released"
Guillaume Smet
:awestruct-tags: [ "Hibernate Validator", "Releases" ]
:awestruct-layout: blog-post
:released-version: 6.0.14.Final
---

We just released Hibernate Validator 6.0.14.Final which comes with a critical bugfix.

This is a recommended upgrade for everyone using Hibernate Validator and it is a drop-in replacement for 6.0.13.Final.

== What's new

We fixed one critical issue: https://hibernate.atlassian.net/browse/HV-1684[HV-1684].

If you have a constraint on a `Map` like this:

[source, java]
----
@Size(min=1)
Map<String, String> map = new HashMap<>();
----

the validation of this constraint will at some point lead to a `StackOverflowError` (how long time it takes will depend on how often you validate this constraint).
In this case, you have no other choice than restarting your application.

In a normal setup, only ``Map``s (and the JavaFX `*MapProperty`) are concerned as they are the only ones with 2 value extractors (one for the key and one for the value).
In the case of a single value extractor, the issue is mitigated.
You might also encounter the issue for other types if you added multiple custom value extractors for the same type.

The issue was reported to us late last week and we decided to release an emergency fix for it, considering how critical it can be for some applications. It has been introduced in Hibernate Validator 6.0.8.Final.

=== Full changelog

The complete list of fixed issues can be found https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HV%20AND%20fixVersion%20%3D%20{released-version}%20order%20by%20created%20DESC[on our JIRA].

== Getting {released-version}

To get the release with Maven, Gradle etc. use the following GAV coordinates:

 * _org.hibernate.validator:hibernate-validator:{released-version}_
 * _org.hibernate.validator:hibernate-validator-cdi:{released-version}_
 * _org.hibernate.validator:hibernate-validator-annotation-processor:{released-version}_

Note that the group id has changed from `org.hibernate` (Hibernate Validator 5 and earlier) to `org.hibernate.validator` (from Hibernate Validator 6 onwards).

Alternatively, a distribution bundle containing all the bits is provided on SourceForge (http://sourceforge.net/projects/hibernate/files/hibernate-validator/{released-version}/hibernate-validator-{released-version}-dist.tar.gz/download[TAR.GZ], http://sourceforge.net/projects/hibernate/files/hibernate-validator/{released-version}/hibernate-validator-{released-version}-dist.zip/download[ZIP]).

If you want to benefit from the new features of this version on WildFly, we also provide WildFly patches for http://search.maven.org/remotecontent?filepath=org/hibernate/validator/hibernate-validator-modules/{released-version}/hibernate-validator-modules-{released-version}-wildfly-15.0.0.Final-patch.zip[WildFly 15] and http://search.maven.org/remotecontent?filepath=org/hibernate/validator/hibernate-validator-modules/{released-version}/hibernate-validator-modules-{released-version}-wildfly-14.0.1.Final-patch.zip[WildFly 14]. You can read about how to apply such patches https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#_updating_hibernate_validator_in_wildfly[here].

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* http://stackoverflow.com/questions/tagged/hibernate-validator[hibernate-validator tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-validator[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HV[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
* http://lists.jboss.org/pipermail/beanvalidation-dev/[Bean Validation development mailing list] (discussions about the Bean Validation specification)

