= "Hibernate ORM 5.4.1.Final released"
Guillaume Smet
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:released-version: 5.4.1.Final
:release-id: 31726
---

We just released the first maintenance release of Hibernate ORM 5.4.

It is designed to be a drop in replacement for ORM 5.4.0.

== What's new

=== Bugfixes and documentation improvements

We fixed several regressions and improved the documentation. Some regressions are specific to 5.4 but some others are also affecting older versions.

You can find the full list of changes in this version https://hibernate.atlassian.net/projects/HHH/versions/{release-id}/tab/release-report-all-issues[here] (or, for people without a Hibernate Jira account, https://hibernate.atlassian.net/issues/?jql=project=10031+AND+fixVersion={release-id}[here]).

== Getting {released-version}

All details are available and up to date on https://hibernate.org/orm/releases/5.4/#get-it[the dedicated page on hibernate.org].

== What's next?

We will release regular maintenance releases thereafter but the main focus of development is now Hibernate ORM 6.

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)

