= "Hibernate Validator 6.2.4.Final, 7.0.5.Final and 8.0.0.CR2 released"
Guillaume Smet
:awestruct-tags: [ "Hibernate Validator", "Releases" ]
:awestruct-layout: blog-post
---

Today, we released new maintenance releases for our Hibernate Validator 6.2 and 7.0 branches.

Both versions improve testing of Java records and make sure the annotation processor is working correctly with records.

We also released a new candidate release (CR2) of Hibernate Validator 8.0, which targets Jakarta EE 10.

== Getting 6.2.4.Final

To get the release with Maven, Gradle etc. use the GAV coordinates _org.hibernate.validator:{hibernate-validator|hibernate-validator-cdi|hibernate-validator-annotation-processor}:6.2.4.Final_. Note that the group id has changed from `org.hibernate` (Hibernate Validator 5 and earlier) to `org.hibernate.validator` (from Hibernate Validator 6 onwards).

Alternatively, a distribution bundle containing all the bits is provided on SourceForge (http://sourceforge.net/projects/hibernate/files/hibernate-validator/6.2.4.Final/hibernate-validator-6.2.4.Final-dist.tar.gz/download[TAR.GZ], http://sourceforge.net/projects/hibernate/files/hibernate-validator/6.2.4.Final/hibernate-validator-6.2.4.Final-dist.zip/download[ZIP]).

== Getting 7.0.5.Final

**Hibernate Validator 7 targets Jakarta EE 9.**

To get the release with Maven, Gradle etc. use the GAV coordinates _org.hibernate.validator:{hibernate-validator|hibernate-validator-cdi|hibernate-validator-annotation-processor}:7.0.5.Final_. Note that the group id has changed from `org.hibernate` (Hibernate Validator 5 and earlier) to `org.hibernate.validator` (from Hibernate Validator 6 onwards).

Alternatively, a distribution bundle containing all the bits is provided on SourceForge (http://sourceforge.net/projects/hibernate/files/hibernate-validator/7.0.5.Final/hibernate-validator-7.0.5.Final-dist.tar.gz/download[TAR.GZ], http://sourceforge.net/projects/hibernate/files/hibernate-validator/7.0.5.Final/hibernate-validator-7.0.5.Final-dist.zip/download[ZIP]).

== Getting 8.0.0.CR2

**Hibernate Validator 8 targets the upcoming Jakarta EE 10.**

To get the release with Maven, Gradle etc. use the GAV coordinates _org.hibernate.validator:{hibernate-validator|hibernate-validator-cdi|hibernate-validator-annotation-processor}:8.0.0.CR2_. Note that the group id has changed from `org.hibernate` (Hibernate Validator 5 and earlier) to `org.hibernate.validator` (from Hibernate Validator 6 onwards).

Alternatively, a distribution bundle containing all the bits is provided on SourceForge (http://sourceforge.net/projects/hibernate/files/hibernate-validator/8.0.0.CR2/hibernate-validator-8.0.0.CR2-dist.tar.gz/download[TAR.GZ], http://sourceforge.net/projects/hibernate/files/hibernate-validator/8.0.0.CR2/hibernate-validator-8.0.0.CR2-dist.zip/download[ZIP]).

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate-validator[hibernate-validator tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-validator/7[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HV[Issue tracker] (bug reports, feature requests)
* https://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
* https://accounts.eclipse.org/mailing-list/bean-validation-dev[Jakarta Bean Validation development mailing list] (discussions about the Jakarta Bean Validation specification)

== What's next?

Depending on the feedback we get on these two Candidate Releases, we will release both Finals in the coming weeks.
