= "Hibernate Validator 8.0.0.CR1 released"
Guillaume Smet
:awestruct-tags: [ "Hibernate Validator", "Releases" ]
:awestruct-layout: blog-post
---

I am glad to announce the release of Hibernate Validator 8.0.0.CR1,
which is the final step before our Final release
(except if important issues are reported, of course).

Hibernate Validator 8 is the Hibernate Validator version targeting Jakarta EE 10
and it is the reference implementation of Jakarta Bean Validation.

== What's new

We already made a few Alphas of Hibernate Validator 8,
mostly to allow integrators to make progress towards the finalization of Jakarta EE 10.

We have made the final adjustments to Hibernate Validator 8,
and we are ready to release it,
pending a stable release of the new Expression Language implementation, Expressly.

If you are a Hibernate Validator user and if you are currently evaluating EE 10,
please give this version a try and report back.

This version is functionally equivalent to Hibernate Validator 6.2 and 7,
except for a few adjustments:

- Our minimal Java version requirement is now Java 11 - https://hibernate.atlassian.net/browse/HV-1887[HV-1887].
- We have a new `@UUID` constraint, allowing to validate UUIDs - https://hibernate.atlassian.net/browse/HV-1867[HV-1867].
- Validated values are not logged when using trace logging, except if you ask otherwise - https://hibernate.atlassian.net/browse/HV-1903[HV-1903].
- We made a small change to the `GetterPropertySelectionStrategy`: the `getGetterMethodNameCandidates()` method now returns a `List` instead of `Set`- https://hibernate.atlassian.net/browse/HV-1853[HV-1853].

The rest of the changes were made to ensure compatibility with Jakarta EE 10.

== Getting 8.0.0.CR1

**Hibernate Validator 8 targets the upcoming Jakarta EE 10.**

To get the release with Maven, Gradle etc. use the GAV coordinates _org.hibernate.validator:{hibernate-validator|hibernate-validator-cdi|hibernate-validator-annotation-processor}:8.0.0.CR1_. Note that the group id has changed from `org.hibernate` (Hibernate Validator 5 and earlier) to `org.hibernate.validator` (from Hibernate Validator 6 onwards).

Alternatively, a distribution bundle containing all the bits is provided on SourceForge (http://sourceforge.net/projects/hibernate/files/hibernate-validator/8.0.0.CR1/hibernate-validator-8.0.0.CR1-dist.tar.gz/download[TAR.GZ], http://sourceforge.net/projects/hibernate/files/hibernate-validator/8.0.0.CR1/hibernate-validator-8.0.0.CR1-dist.zip/download[ZIP]).

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate-validator[hibernate-validator tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-validator/7[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HV[Issue tracker] (bug reports, feature requests)
* https://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
* https://accounts.eclipse.org/mailing-list/bean-validation-dev[Jakarta Bean Validation development mailing list] (discussions about the Jakarta Bean Validation specification)

== What's next?

Depending on the feedback we get on these two Candidate Releases, we will release both Finals in the coming weeks.
