= "Hibernate ORM 5.4.30.Final released"
Andrea Boriero
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:released-version: 5.4.30.Final
:release-id: 31927
---

Today, we published a new maintenance release of Hibernate ORM 5.4: {released-version}.

== Spatial support for CockroachDB

This release introduces a `CockroachDB202SpatialDialect` in the `hibernate-spatial` module, that supports the spatial features available in CockroachDB v20.2 and later.

Just as CockroachDB strives for (https://www.cockroachlabs.com/docs/v20.2/postgresql-compatibility[PostgreSQL compatibility]),
the spatial data support is based on (https://postgis.net/[PostGIS]).
The dialect provides similar functionality as the spatial dialects based on PostgreSQL.

This release also introduces:

* `PostgisPG10Dialect` in the `hibernate-spatial` module, a PostGIS dialect for PostgreSQL 10 (https://hibernate.atlassian.net/browse/HHH-14037[HHH-14037]).
* Support orphan-removal for one-to-one inside components (https://hibernate.atlassian.net/browse/HHH-4815[HHH-4815])

In addition, the release introduces a few minor improvements as well as bug fixes. See below for the complete list
of changes.

=== Bugfixes

You can find the full list of changes in this version https://hibernate.atlassian.net/projects/HHH/versions/{release-id}/tab/release-report-all-issues[here] (or, for people without a Hibernate Jira account, https://hibernate.atlassian.net/secure/ReleaseNote.jspa?version={release-id}&styleName=Html&projectId=10031[here]).

== Thank you

Specials thanks to Karel Maesen for implementing Spatial support for CockroachDB and PostgisPG10Dialect.

== Getting {released-version}

All details are available and up to date on https://hibernate.org/orm/releases/5.4/#get-it[the dedicated page on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
