= "Hibernate ORM {released-version} released"
Andrea Boriero
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:released-version: 5.3.22.Final
:release-id: 31962
---

Today, we published a new maintenance release of Hibernate ORM 5.3: {released-version}.

== JDK 17 support

This release makes even our oldest maintained version compatible with java 17, so even if you don't want to upgrade to Hibernate ORM 5.4 or 5.5 yet, using 5.3 isn't going to hold you back from upgrading to JDK 17.

== Changes

We upgraded Gradle to use the Toolchains support, which allows us to build with Java 8 and run tests on all other versions

We also upgraded ByteBuddy and Javassist to support JDK17 (and works on JDK18 previews as well)

For the full list of changes in this version see the https://hibernate.atlassian.net/issues/?jql=project=10031+AND+fixVersion={release-id}[Release Notes].

== Getting {released-version}

All details are available and up to date on https://hibernate.org/orm/releases/5.3/#get-it[the dedicated page on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
