= "Hibernate ORM {released-version} released"
Andrea Boriero
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:released-version: 5.5.4.Final
:release-id: 31959
---

Happy now to announce a successful release of Hibernate ORM `{released-version}`! It is already available for download from your favourite Maven Central mirror.

== Physical Naming Strategy

A new `CamelCaseToUnderscoresNamingStrategy` has been introduced (see https://hibernate.atlassian.net/browse/HHH-14728[HHH-14728]), the new strategy is the equivalent of the Spring `SpringPhysicalNamingStrategy`.

The `CamelCaseToUnderscoresNamingStrategy` replaces all dots with underscores, all camel casing with underscores and generates all table names in lower case.

For example, the `LineItem` entity will be mapped to the `line_item` table.

== IdentifierGenerator

Hibernate can now get `IdentifierGenerator` definitions from `BeanContainer` when not registered (see https://hibernate.atlassian.net/browse/HHH-14688[HHH-14688]).

== Java 18

We are running tests with an early version of JDK 18 and all tests are green.

== Fixes

Some other defects have been fixed, for a full list see the https://hibernate.atlassian.net/secure/ReleaseNote.jspa?version={release-id}&styleName=Html&projectId=10031[Release Notes].

== Getting {released-version}

All details are available and up to date on https://hibernate.org/orm/releases/5.5/#get-it[the dedicated page on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
