= "Hibernate ORM 5.4.31.Final released"
Andrea Boriero
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:released-version: 5.4.31.Final
:release-id: 31933
---

Today, we published a new maintenance release of Hibernate ORM 5.4: {released-version}.

== Spatial added support for MariaDB 10.3

This release introduces a `MariaDB103SpatialDialect` in the `hibernate-spatial` module, that supports the spatial features available in MariaDB v10.3 and later.


In addition, the release introduces a few minor improvements as well as bug fixes. See below for the complete list
of changes.

=== Bugfixes

You can find the full list of changes in this version https://hibernate.atlassian.net/projects/HHH/versions/{release-id}/tab/release-report-all-issues[here] (or, for people without a Hibernate Jira account, https://hibernate.atlassian.net/issues/?jql=project=10031+AND+fixVersion={release-id}[here]).

== Thank you

Specials thanks to Karel Maesen for implementing Spatial support for MariaDB.

== Getting {released-version}

All details are available and up to date on https://hibernate.org/orm/releases/5.4/#get-it[the dedicated page on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
