= "Hibernate ORM {released-version} released"
Andrea Boriero
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:released-version: 5.5.3.Final
:release-id: 31957
---

Happy now to announce a successful release of Hibernate ORM `{released-version}`! It is already available for download from your favourite Maven Central mirror.

== DDL scripts generation

We have introduced the `hibernate.hbm2ddl.schema-generation.script.append` configuration property, it allows specifying if the schema commands should be appended to the end of the file rather than overwriting the file.

Values are `true` (default value) for appending schema commands to the end of the file, `false` for overwriting the file (see https://hibernate.atlassian.net/browse/HHH-11817[HHH-11817]).

== Performance

The release contains some more small optimisations, this time targeting collection of Statistics of usage of the Query Cache.

== Fixes

Some other defects have been fixed, for a full list see the https://hibernate.atlassian.net/issues/?jql=project=10031+AND+fixVersion={release-id}[Release Notes].

== Getting {released-version}

All details are available and up to date on https://hibernate.org/orm/releases/5.5/#get-it[the dedicated page on hibernate.org].

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
