= "Hibernate ORM {released-version} released"
Andrea Boriero
:awestruct-tags: ["Hibernate ORM", "Releases"]
:awestruct-layout: blog-post
:released-version: 6.0.2.Final
:docs-url: https://docs.jboss.org/hibernate/orm/6.0
:migration-guide-url: {docs-url}/migration-guide/migration-guide.html
:user-guide-url: {docs-url}/userguide/html_single/Hibernate_User_Guide.html
:release-id: 32070

Today, we published a new maintenance release of Hibernate ORM 6.0: {released-version}.

== What's new

This release introduces a few minor improvements as well as bug fixes.

=== Optimisation

We have improved how the `LazyAttributeLoadingInterceptor` is dealing with lazy fields, this makes its processing a bit more efficient and saves a bit of memory as well (see https://hibernate.atlassian.net/browse/HHH-15274[HHH-15274]).

=== Bugfixes

You can find the full list of changes in this version https://hibernate.atlassian.net/secure/ReleaseNote.jspa?version={release-id}&styleName=Html&projectId=10031[here].

== Getting {released-version}

All details are available and up to date on https://hibernate.org/orm/releases/6.0/#get-it[the dedicated page on hibernate.org].

== Conclusion

For additional details, see:

- the link:{user-guide-url}[User Guide]
- the link:{migration-guide-url}[Migration Guide]
- the https://hibernate.org/orm/releases/6.0/[release page].


== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
