= "Hibernate ORM {released-version} released"
Andrea Boriero
:awestruct-tags: ["Hibernate ORM", "Releases"]
:awestruct-layout: blog-post
:released-version: 6.1.1.Final
:docs-url: https://docs.jboss.org/hibernate/orm/6.1
:migration-guide-url: {docs-url}/migration-guide/migration-guide.html
:user-guide-url: {docs-url}/userguide/html_single/Hibernate_User_Guide.html
:release-id: 32080

Today, we published a new maintenance release of Hibernate ORM 6.1: {released-version}.

== What's new

This release introduces a few minor improvements as well as bug fixes.

=== Optimisation

We have improved the memory allocation of the `AbstractEntityPersister.resolveDirtyAttributeIndexes()` method, thanks to Christoph Dreis for his contribution (see https://hibernate.atlassian.net/browse/HHH-15325[HHH-15325]).

=== Subqueries, EmbeddedId and IdClass

The selection of embedded ids or id classes in a from clause subquery is not any more limited to to-one associations (see https://hibernate.atlassian.net/browse/HHH-15367[HHH-15367]).

=== Bugfixes

You can find the full list of changes in this version https://hibernate.atlassian.net/issues/?jql=project=10031+AND+fixVersion={release-id}[here].

== Conclusion

For additional details, see:

- the link:{user-guide-url}[User Guide]
- the link:{migration-guide-url}[Migration Guide]
- the https://hibernate.org/orm/releases/6.1/[release page].


== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
