= "Hibernate ORM {released-version} released"
Andrea Boriero
:awestruct-tags: ["Hibernate ORM", "Releases"]
:awestruct-layout: blog-post
:released-version: 5.6.12.Final
:docs-url: https://docs.jboss.org/hibernate/orm/5.6
:migration-guide-url: https://github.com/hibernate/hibernate-orm/blob/5.6/migration-guide.adoc
:user-guide-url: {docs-url}/userguide/html_single/Hibernate_User_Guide.html
:release-id: 32105

Today, we published a new maintenance release of Hibernate ORM 5.6: {released-version}.

== What's new

This release introduces a few bug fixes and a new feature.

=== New Feature

A new method https://docs.jboss.org/hibernate/orm/5.6/javadocs/org/hibernate/Session.html#getReference(T)[getReference(T)] has been added to `org.hibernate.Session` that receives a detached instance and returns a reference to the persistent instance with the same identity as the given
detached instance (see https://hibernate.atlassian.net/browse/HHH-15508[HHH-15508]).

=== Bugfixes

==== Second Level Cache and One-To-One associations

We have reverted https://hibernate.atlassian.net/browse/HHH-14216[HHH-14216] that was causing https://hibernate.atlassian.net/browse/HHH-15045[HHH-15045] and https://hibernate.atlassian.net/browse/HHH-15235[HHH-15235].

We will work on a better solution for caching entries for one-to-one associations (see https://hibernate.atlassian.net/browse/HHH-15540[HHH-15540])

==== Envers Collections

Thanks to Fabricio Gregorio for fixing `Hibernate.isInitialized()` for Envers collection classes (see https://hibernate.atlassian.net/browse/HHH-15522[HHH-15522])

==== NaturalId and Many-To-One

Loading by its natural identifier an entity having a Many-To-One association annotated with `@NaturalId` is now generating a correct SQL query (see https://hibernate.atlassian.net/browse/HHH-14943[HHH-14943])


You can find the full list of changes in this version https://hibernate.atlassian.net/issues/?jql=project=10031+AND+fixVersion={release-id}[here].


== Conclusion



For additional details, see:

- the link:{user-guide-url}[User Guide]
- the link:{migration-guide-url}[Migration Guide]
- the https://hibernate.org/orm/releases/5.6/[release page].


== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
