= "Hibernate ORM {released-version} released"
Andrea Boriero
:awestruct-tags: ["Hibernate ORM", "Releases"]
:awestruct-layout: blog-post
:released-version: 5.6.10.Final
:docs-url: https://docs.jboss.org/hibernate/orm/5.6
:migration-guide-url: https://github.com/hibernate/hibernate-orm/blob/5.6/migration-guide.adoc
:user-guide-url: {docs-url}/userguide/html_single/Hibernate_User_Guide.html
:release-id: 32076

Today, we published a new maintenance release of Hibernate ORM 5.6: {released-version}.

== What's new

This release introduces a few minor improvements as well as bug fixes.

=== Optimisation

Thanks to Christoph Dreis for his contribution in the improvement of the `AbstractEntityPersister.resolveDirtyAttributeIndexes()` method memory allocation (see https://hibernate.atlassian.net/browse/HHH-15325[HHH-15325]).

=== Bugfixes

==== Association Delete Cascading, Versionless optimistic locking and Dirty OptimisticLockType

We have fixed a bug causing an exception when trying to delete an entity having an association annotated for cascading delete (see https://hibernate.atlassian.net/browse/HHH-15218[HHH-15218]).

You can find the full list of changes in this version https://hibernate.atlassian.net/issues/?jql=project=10031+AND+fixVersion={release-id}[here].

== Conclusion

For additional details, see:

- the link:{user-guide-url}[User Guide]
- the link:{migration-guide-url}[Migration Guide]
- the https://hibernate.org/orm/releases/5.6/[release page].


== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
