= Hibernate 6.4.0.Final
Andrea Boriero
:awestruct-tags: ["Hibernate ORM", "Releases"]
:awestruct-layout: blog-post

:family: 6.4
:docs-url: https://docs.jboss.org/hibernate/orm/{family}
:javadocs-url: {docs-url}/javadocs
:migration-guide-url: {docs-url}/migration-guide/migration-guide.html
:intro-guide-url: {docs-url}/introduction/html_single/Hibernate_Introduction.html
:user-guide-url: {docs-url}/userguide/html_single/Hibernate_User_Guide.html
:ql-guide-url: {docs-url}/querylanguage/html_single/Hibernate_Query_Language.html

Hibernate ORM 6.4.0 has just been released. Simultaneously, 6.3.2 has also been released.


6.4 adds some cool new features, in addition to many improvements and fixes.

[[soft-delete]]
== Soft Delete

6.4 adds support for soft deletes using the new `@SoftDelete` annotation.

[source,java]
----
@Entity
@SoftDelete
class Account {
	...
}
----

Dealing with values as deleted/non-deleted versus active/inactive (reversed) is simple using an annotation attribute:

[source,java]
----
@Entity
@SoftDelete(strategy=ACTIVE)
class Account {
	...
}
----

It even supports pluggable converters for dealing with what gets stored in the database.

See the link:{user-guide-url}#soft-delete[User Guide] for details.

[[hql-vector-suppoet]]

== HQL Vector Support

6.4 introduces a new module `hibernate-vector` that offers support for mathematical vector types and functions that are useful for the AI/ML space to do vector similarity search.

The current implementation only supports running with PostgreSQL with the pgvector extension enabled and maps various functions to the underlying pgvector operators that enable efficient index access.

See the link:{user-guide-url}#vector-module[Query Guide] for details.


[[sqm-array-functions]]
== HQL/Criteria Array Functions

Following up on https://hibernate.atlassian.net/browse/HHH-16780[earlier work], 6.4 adds the
https://github.com/hibernate/hibernate-orm/discussions/5562[remaining] functions for handling
arrays in HQL and Criteria queries.

See the link:{user-guide-url}#hql-functions-arrays[Query Guide] for excellent coverage of these functions.

[NOTE]
====
These functions are still incubating and some things (names, etc.) may change before Final.
====


[[jfr-events]]
== Java Flight Recorder Events

6.4 adds support for producing Java Flight Recorder (JFR) events.
This works natively on many JDKs, but we recently discovered that not all of them implement the JFR spec, despite it being part of Open JDK.

For this reason we have created a separate module that will ensure compatibility, and applications will need to include the new `hibernate-jfr` artifact on the classpath in order to use Java Flight Recorder events integration.

See the link:{user-guide-url}#appendix-monitoring-with-JFR[User Guide] for details.


[[non-strng-tenant-id]]
== Non-String Tenant Id

6.4 adds support for using tenant-id with types other than String.

See https://hibernate.atlassian.net/browse/HHH-14822[HHH-14822] for details.


== Conclusion

For additional details, see:

- the https://hibernate.org/orm/releases/6.4/[release page]
- the link:{migration-guide-url}[Migration Guide]
- the link:{intro-guide-url}[Hibernate 6 Introduction]
- the link:{user-guide-url}[User Guide]

See also the following resources related to supported APIs:

- the https://hibernate.org/community/compatibility-policy/[compatibility policy]
- the link:{docs-url}/incubating/incubating.txt[incubating API report] (`@Incubating`)
- the link:{docs-url}/deprecated/deprecated.txt[deprecated API report] (`@Deprecated` + `@Remove`)
- the link:{docs-url}/internals/internal.txt[internal API report] (internal packages, `@Internal`)

== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.zulipchat.com/#narrow/stream[Chat] (usage questions)
* https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
