= "Hibernate ORM {released-version} released"
Andrea Boriero
:awestruct-tags: ["Hibernate ORM", "Releases"]
:awestruct-layout: blog-post
:released-version: 5.6.15.Final
:docs-url: https://docs.jboss.org/hibernate/orm/5.6
:migration-guide-url: https://github.com/hibernate/hibernate-orm/blob/5.6/migration-guide.adoc
:user-guide-url: {docs-url}/userguide/html_single/Hibernate_User_Guide.html
:release-id: 32121

Today, we published a new maintenance release of Hibernate ORM 5.6: {released-version}.

== What's new

This release introduces a few minor improvements as well as bug fixes.

=== Bugfixes

==== MariaDB sequence identifier

We have fixed a bug causing an error when Hibernate tries to retrieve the information about existing sequences (see https://hibernate.atlassian.net/browse/HHH-15665[HHH-15665]).

==== Bytecode enhancement and dirty checking

We have fixed a bug causing the execution of unnecessary SQL update statements when setting a property to its current value (see https://hibernate.atlassian.net/browse/HHH-16049[HHH-16049])

You can find the full list of changes in this version https://hibernate.atlassian.net/secure/ReleaseNote.jspa?version={release-id}&styleName=Html&projectId=10031[here].

== Conclusion

For additional details, see:

- the link:{user-guide-url}[User Guide]
- the link:{migration-guide-url}[Migration Guide]
- the https://hibernate.org/orm/releases/5.6/[release page].


== Feedback, issues, ideas?

To get in touch, use the usual channels:

* https://stackoverflow.com/questions/tagged/hibernate[**hibernate** tag on Stack Overflow] (usage questions)
* https://discourse.hibernate.org/c/hibernate-orm[User forum] (usage questions, general feedback)
* https://hibernate.atlassian.net/browse/HHH[Issue tracker] (bug reports, feature requests)
* http://lists.jboss.org/pipermail/hibernate-dev/[Mailing list] (development-related discussions)
