= Fourth bug-fix release for ORM 5.0
Steve Ebersole
:awestruct-tags: ["Hibernate ORM", "Releases"]
:awestruct-layout: blog-post

The fourth bug-fix release for Hibernate ORM 5.0 has just been http://github.com/hibernate/hibernate-orm/releases/tag/5.0.4[tagged] and published.

There are 52 issues resolved in this release.  20 of those came out of the recent http://in.relation.to/2015/10/27/great-jira-cleanup-2015/[Jira cleanup].  Initially that initiative pulled in roughly 750 issues.  To date, 66 of those have been resolved - fixed or verified as out-of-date, unable-to-reproduce, etc.  An additional 14 have been more propoerly reclassified as feature or enhancement requests rather than bugs.  The really cool part is the amount of community help we have gotten in making that happen!  Thanks to everyone responding, verifying and even fixing alot of these bugs!

The complete list of changes can be found http://hibernate.atlassian.net/projects/HHH/versions/21750[here].  _People without a Hibernate Jira account will not be able to access the previous link and can access the changelog https://github.com/hibernate/hibernate-orm/blob/5.0.4/changelog.txt[in GitHub]; the issue I reported with Atlassian has been resolved and is ready for deployment into our hosted environment, I just do not know when that will happen._

For information on consuming the release via your favorite dependency-management-capable build tool, see http://hibernate.org/orm/downloads/

For those of you allergic to dependency-management-capable build tools, the release bundles can be obtained from 
http://sourceforge.net/projects/hibernate/files/hibernate-orm/5.0.4.Final/[SourceForge] or 
http://bintray.com/hibernate/bundles/hibernate-orm/5.0.4.Final[BinTray].

