= Hibernate ORM 5.3.0.Beta2 release
Steve Ebersole
:awestruct-tags: ["Hibernate ORM", "Releases"]
:awestruct-layout: blog-post

This is the second Beta release in the Hibernate ORM 5.3 family.  5.3 represents a JPA 2.2 compatible version
on top of 5.2.  Beta2 is mainly minor bug-fixes and improvements.  Changes of note include:

* Move to Bintray for artifact publishing.  This move has been long-planned, and we finally were finally able to implement it.  From Bintray the artifacts are synced to both JCenter and Maven Central.
* New https://agroal.github.io/[Agroal]-based `ConnectionProvider`
* The issues with documentation uploading have been resolved, so documentation for 5.3 is now available from the doc server.  See the ORM http://hibernate.org/orm/documentation/5.3/[documentation] page.

See Jira for the complete list of https://hibernate.atlassian.net/projects/HHH/versions/31621/tab/release-report-done[changes]

See the http://hibernate.org/orm/releases/5.3/[downloads] page for details on obtaining this release

__NOTE : I actually did the release last Wednesday as scheduled, but have been very sick and am just getting around to doing these ancilary tasks.  I apologize for the delay__
