= Hibernate ORM 6.0.0.CR2 released
Steve Ebersole
:awestruct-tags: [ "Hibernate ORM", "Releases" ]
:awestruct-layout: blog-post
:released-version: 6.0.0.CR2
:release-id: 32033
---

The second candidate release for Hibernate ORM 6.0 has been released.

We fully expect this to be the last release candidate and currently plan on having the 6.0 final release within the next 2-4 weeks.

This release was held up a bit working on passing the Jakarta Persistence TCK.  Mainly we had to wait for our challenges and proposed challenges 
to be discussed and accepted.  This release fully passes the 3.1 TCK!  Hopefully we will soon pass the 3.0 TCK as well, but we are still waiting on
resolution of some challenges there.

Much of the work in this release focused on the TCK.  A few other items of note...

* Artifacts published to Maven Central are now signed.  See https://hibernate.atlassian.net/browse/HHH-14604[HHH-14604].
* Fix some timing issues with CDI integration.  See https://hibernate.atlassian.net/browse/HHH-15068[HHH-15068] and https://hibernate.atlassian.net/browse/HHH-15084[HHH-15084].
* Corrected and improved the behavior of `@NotFound` mappings.  See https://hibernate.atlassian.net/browse/HHH-15099[HHH-15099] and https://hibernate.atlassian.net/browse/HHH-15106[HHH-15106].


See the https://docs.jboss.org/hibernate/orm/6.0/userguide/html_single/Hibernate_User_Guide.html[user guide] and
https://github.com/hibernate/hibernate-orm/blob/6.0.0.CR2/migration-guide.adoc[migration guide].

Also check out the https://hibernate.org/orm/releases/6.0/[release page].

To get in touch, use the usual channels as discussed on https://hibernate.org/community/
