= Hibernate 6.2 CR3
Steve Ebersole
:awestruct-tags: ["Hibernate ORM", "Releases"]
:awestruct-layout: blog-post
:major-minor: 6.2
:docs-url: https://docs.jboss.org/hibernate/orm/{major-minor}
:javadocs-url: {docs-url}/javadocs
:migration-guide-url: {docs-url}/migration-guide/migration-guide.html
:user-guide-url: {docs-url}/userguide/html_single/Hibernate_User_Guide.html

Hibernate ORM 6.2.0.CR3 has just been released.  It contains 64 resolutions, including 37 bug-fixes.  Many of these improvements come directly from the excellent feedback and bug reports we continue to get from the community.  Thank you again for the continued support and feedback!


== What's next?

We will hold releasing a `Final` until a few integration contracts stabilize, especially as https://hibernate.org/reactive/[Hibernate Reactive] makes a push to 2.0.  That is expected to be very short term.


== Community

For additional details, see:

- the link:{user-guide-url}[User Guide]
- the link:{migration-guide-url}[Migration Guide]
- the https://hibernate.org/orm/releases/{major-minor}/[release page]
- the link:{docs-url}/incubating/incubating.txt[incubating report]
- the link:{docs-url}/deprecated/deprecated.txt[deprecation report]
- the link:{docs-url}/internals/internal.txt[internals report]
- the https://hibernate.org/community/compatibility-policy/[compatibility policy]

See the https://hibernate.org/community/[website] for getting in touch with us.
