= Investigating Move to Apache License
Steve Ebersole
:awestruct-tags: ["Hibernate ORM"]
:awestruct-layout: blog-post

We are considering a change of license for Hibernate projects to Apache License 2.0.  In fact, more recent Hibernate projects have  
started out using that license.

[NOTE]
====
While we still believe that our long published interpretation of LGPL to be compatible with ASL and similar licenses, enough https://en.wikipedia.org/wiki/Fear,_uncertainty,_and_doubt[FUD] has been spread about 
it to be considered a lost cause in terms of inclusion in various projects.  At this point, it just makes sense to change - it opens up wider acceptance amongst Apache/Jakarta projects and others.
====

In the coming weeks we will be sending emails to developers who have made significant, still-relevant contributions to the codebase over the years.   We want to respect the wishes of all of us.

Questions about the change are best directed to one of the https://hibernate.org/community/[communication channels].
