= Release Announcements
Steve Ebersole
:awestruct-tags: ["Hibernate ORM"]
:awestruct-layout: blog-post

As we have continued automating much of our processes, one item that has become increasing more scripted is releases.
That automation creates a https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases[GitHub release] for each release we do.

GitHub exposes an RSS feed for a project's releases.
For Hibernate ORM, that URL is https://github.com/hibernate/hibernate-orm/releases.atom footnote:[The format for the RSS feed URL is standardized - https://github.com/{organization}/{project}/releases.atom].

There are many excellent ways to be notified of releases through this RSS feed, including many email clients.
And many people already consume these release announcements using RSS from this site.

For these reasons, we have decided to no longer write blog posts or send emails to the hibernate-announce and hibernate-dev mailing lists
for _micro_ (bugfix) releases of Hibernate ORM.

We will continue to write blog posts and email announcements for some releases with notable features and improvements,
in particular major (`x.0.0.Final`) and minor (`x.y.0.Final`) releases.
