= Hibernate 8.0.0.Beta3
Steve Ebersole
:toc:
:toclevels: 2
:awestruct-tags: ["Hibernate ORM", "Releases"]
:awestruct-layout: blog-post

Hibernate ORM 8.0.0.Beta3 is now available.

Coming just a few days after Beta2, the third beta of Hiberante ORM 8.0 is a bit lighter than usual.

Compared to Beta2, notable changes include:

* *https://hibernate.atlassian.net/browse/HHH-20929[Bootstrap logging changes]*
+
Info-level logs about the Hibernate ORM version or database info, generally happening on startup,
are now grouped under the same category `org.hibernate.orm.info`,
making it easier to suppress them in your logger configuration.
* *A setting for the accessor strategy*
+
If for some reason Hibernate ORM's https://github.com/hibernate/hibernate-orm/pull/13140[new and improved way of accessing entity data] is causing trouble in your environment, you can first report it, then set `hibernate.accessor.strategy` to `reflection` in order to revert to (less efficient) pre-8.0 behavior and continue testing.
* Various additional fixes (https://hibernate.atlassian.net/browse/HHH-20932[HHH-20923], https://hibernate.atlassian.net/browse/HHH-20933[HHH-20933], https://hibernate.atlassian.net/browse/HHH-20941[HHH-20941]), and some cleanup (https://hibernate.atlassian.net/browse/HHH-20932[HHH-20932], https://hibernate.atlassian.net/browse/HHH-20938[HHH-20938])

When upgrading directly from Beta1,
be sure to read the https://in.relation.to/2026/09/23/orm-80-beta2/[8.0.0.Beta2 announcement],
which includes many more highlights.

Other useful resources include:

* https://docs.hibernate.org/orm/8.0/migration-guide/[Migration Guide]
* https://docs.hibernate.org/orm/8.0/whats-new/whats-new.html[What’s New]
* https://github.com/hibernate/hibernate-orm/releases/tag/8.0.0.Beta2[Release Details]

Note that 8.0 remains in beta while Jakarta Persistence is not yet approved.

Please try Beta3 with your applications and let us know about any regressions or migration difficulties through https://hibernate.atlassian.net/[Hibernate Jira].
